### PR TITLE
NAS-120490 / 23.10 / [SCALE/Apps]: Editing an app with a `type: list` variable with added items, fails to render

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Use this machine for testing:
http://mini3xlp-101.dc1.ixsystems.net/ui/sessions/signin

Go to APPS, find `Minio` installed.

(minio image environment)

image

Data should be prefilled with previously saved data (on create)

Or contact @stavros-k regarding this ticket, he can setup an app on any machine 💪

### CODE REVIEW

**Review by RehanY147 — COMMENTED** [review]
@AlexKarpov98 Need instructions or bug reproduction and testing. I tried adding a list item with some values and it loads ok on master

**Comment by AlexKarpov98** [comment]
@RehanY147  - please go ahead again, I updated description 🔝

**Review by RehanY147 — COMMENTED** [review]
Still can't reproduce this issue on master. Will ask reporter for details.

**Comment by AlexKarpov98** [comment]
merged with other task

**Pull request closed without merging**
