### PR TITLE
NAS-131118 / 25.04 / All discovery apps get `installed` flag once I start or stop installed application

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: 
See ticket, result ⬇️ 

https://github.com/user-attachments/assets/573ec19b-6a98-4e63-a8bd-27ebe275c77f

### CODE REVIEW

**Comment by undsoft** [comment]
RC1 is already in code freeze.

**Comment by AlexKarpov98** [comment]
> RC1 is already in code freeze.

@undsoft  should I use `24.10.0 `?

**Comment by undsoft** [comment]
Yes. I see that branches were not created yet, but they will be soon.

**Review by bvasilenko — APPROVED** [review]
Issue no longer occurs

**Pull request merged**
