### PR TITLE
NAS-123295 / 23.10 / Added error handling on Shares Dashboard 

### PR DESCRIPTION
**Pull request by RehanY147**

### CODE REVIEW

**Review by undsoft — COMMENTED** [review]
I feel like the video is suggestive of there being a problem when saving smb acl, not necessarily when loading it.

**Review by dszidi — APPROVED** [review]
Looks good

**Comment by RehanY147** [comment]
@undsoft Andrew commented on the ticket that the issue was the when saving, websocket was throwing an error and UI wasn't showing that error. So it seemed like the save was successfull.

**Comment by undsoft** [comment]
@RehanY147 I just don't see how adding error handling on loading solves the issue in the ticket. Were you able to reproduce it by rebooting the system?

**Review by undsoft — CHANGES_REQUESTED** [review]
.

**Comment by RehanY147** [comment]
This seems like a middleware issue upon investigation. Closing.

**Pull request closed without merging**
