### PR TITLE
NAS-127042 / 24.10 / Refactor SnapshotTaskListComponent to ix-tables2

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: See ticket (refactoring)

Screenshot 2024-02-08 at 12 52 37

### CODE REVIEW

**Review by bvasilenko — CHANGES_REQUESTED** [review]
Looks like something is not right with the formatting of **Next Run** within expandable section. Same for **Last Run**.

image

Also, after choosing **Last Run** column to be shown, the formatting of column value is also missing

image

**Comment by AlexKarpov98** [comment]
@bvasilenko - we have an issue with **relativeDateColumn** - it only works for the table cell, not inside of the details panel - I currently replaced it with textColumn, so that value transformation will also work inside of the details as well.

I updated `Last Run` as well:

Screenshot 2024-02-08 at 13 06 07

**Comment by AlexKarpov98** [comment]
@bvasilenko - would be good to find a way to still use `relativeDateColumn`, it adds nice tooltip.

Screenshot 2024-02-08 at 13 07 37

Or we should use relativeDateColumn for card only, and for list page - we can use textColumn with correct text

**Comment by AlexKarpov98** [comment]
@bvasilenko - as well a new bug (ticket) was created https://ixsystems.atlassian.net/browse/NAS-127279

**Review by bvasilenko — APPROVED** [review]
Looks good to me

**Pull request merged**
