### PR TITLE
NAS-115547 / 22.12 / NAS-115547: Refactor KerberosKeytabsFormComponent to ix-forms

### PR DESCRIPTION
**Pull request by bvasilenko**
Testing:
- Credentials -> Directory Services -> Kerberos Keytab

### CODE REVIEW

**Comment by denysbutenko** [comment]
getting validation error
image

Is it required the latest nightly?

**Comment by denysbutenko** [comment]
@bvasilenko do you have an example of the file?

**Review by denysbutenko — CHANGES_REQUESTED** [review]
Waiting for response

**Comment by bvasilenko** [comment]
No there's no example, what I did is just used mockups.

**Review by denysbutenko — APPROVED** [review]
Looks good

**Pull request merged**
