### PR TITLE
NAS-125246 / 24.04 / Use Translated Names for Privilleges

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: 
You should now see it updated http://localhost:4200/credentials/groups/privileges:

Screenshot 2023-11-16 at 15 23 27
Screenshot 2023-11-16 at 15 23 44

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
That's cool, but strings are not actually translated, only marked for translation (translation pipe is not called).
See `translateOptions` and other methods.

**Comment by AlexKarpov98** [comment]
> That's cool, but strings are not actually translated, only marked for translation (translation pipe is not called). See `translateOptions` and other methods.

ohhh, really, I didn't notice there are no translations added actually, my bad.

**Comment by AlexKarpov98** [comment]
> That's cool, but strings are not actually translated, only marked for translation (translation pipe is not called). See `translateOptions` and other methods.

@undsoft  - I checked, we already have these translations in `.json` files.
I used them previously for a [directive for hiding UI elements based on role](https://ixsystems.atlassian.net/browse/NAS-125091)

**Comment by undsoft** [comment]
@AlexKarpov98 They are in .json files because you have marked them for translation with T. They will not be in fact translated if you switch truenas language to something else.

**Comment by AlexKarpov98** [comment]
@undsoft - now it's using translation strings 😃

**Review by undsoft — APPROVED** [review]
Thanks, looks good.

**Pull request merged**
