### PR TITLE
NAS-110839 / 21.08 / Add unit tests to github actions

### PR DESCRIPTION
**Pull request by dszidi**

### CODE REVIEW

**Review by undsoft — APPROVED** [review]
👍🏼

**Comment by dszidi** [comment]
It seems there is a problem. The environment setup script is not run in the ci environment so the test fails. We need to mock this somehow in the unit tests.

**Comment by undsoft** [comment]
@dszidi I think environment.ts is created during the build. You can try swapping steps.

**Comment by dszidi** [comment]
Putting it last didn't work. Going to try running tests before the build but using setup_env.js to create an environment file. The build in the next step should overwrite that environment file.

**Pull request merged**
