### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by MDVAurelien**
Fix display problem. Translation is not important here

### CODE REVIEW

**Review by undsoft — APPROVED** [review]
Thanks, you can also create a ticket for us to fix the issue.

**Comment by AlexKarpov98** [comment]
revert

**Comment by AlexKarpov98** [comment]
I've reverted this change since it's fixed on UI side to fit the text: 
https://github.com/truenas/webui/pull/10751

**Comment by MDVAurelien** [comment]
Hi thks Alex, TOP ! Great team !

**Pull request merged**
