### PR TITLE
NAS-113598 / 22.02-RC.2 / NAS-113598: Added navigation on cancel click

### PR DESCRIPTION
**Pull request by RehanY147**
To test,
1. Create encrypted datasets on a pool
2. Export dataset keys from the pool `cog` icon drop down. (Not dataset three dot menu)
3. Export/Disconnect the pool
4. Import the same pool again
5. You should see a prompt that asks if you want to unlock your locked datasets
6. Click on `Continue`
7. Provide the dataset keys json file you downloaded in step 2
8. Click on save and follow the process.
9. On the last `Close` button when you're done unlocking datasets, you should be navigated to the `Storage` page again automatically

### CODE REVIEW

**Comment by denysbutenko** [comment]
@RehanY147 where did you test it? I'm getting a failure on step 8 when trying to unlock datasets on `TrueNAS-SCALE-22.02-MASTER-20211210-034401` version that running in VM. Our cloud VM does not have available pools for testing.
image

**Review by undsoft — CHANGES_REQUESTED** [review]
Same here on local.

**Comment by RehanY147** [comment]
This looks like an issue with the middleware side of things. It's happening on master branch as well so not related to this PR.

**Comment by undsoft** [comment]
Has this been reported to middleware? Does it happen in RC2? How can we test the PR without it working?

**Comment by RehanY147** [comment]
> Has this been reported to middleware? Does it happen in RC2? How can we test the PR without it working?

Yes. I've talked to Waqar about this. We identified a regression with middleware that he's working on. It's unrelated to UI.

**Comment by RehanY147** [comment]
I think this can be tested now with the latest nightly @undsoft @denysbutenko

**Review by undsoft — APPROVED** [review]
Works well.

**Pull request merged**
