### PR TITLE
NAS-114447 / None / NAS-114447: Refactor Truecommand button into separate components

### PR DESCRIPTION
**Pull request by bvasilenko**
Testing:

1. Click "TrueCommand" icon in the top bar
2. Fill the form:
   - Use any 16 characters as API key
   - Keep "Enabled" unchecked to bypass "Invalid API key" error
3. Try changing API key to another with "Save"
4. Try resetting the API key with "Deregister"

### CODE REVIEW

**Review by AlexKarpov98 — CHANGES_REQUESTED** [review]
Look good!

Right-aligned buttons
Screenshot_2
Screenshot_3

Connecting animation in Truecommand icon.
Screenshot_5

Enable `connect button` after unchecked `Enable` without API key
Screenshot_4

**Comment by bvasilenko** [comment]
@AlexKarpov98 
>Enable connect button after unchecked Enable without API key
Could not understand that. Please provide 1-2-3 steps and Actual vs Expected comparison. Thanks

**Comment by AlexKarpov98** [comment]
> 

Sorry, Attached the gif images (before & after)
Before:
Before
After:
After

**Review by AlexKarpov98 — CHANGES_REQUESTED** [review]
Though validation was removed, It would not show the dialog verification instructions email like before, it shows dialog of the validation of API key

**Comment by AlexKarpov98** [comment]
LGTM! 👍

**Pull request merged**
