### PR TITLE
NAS-112795 / None / NAS-112795: fixed form-input value overlap icon

### PR DESCRIPTION
**Pull request by Raz-Dva**
Check the password fields that have a button to toggle the display of the password

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
It's better to add styles to form-input styles and not to global styles.

**Review by undsoft — CHANGES_REQUESTED** [review]
Doesn't look to good here.
Снимок экрана 2022-01-30 в 12 42 58

**Review by undsoft — CHANGES_REQUESTED** [review]
As discussed on Slack
> width: 372px !important;
needs to be removed completely.

**Review by RehanY147 — COMMENTED** [review]
Waiting for changes on previous comments by @undsoft

**Review by undsoft — APPROVED** [review]
Looks good.

**Pull request merged**
