### PR TITLE
NAS-113267 / 22.02-RC.2 / NAS-113267: Refactoring catalog form and pull image form

### PR DESCRIPTION
**Pull request by undsoft**
Test following forms in Apps:
- Catalogs -> Add
- Catalogs -> Edit
- Docker Images -> Add

Notes:
Fields in Pull image form were reorganized to make it clear that authentication is optional in most cases.
Additional cdr.markForChecks() were added to make life easier for our friends in Release Engineering.

### CODE REVIEW

**Review by dszidi — COMMENTED** [review]
I'm getting this error when trying to add the truecharts catalog.

image

**Comment by undsoft** [comment]
Truecharts doesn't have `charts` train. See connection details here: https://truecharts.org/manual/Quick-Start%20Guides/02-Adding-TrueCharts/

**Comment by dszidi** [comment]
Ah yes, setting the preferred train to stable was what I was missing. All seems to be fine now. LGTM

**Review by dszidi — APPROVED** [review]
LGTM

**Pull request merged**
