### PR TITLE
NAS-118505 / 13.0 / Added r50bm

### PR DESCRIPTION
**Pull request by RehanY147**
Check out ticket description for testing

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
1. When I click on REAR in enclosure UI management, the image is ginormous.
2. I've created a pool using `nvd` disks. I don't know if they should be shown here, but they aren't:
Снимок экрана 2022-10-17 в 11 04 23

**Comment by RehanY147** [comment]
The nvme disks are shown on the rear @undsoft

**Review by undsoft — CHANGES_REQUESTED** [review]
As mentioned on Slack, when I've created a pool with all disks and then went to enclosure management, I could still two unused disks and no disks on the rear for some reason.

**Comment by RehanY147** [comment]
@undsoft I've solved the issue of unassigned pool. but the unassigned vdev issue still persists on certain disks. this looks like the unassigned vdev is separate issue triggered by older code. I created this ticket for it. https://ixsystems.atlassian.net/browse/NAS-118658

**Comment by RehanY147** [comment]
@undsoft the enclosure has `has_slot_status` property `false`. Which means rear disks are not "identifiable". Need more clarification from someone from middleware.

**Comment by RehanY147** [comment]
It also seems like in `disk.query` response, the first 48 disks (that show up on the front view) have enclosure info like `number` and `slot` but the last four (that appear on the rear view) have `enclosure` property set to `null` in the `disk.query` response. Which is why UI can't identify those four disks to be part of any enclosure so they get excluded from selection querying.

**Review by undsoft — APPROVED** [review]
Appears to be working correctly now.

**Comment by undsoft** [comment]
backport

**Comment by undsoft** [comment]
backport

**Pull request merged**
