### PR TITLE
NAS-115077 / 22.12 / NAS-115077: Added close button

### PR DESCRIPTION
**Pull request by RehanY147**

### CODE REVIEW

**Comment by denysbutenko** [comment]
Not sure if that's related to the ticket but..

https://user-images.githubusercontent.com/351613/158996481-e5844f2c-e97f-4d88-81b1-5e9bbfa9a929.mp4

Dry Run Cloud Sync Task dialog is unusable

**Comment by RehanY147** [comment]
> Kapture.2022-03-18.at.17.03.03.mp4
> 
> Dry Run Cloud Sync Task dialog is unusable

This is a different issue. It should be addressed in a separate ticket. Might be out of scope for this one.

**Comment by denysbutenko** [comment]
> > Kapture.2022-03-18.at.17.03.03.mp4
> > Dry Run Cloud Sync Task dialog is unusable
> 
> @denysbutenko This is a different issue. It should be addressed in a separate ticket. Might be out of scope for this one.

Okay. I tried to run the `Dry Run` task from Data Protection Dashboard it shows confirmation that the task was executed seems like the wrong place. Then I clicked on the Dry Run button in the Cloud Sync Form and the result is above. It seems there is no button to close or cancel this dialog. How to test the fix?

**Comment by RehanY147** [comment]
@denysbutenko I should've added a description. But you're supposed to test the abort process. check
1. The abort button shows up while running the dry run task
2. When you abort, the dialog is closable afterwards.

**Comment by denysbutenko** [comment]
> @denysbutenko I should've added a description. But you're supposed to test the abort process. check
> 
> 1. The abort button shows up while running the dry run task
> 2. When you abort, the dialog is closable afterwards.

There is no `abort` button in the dialog. I've checked the websocket messages: `cloudsync.onetime_sync` is not abortable. Maybe I'm doing something wrong?

**Comment by denysbutenko** [comment]
https://user-images.githubusercontent.com/351613/159106719-293305ec-1b36-4162-af73-f8b675df134b.mp4

**Comment by RehanY147** [comment]
@denysbutenko What build version are you using to test this? Try testing on the latest nightly. The changes on the middleware side are pretty recent.

**Review by denysbutenko — APPROVED** [review]
image
Works well on latest nightly 👍🏻

**Pull request merged**
