### PR TITLE
NAS-116556 / 22.02.4 / NAS-116556: Disabling netbios fields

### PR DESCRIPTION
**Pull request by bvasilenko**
**Testing**

On the **Credentials > Directory Services** page

When **Active Directory** is enabled

- **Netbios Name** (`netbiosname`) input field should be disabled

- **NetBIOS alias** (`netbiosalias`) field should be disabled

### CODE REVIEW

**Review by RehanY147 — COMMENTED** [review]
@bvasilenko Can you point out a machine that I can test this on? I am having issues setting up `Active Directory` on my machine.

**Comment by bvasilenko** [comment]
@RehanY147 

> The fields show up when you're setting up AD. Then I save it after checking the Enable checkbox. Then I go back to the settings form and the fields are disabled. However, once I uncheck the enable checkbox and save the form. The next time I open the form, the fields are still disabled. 

Now when you uncheck  **Enabled**, save, and next time open the form, the fields will be enabled again.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Still seeing the same issue
image

**Comment by bvasilenko** [comment]
Thanks for doing a review, @RehanY147  . I've checked your screenshot, and found out that your screenshot shows the GUI portion, not related to the ticket.

To my understanding, fields of interest are **Netbios Name** (`netbiosname`) and **NetBIOS alias** (`netbiosalias`) . These 2 fields are located at the **Advanced settings**

**AD Disabled** => user can edit netbios name/alias

https://user-images.githubusercontent.com/20611516/185741744-743521db-740a-4929-a7fe-3b3fb21c4bbf.mp4

**AD Enabled** => user cannot edit netbios name/alias

https://user-images.githubusercontent.com/20611516/185741747-646d9690-1b39-4da0-8456-ed88626fcb59.mp4

On these videos I am testing AD connection to a VM at my home.

**Review by RehanY147 — APPROVED** [review]
Looks good

**Pull request merged**
