### PR TITLE
NAS-116385: Support for Hyper-V enlightenments

### PR DESCRIPTION
**Pull request by heppu**
UI support for https://github.com/truenas/middleware/pull/9034

### CODE REVIEW

**Comment by AlexKarpov98** [comment]
Waiting for middleware approval.

**Review by AlexKarpov98 — COMMENTED** [review]
Waiting for middleware approval.

**Comment by heppu** [comment]
Middleware support has now been merged and I have rebased this review on top of latest master.

**Comment by AlexKarpov98** [comment]
@heppu Could you create a new vm?
I got a keyError `min_memory` in `master` branch
Screenshot_40

Same error in this `hyperv-enlightenments` branch, but does not show error dialog.
Code change looks good.

**Review by AlexKarpov98 — COMMENTED** [review]
Code change look good

**Comment by heppu** [comment]
> @heppu Could you create a new vm? I got a keyError `min_memory` in `master` branch Screenshot_40
> 
> Same error in this `hyperv-enlightenments` branch, but does not show error dialog. Code change looks good.

I'm currently on vaction and don't have my laptop with me but that error shouldn't have anything to do with this review. There was separate feature merged about min_memory which could be causing that.

**Comment by heppu** [comment]
Hi, back from vacation @undsoft. Rebased to latest master.

**Review by AlexKarpov98 — CHANGES_REQUESTED** [review]
The frontend is looks good and the relevant code is good as well.

One thing for the submit code:
I think an hyperv_enlightenments prameter should be considered in the submit formdata.
Screenshot_10

**Comment by heppu** [comment]
> One thing for the submit code: I think an `hyperv_enlightenments` prameter should be considered in `customSubmit` finction.


@AlexKarpov98 Done

**Comment by heppu** [comment]
Anyone able to take a look at this before next merge conflict. :D @AlexKarpov98 @undsoft

**Review by undsoft — APPROVED** [review]
Looks good. Thank you for your contribution.

**Pull request merged**
