### PR TITLE
NL translation

### PR DESCRIPTION
**Pull request by renediepenbroek**
nl.json is 100% translated (2023-11-24),
René

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
Hi, thank you for your contribution.
Could you remove `nl.json` from the root that you've added. We only need one in `assets/i18n`.
There is also a conflict in `nl.json` between your branch and master.

**Comment by AlexKarpov98** [comment]
@renediepenbroek - please resolve conflicts inside of the `nl.json`

**Comment by renediepenbroek** [comment]
Hello Alex,

I checked my nl.json but cannot find any problem with syntax and/or 
structure. But your message 'resolve confilcts' is 'a little bit too 
glaboal' .... I have no idea where to search and probably you have had 
an indication of the kind of problem ... So when you can inform me where 
I have to look that would be very nice ...

Best regards,


René Diepenbroek


------ Oorspronkelijke bericht ------
Van "Alex Karpov" ***@***.***>
Aan "truenas/webui" ***@***.***>
CC "René" ***@***.***>; "Mention" 
***@***.***>
Datum 1-2-2024 06:59:35
Onderwerp Re: [truenas/webui] NL translation (PR #9245)

**Comment by AlexKarpov98** [comment]
Hello @renediepenbroek. 
I took your translations to another PR, we gonna merge it soon.
https://github.com/truenas/webui/pull/9664
Thank you for contribution.

BTW - now you have 349 strings more to translate 😄 (we did a bunch of updates from the last time you added translations)

Screenshot 2024-02-12 at 10 17 18

**Pull request closed without merging**
