### PR TITLE
NAS-118492 / 22.12 / Datasets detail cards should realign to fill horizontal space first

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Test with datasets | devices side columns on any screen size.

### CODE REVIEW

**Review by RehanY147 — COMMENTED** [review]
@undsoft Are we OK with changing order and placement of certain cards to make them fit better horizontally?

**Review by dszidi — COMMENTED** [review]
I'm getting this single column layout in between breakpoints

image

**Comment by AlexKarpov98** [comment]
@dszidi  - is that the only problem?

**Comment by AlexKarpov98** [comment]
@dszidi fixed the issue, as well improved mobile, tablet view.

**Review by dszidi — APPROVED** [review]
Yep just checked it again. Looks good. Nice work!

**Pull request merged**
