### PR TITLE
NAS-125720 / 24.04 / NAS-125720 - Add License Text to WebUI Repo

### PR DESCRIPTION
**Pull request by kmoore134**

### CODE REVIEW

**Comment by undsoft** [comment]
Shouldn't it be called `LICENSE`. Seems like this is what github understands https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by kmoore134** [comment]
Good point. I had seen the preference for GPL was to use COPYING, so I've just sym-linked it to make sure both bases are covered.

**Review by undsoft — APPROVED** [review]
👍🏻

**Comment by undsoft** [comment]
Looks like github doesn't understand symlinks. Front page now says  `Unknown, GPL-3.0 licenses found`

**Comment by kmoore134** [comment]
GitHub is lame :) But it answers the question as to which files to use, the answer is "both" work. I'll just standardize on LICENSE then

**Pull request merged**
