### PR TITLE
NAS-121432 / 23.10 / Various fixes for Available Apps

### PR DESCRIPTION
**Pull request by denysbutenko**
Details in the ticket

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Let's make the installed badge clickable every where. Like on the Available Apps page. Also, the add the tooltip. Also fix the tooltip text to say `"An instance of this app already installed. Click the badge to see installed apps."`

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Everything looks good. This is something extra but falls under the scope of this ticket. We should have a skeleton loading for the app cards for a couple of categories, also category titles.

**Comment by denysbutenko** [comment]
> Everything looks good. This is something extra but falls under the scope of this ticket. We should have a skeleton loading for the app cards for a couple of categories, also category titles.

Sure, good idea. Thanks for bringing it to my attention.

**Comment by undsoft** [comment]
I liked previous loading for app cards more. At least on our m40 loading a list of apps is not a fast operation and animation on cards it too intrusive.
I think we should just have a fake progress bar just below filter. We can add cards, but then maybe let's lose animation to make them less prominent.

**Review by undsoft — CHANGES_REQUESTED** [review]
Also this PR seems to show every app in every category at least on our m40.

**Comment by denysbutenko** [comment]
> Also this PR seems to show every app in every category at least on our m40.

Oops. There were two different `apps` - one coming from the template and the second variable from observable. Fixed 👍🏻 

Also, put back animation for app card placeholders. So, it has a blue line and animated placeholders now.

**Review by undsoft — APPROVED** [review]
There's something about loading animation that doesn't sit right with me, but I'm not sure I can pinpoint it.
We can merge and iterate on it later, rest of the stuff is okay.

**Comment by denysbutenko** [comment]
> @denysbutenko I've been playing with animation. I've removed skeleton from header, I think it looks better this way. If you agree, we can merge.

Yep, looks good to me 👍🏻

**Pull request merged**
