### PR TITLE
Update ga.json

### PR DESCRIPTION
**Pull request by aindriu80**
Adding Irish language support

**Changes:**

Translated into Irish/Gaeilge

**Testing:**

Personally examined Irish translation

### Downstream

|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   |

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
Thank you for your contribution.

There are some issues to fix.

### Placeholders
First there are some placeholder tokens that got translated.
For example in:
```
"{version} is available!": "Tá {leagan} ar fáil!",
```
`{version}` part will be replaced with some version, e.g. `12.0 is available`, so `{version}` keyword needs to stay as is:

```
"{version} is available!": "Tá {version} ar fáil!",
```

### Plural rules
In here:
```
"({n, plural, =1 {# widget} other {# widgets}})": "({ n, iolra, = 1 {# ghiuirléid} eile {# ghiuirléid}})",
```
`plural` and `other` are tokens. The message needs to be adjusted based on how plurality works in Irish.
If it works in the same way as in English (one word for single and another for many), it can be:

```
"({n, plural, =1 {# widget} other {# widgets}})": "({ n, plural, = 1 {# giuirléid} other {# giuirléidí}})",
```

You can test it here http://format-message.github.io/icu-message-format-for-translators/editor.html

---
In addition to plural rules:

**Comment by aindriu80** [comment]
thanks for the heads up, I see the issues and I made those changes.

**Review by undsoft — APPROVED** [review]
Thanks, there were still some broken translations that I've either fixed or removed.
We'll update our documentation on how to work with translation files to make it easier.

Once again thank you for your contribution.

**Comment by aindriu80** [comment]
No problem, I can make corrections,

**Pull request merged**
