### PR TITLE
NAS-130644 / 25.04 / Fix subfolder path for `cloud_backup.restore`

### PR DESCRIPTION
**Pull request by denysbutenko**
**Changes:**

Fix subfolder path for cloud_backup.restore

**Testing:**

details in ticket

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
Does not work correctly for me.
1. I've backed up a file using TrueCloud.
2. When I restore backup using `Include from subfolder` it correctly restores my file.
3. If I use `Include everything`, my file is not restored.

**Comment by undsoft** [comment]
Similar issue got reported: https://ixsystems.atlassian.net/browse/NAS-130794
See if it makes sense to fix it as part of this PR.

**Comment by denysbutenko** [comment]
> Similar issue got reported: https://ixsystems.atlassian.net/browse/NAS-130794 See if it makes sense to fix it as part of this PR.

It looks like a path-related issue. I prefer to isolate the changes, and I'll take a look at them afterward.

**Comment by denysbutenko** [comment]
@undsoft you can use http://10.220.38.184/ for testing

**Review by undsoft — CHANGES_REQUESTED** [review]
Now I have the opposite of the previous problem. I still cannot restore my files. If I select `Include from subfolder` and select settings resulting in this configuration:
```
[
  1,
  "bffcd05cbb5c6317b72dbd26496db5a87314a22c390f51fbf677d17662d27ff2",
  "/mnt/dozer",
  "/mnt/dozer/b",
  {
    "include": [
      "/mnt/dozer/a"
    ]
  }
]
```

**Comment by denysbutenko** [comment]
> Now I have the opposite of the previous problem. I still cannot restore my files. If I select `Include from subfolder` and select settings resulting in this configuration, no files get restored.
> 
> ```
> [
>   1,
>   "bffcd05cbb5c6317b72dbd26496db5a87314a22c390f51fbf677d17662d27ff2",
>   "/mnt/dozer",
>   "/mnt/dozer/b",
>   {
>     "include": [
>       "/mnt/dozer/a"
>     ]
>   }
> ]
> ```

`Include from subfolder` wasn't touched in this PR - it will be fixed in [EE: Include Path in TrueCloud restore from Snapshot does not work properly](https://ixsystems.atlassian.net/browse/NAS-130794). 
This PR fixes `Include everything` only.

**Review by undsoft — APPROVED** [review]
Okay, then "all" part works.

**Pull request merged**
