### PR TITLE
Update cs.json

### PR DESCRIPTION
**Pull request by markrieder**

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
Hi,

Thank you for your contribution. This is impressive.
Unfortunately there has been a misunderstanding about how to make translations.
You need to keep the original text on the left and then add translation in `""` on the right.

So for example, this:
```
"1 den": "",
```

should be:
```
"1 day": "1 den",
```

There are also some syntax typos. You can spot them by going to `Files Changed` on top and scrolling down until you see dark red. It's usually a misplaced quote or something similar.

Thanks.

**Review by bvasilenko — APPROVED** [review]
LGTM

**Review by AlexKarpov98 — CHANGES_REQUESTED** [review]
Screenshot 2024-07-31 at 12 33 29

As well make sure there is ✅ green check here ⬆️ 

It's not a valid json item:

```"Bylo nastaveno "Povolit hostitele" nebo "Odmítnout hostitele": "",```

**Review by bvasilenko — APPROVED** [review]
LGTM!

**Comment by AlexKarpov98** [comment]
Seems like updated version is provided here => https://github.com/truenas/webui/pull/10478/files, where most of the syntax is fixed.
Misunderstanding about how to make translations - were fixed there.

So I close this PR and gonna work on https://github.com/truenas/webui/pull/10478/files to finally merge these great `CS` translations!

(TN ticket - https://ixsystems.atlassian.net/browse/NAS-131133)

**Pull request closed without merging**
