### PR TITLE
NAS-118209 / 22.12 / Add hold option for snapshots

### PR DESCRIPTION
**Pull request by bvasilenko**
**Testing**

See ticket for details

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Checkbox placement is not as recommended in the ticket comments.

**Comment by bvasilenko** [comment]
@RehanY147 

Now the option is located properly:

image

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Both times, checking and unchecking, `zfs.snapshot.hold` is called. Instead of calling `zfs.snapshot.release` when unchecked.

**Comment by bvasilenko** [comment]
> Both times, checking and unchecking, `zfs.snapshot.hold` is called. Instead of calling `zfs.snapshot.release` when unchecked.

@RehanY147 Would you please double check the latest version of the code?  For me `zfs.snapshot.release` gets called when unchecked, as expected.

https://user-images.githubusercontent.com/20611516/192830533-b5ba1aaa-9b22-4fa2-8d1b-974679f4934b.mp4

**Review by RehanY147 — APPROVED** [review]
Looks good

**Pull request merged**
