### PR TITLE
NAS-112683 / 12.0 / Update R20 rear chassis image (io plate)

### PR DESCRIPTION
**Pull request by dszidi**
The image for the rear of the R20 chassis needed to be updated to show the correct IO plate.
This is a purely cosmetic change.

Please refer to JIRA ticket linked below to see what the new UI plate looks like.

https://jira.ixsystems.com/browse/NAS-112683

### CODE REVIEW

**Comment by dszidi** [comment]
The new IO plate is only for rev B models. This branch currently applies the image to all R20 models.

**Review by undsoft — CHANGES_REQUESTED** [review]
rev B only

**Review by undsoft — APPROVED** [review]
Looks good.

1. Do you need to update `createExtractedEnclosure` method?
2. Forwardport?

**Comment by dszidi** [comment]
> Looks good.
> 
> 1. Do you need to update `createExtractedEnclosure` method?
> 2. Forwardport?

1. Extracted enclosure never displays rear of chassis so we can leave it as is
2. I was going to update the branch and reopen the existing PR at https://github.com/truenas/webui/pull/6107

**Pull request merged**
