### PR TITLE
NAS-111774 / 12.0 / Built-in group Dispaly Note is randomely showing when editing users in CORE

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Review by undsoft — APPROVED** [review]
The same code also exists on group-list page.

**Comment by AlexKarpov98** [comment]
> The same code also exists on group-list page.

But this isn't included in the ticket, still do we need it?

**Comment by undsoft** [comment]
Yes, it basically the same issue.

**Review by undsoft — APPROVED** [review]
👍🏻

**Pull request merged**
