### PR TITLE
NAS-111393 / 12.0 / Only show icons based on status instead of health

### PR DESCRIPTION
**Pull request by dszidi**

### CODE REVIEW

**Comment by denysbutenko** [comment]
@dszidi, the code looks good. What is the way to reproduce this scenario?

**Comment by dszidi** [comment]
@denysbutenko Unfortunately forcing specific zpool status scenarios in ZFS is not straight forward. 
Simplest way to test is to inject the status string via ngOnChanges in the widgetpool.component.ts. 
Master branch has an enum with all the possible cases

https://github.com/truenas/webui/blob/master/src/app/enums/pool-status.enum.ts

**Comment by denysbutenko** [comment]
image
it is not clear what the pool status icon means. also, it has some offset from others

**Comment by denysbutenko** [comment]
> image
> it is not clear what the pool status icon means. also, it has some offset from others

My bad. I assigned the wrong variable above.

image
image
image
image

**Comment by dszidi** [comment]
Looks like I need to hard code the error case in the html. The yellow close icon the existing poolHealth.level value generates should really be red.

**Review by denysbutenko — APPROVED** [review]
image

image


Looks good!

**Pull request merged**
