### PR TITLE
NAS-127951 / 24.10 / Fix apps network usage

### PR DESCRIPTION
**Pull request by denysbutenko**
image

### CODE REVIEW

**Review by bvasilenko — APPROVED** [review]
Looks good to me

**Review by undsoft — CHANGES_REQUESTED** [review]
Doesn't look like it's really "all" according to last Rehan's comment.

**Comment by denysbutenko** [comment]
> Doesn't look like it's really "all" according to last Rehan's comment.

@undsoft does it mean UI changes are not needed due to middleware changes because data becomes bytes per second rather than in/out summary?

**Comment by denysbutenko** [comment]
Middleware has changes to provide data `bytes per second`, no need to change UI.

**Pull request closed without merging**
