### PR TITLE
NAS-122751 / 23.10 / Fix device form

### PR DESCRIPTION
**Pull request by bvasilenko**
**Testing**

On **Virtualization** page,
1.  **Password** field should be added to VM creation wizard
1. **Display Type** dropdown should be removed, and type parameter should be locked to a single available choice (SPICE)
1. it should be possible to apply same changes to the **Password** and **Display Type** fields at the **Add Device** form, which is located at **(Choose a VM) -> Devices > Add > Type: Display**
1. mentions of "VNC" should be removed

### CODE REVIEW

**Review by denysbutenko — CHANGES_REQUESTED** [review]
`Unable to find image 'ixsystems/truenas-webui:8460'`

Needs to resolve the merge conflict to proceed.

**Comment by bvasilenko** [comment]
@denysbutenko ok, conflicts resolved, so it should be ready for review

**Review by denysbutenko — APPROVED** [review]
image

Looks good.

**Comment by undsoft** [comment]
backport

**Comment by undsoft** [comment]
backport

**Comment by undsoft** [comment]
Actually, backport is not necessary, as `master` corresponded to 23.10 in July when this PR was merged.

**Pull request merged**
