### PR TITLE
NAS-132636 / 25.04 / Upgrade to Angular 19

### PR DESCRIPTION
**Pull request by bvasilenko**
**Testing:**

Browse across the WebUI and ensure that it's not broken

### CODE REVIEW

**Review by AlexKarpov98 — COMMENTED** [review]
@bvasilenko  - please fix these issues first 

Screenshot 2024-11-27 at 23 49 56

**Review by AlexKarpov98 — COMMENTED** [review]
Watch mode started.
Screenshot 2024-12-02 at 22 55 59

But there are some problems

1. A lot of warnings in a terminal console

https://github.com/user-attachments/assets/b3ad8634-d302-43f5-99ab-1bfd67f979f5

2. Icons are jumping / Huge (see TrueNAS logo)

https://github.com/user-attachments/assets/f7fd94ee-e304-490c-8bbd-1bd285a05719

3. Icons or something is jumping on other pages as well

https://github.com/user-attachments/assets/e0b95860-7317-4450-8c24-5a274c72140c

**Comment by aervin** [comment]
I came here to see if you guys were also experiencing the CSS parsing issue during test runs. I debugged the `jsdom` routine and it's failing to parse valid CSS. I'm considering this a termporary `jsdom` issue, so we silenced the error on our project. If you find a better solution I'd be grateful to learn about it.

https://github.com/iXsystems/TrueNAS-Cloud-UI/pull/259

**Comment by undsoft** [comment]
@aervin Yeah, we had the same issue some time ago:
https://github.com/truenas/webui/blob/master/src/app/core/testing/utils/suppress-jsdom-css-errors.utils.ts

**Comment by bvasilenko** [comment]
@AlexKarpov98 everything's ready for review, except the drag & drop on the dashboard. This is to be resolved in another extra PR

**Comment by AlexKarpov98** [comment]
`except the drag & drop on the dashboard. This is to be resolved in another extra PR`

@bvasilenko - can you link the ticket here please (for drag&drop)?

**Review by AlexKarpov98 — APPROVED** [review]
Issues are fixed now, thanks, really good job 👍

**Comment by undsoft** [comment]
Drag and drop may not be an problem because of changes here https://github.com/truenas/webui/pull/11176

**Pull request merged**
