### PR TITLE
[master] Add AlertService

### PR DESCRIPTION
**Pull request by zorglube**
`Backport` on master of this [PR](https://github.com/truenas/webui/pull/6534), also this PR is related to [this one](https://github.com/truenas/middleware/pull/8070) into the Middleware.

### CODE REVIEW

**Comment by bvasilenko** [comment]
@zorglube  
Would you please provide some more details? 
- Could you please describe the steps necessary for testing? 
- Also would be great to know about the way to obtain API credentials for https://mobile.free.fr/

**Comment by zorglube** [comment]
Hello @bvasilenko  

The idea is to provide a way to use the SMS Api of [Free](http://mobile.free.fr) so TrueNAS is abble to sent alertes through SMS. 

> * Could you please describe the steps necessary for testing? 

In order to test, you should 

> * Also would be great to know about the way to obtain API credentials for https://mobile.free.fr/

**Comment by zorglube** [comment]
Hello @bvasilenko 

**This** PR and [this one](https://github.com/truenas/webui/pull/6534) are ready for review.

**Comment by undsoft** [comment]
This PR has been stale for a while and it doesn't look like middleware wants to accept these changes. If they do accept changes, feel free to reopen this PR. In meantime I would have to close it.

**Comment by zorglube** [comment]
> 



> This PR has been stale for a while and it doesn't look like middleware wants to accept these changes. If they do accept changes, feel free to reopen this PR. In meantime I would have to close it.

Yes you're right.

**Pull request closed without merging**
