### PR TITLE
NAS-130719 / 25.04 / UI Global Search passes "undefined" url path to Docs Hub

### PR DESCRIPTION
**Pull request by AlexKarpov98**
**Testing:** see ticket.
If no version found - we redirect user to global docs, not version specific.

### CODE REVIEW

**Review by undsoft — COMMENTED** [review]
I'm curious, what kind of string would result in no version?

**Comment by AlexKarpov98** [comment]
> I'm curious, what kind of string would result in no version?

@undsoft - I'll ask Timothy Moore II about that `systemInfo.version`

**Comment by AlexKarpov98** [comment]
@undsoft  - it was `24.10-BETA.1-INTERNAL.7` probably `extractVersion` is not working correctly.

**Review by undsoft — APPROVED** [review]
Looks good. Let's extract `extractVersion` to utils and add tests to it.

**Review by bvasilenko — APPROVED** [review]
Works good!

**Comment by AlexKarpov98** [comment]
backport

**Pull request merged**
