### PR TITLE
NAS-119793 / 23.10 / Sidebar menu closes if I hit ESC button

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Menu should be closed only by clicking the hamburger menu.

### CODE REVIEW

**Review by denysbutenko — CHANGES_REQUESTED** [review]
I agree that we need to handle hitting `Esc` on the sidebar menu, and we probably need to keep the possibility to close the menu by clicking on the backdrop. @undsoft, what do you think about it?

**Comment by AlexKarpov98** [comment]
> I agree that we need to handle hitting `Esc` on the sidebar menu, and we probably need to keep the possibility to close the menu by clicking on the backdrop. @undsoft, what do you think about it?

I need to check that functionality, I forgot that we also have backdrop.
It was easy quick solution :D

**Comment by undsoft** [comment]
I'd rather keep closing via Esc if no easy solution exists. It's not a big issue.

**Comment by AlexKarpov98** [comment]
Solution:
Disable `Esc` close only if `sidenavMode !== 'over'` so then we see this and `Esc` is needed.

Screenshot 2023-01-11 at 23 39 23

**Review by denysbutenko — APPROVED** [review]
Works well 👍🏻

**Pull request merged**
