### PR TITLE
NAS-127483 / 24.10 / Removed redundancy check for Dedup and Special vdevs with Data vdevs

### PR DESCRIPTION
**Pull request by RehanY147**

### CODE REVIEW

**Review by AlexKarpov98 — COMMENTED** [review]
@RehanY147 @undsoft - do we need to fully remove `RedundancyMismatch` check?

**Comment by RehanY147** [comment]
Adding a quote from Caleb here for his opinion on the matter since its relevant

> Any type of business logic related to "warning" a user on vdevs should be removed
> Before this type of logic gets put into the UI, the UI team needs to consult with the OS team to make sure it makes sense

**Comment by RehanY147** [comment]
@AlexKarpov98 We can merge this PR. If more changes are required we can do it later.

**Review by AlexKarpov98 — APPROVED** [review]
@RehanY147 said we can merge this one, even though we removed `RedundancyMismatch` check.

**Pull request merged**
