### PR TITLE
NAS-120410 / 23.10 / Styles for scrollbar

### PR DESCRIPTION
**Pull request by Raz-Dva**
Test the scrollbar on different themes and browsers.

### CODE REVIEW

**Comment by denysbutenko** [comment]
Here's a preview of how it looks and behaves on macOS 13.

|browser|preview|
|-------|-------|
|chrome|https://user-images.githubusercontent.com/351613/223033715-313c7b92-a63f-432f-9a0f-80fdf28baf89.mp4|
|safari|https://user-images.githubusercontent.com/351613/223034012-937455bd-6353-4e2b-b035-e4cf5d07dd68.mp4|
|firefox|https://user-images.githubusercontent.com/351613/223034206-8d47f9ce-9e68-4448-a2f3-a4ce22a3bc01.mp4|
|opera|https://user-images.githubusercontent.com/351613/223034280-18da1604-008c-4d5e-b006-28f5007cc752.mp4|


the scroll bar looks different in firefox and other browsers.
I notice a delay between scrolling and updating the scroll bar on chrome. It may be an issue on my end.

**Comment by Raz-Dva** [comment]
In Firefox on Mac, it is only possible to change the color of the scrollbar.

Screenshot 2023-03-08 at 06 49 07

**Comment by denysbutenko** [comment]
Different theme preview:

|ix-dark|ix-blue|dracula|nord|
|-------|-------|-------|----|
|image|image|image|image|

The visibility of the scroll is broken when `auto` mode is activated in macOS. If the content has scrolling - it is always visible. Let me show what I meant.

|before|after|
|---|---|
|Kapture 2023-03-09 at 15 19 00|Kapture 2023-03-09 at 15 32 05|

**Comment by denysbutenko** [comment]
|chrome|safari|firefox|
|---|---|---|
|image|image|image|

**Review by denysbutenko — CHANGES_REQUESTED** [review]
|actual|expected|
|-|-|
|image|image|


The scrollbar does not meet expectations.

**Comment by denysbutenko** [comment]
|chrome-dark|chrome-light|safari-dark|safari-light|
|-|-|-|-|
|image|image|image|image|

The scrollbar does not disappear in Chrome and Safari when macOS have the `Show scroll bars: When scrolling`. Firefox works well. As we discussed, that is an expected trade-off for consistent appearance. So we are good to go with this.

**Review by denysbutenko — APPROVED** [review]

**Pull request merged**
