### PR TITLE
NAS-112190 / 21.10 / NAS-112190: Fixed required assignment

### PR DESCRIPTION
**Pull request by RehanY147**
NAS-112190

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
SAN is still required.
Снимок экрана 2021-09-10 в 14 41 34

**Comment by RehanY147** [comment]
> 
> 
> Now there is a middleware validation error that SAN is required. Check with someone from middleware to see if it actually should be required.

Trying to get in touch with someone from middleware regarding this.

**Comment by RehanY147** [comment]
Waiting for Waqar to get back from his vacation

**Comment by RehanY147** [comment]
Waqar will be taking the ticket as further investigation is required to nail down the issue and a proposed solution. Closing this PR for now.

**Pull request closed without merging**
