### PR TITLE
NAS-117634 / 22.12 / Refactor bootenv-status.component

### PR DESCRIPTION
**Pull request by denysbutenko**
You can access this component by going to: System Settings → Boot → Actions → Boot Pool Status.

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
The buttons need a bit of adjustment. And the Active column is empty. We should show some text there to explain.

image

**Comment by denysbutenko** [comment]
> The buttons need a bit of adjustment. And the Active column is empty. We should show some text there to explain.
> 
> image

Good catch. I will fix it in the next PR #7000

**Comment by denysbutenko** [comment]
The latest docker image includes the changes for `bootenv-list.component` from #7000

**Review by RehanY147 — APPROVED** [review]
Looks good.

**Pull request merged**
