### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by MDVAurelien**
Add some French translations

**Changes:**

**Testing:**

### Downstream

|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   |

### CODE REVIEW

**Review by undsoft — APPROVED** [review]
Thanks 👍🏼

**Comment by MDVAurelien** [comment]
FIX

**Comment by undsoft** [comment]
There are still conflicts.

**Comment by MDVAurelien** [comment]
Strange, it's not very clear in the report. I'll close the PR and redo.

**Comment by MDVAurelien** [comment]
I'll redo

**Pull request closed without merging**
