### PR TITLE
NAS-110739 / 12.0 / Don't try to upload an iso file for a vm if one hasn't been selected

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
1. I would imagine that updating a root component like this will make all file inputs in all forms that use form-upload required. I don't think this is always the case.
It should probably be based on a 'required' field in config.
Ideally it would show an inline validation message similar to how other inputs work, but this can be skipped if it's too hard.

2. Also, please update the message to "Please make sure to select a file".

**Comment by AlexKarpov98** [comment]
> 1. I would imagine that updating a root component like this will make all file inputs in all forms that use form-upload required. I don't think this is always the case.
>    It should probably be based on a 'required' field in config.
>    Ideally it would show an inline validation message similar to how other inputs work, but this can be skipped if it's too hard.
> 2. Also, please update the message to "Please make sure to select a file".

Regarding 1st opinion, I don't think it's the right way. I think that workflow is for submitting scope, but we are currently talking about only an uploading section. You know the terms of `required` stand for submit, nothing else. We are talking about the workflow of the upload button itself. Why do we need to follow upload processing even though there is no file selected? I am sure you confused something. Can you please consider this once again? Thank you.

**Review by undsoft — APPROVED** [review]
You are right. I made an incorrect assumption about how this form control works.
Thanks.
Do you think we need to port this to master?

**Comment by AlexKarpov98** [comment]
@undsoft Yeah, I think we need to port this to master.

**Comment by undsoft** [comment]
backport

**Comment by undsoft** [comment]
backport

**Pull request merged**
