### PR TITLE
NAS-124134 / 24.04 / Refactor Start And Enable Dialog for Services

### PR DESCRIPTION
**Pull request by denysbutenko**
## Changes

- Use global store as a single source of truth for services state.
- `StartServiceDialog` appears when the service is stopped.
- Update shares dashboard to consume service from the store.
- Open service form on the Shares dashboard directly.
- `Enable this service to start automatically` is set to true by default.
- Move `StartServiceDialogComponent` to `common/dialog` directory and `AppCommonModule`

### SMB Service

Case 1:
- given SMB service is `Stopped` and `disabled` (auto-start)
- create SMB share with non-ACL path.
- ensure the `Start SMB Service` dialog **do appear**
- ensure the `Restart SMB Service` dialog **do not appear**
- ensure the `Configure ACL` dialog **do not appear**

Case 2:
- given SMB service is `Running` and `disabled` (auto-start)
- create SMB share with non-ACL path.
- ensure the `Restart SMB Service` dialog **do appear**
- ensure the `Configure ACL` dialog **do not appear**
- ensure the `Start SMB Service` dialog **do not appear**

Case 3:
- given SMB service is `Running` and `enabled` (auto-start)
- create SMB share with non-ACL path.
- ensure the `Restart SMB Service` dialog **do appear**
- ensure the `Configure ACL` dialog **do not appear**
- ensure the `Start SMB Service` dialog **do not appear**

Case 4:
- given SMB service is `Stopped` and `disabled`
- create SMB share with ACL path.
- ensure the `Restart SMB Service` dialog **do not appear**
- ensure the `Configure ACL` dialog **do appears**
- when press 'No' ensure the `Start SMB Service` dialog **do appear**
- when press 'Configure' gets redirected and ensure the `Start SMB Service` dialog **do appear**

Case 5:
- given SMB service is `Running` and `disabled`
- create SMB share with ACL path.
- ensure the `Restart SMB Service` dialog **do appear**
- ensure the `Configure ACL` dialog **do appear**
- when press the `Cancel` button – ensure the `Start SMB Service` dialog **do not appear**
- when press the `Configure` button gets redirected and ensure the `Start SMB Service` dialog **do not appears**

Case 6:
- given SMB service is `Running` and `enabled`
- create SMB share with ACL path.
- ensure the `Restart SMB Service` dialog **do appear**
- ensure the `Configure ACL` dialog **do appear**
- when press 'No' – ensure the `Start SMB Service` dialog **do not appear**
- when press 'Configure' gets redirected and ensure the `Start SMB Service` **do not appear**

### NFS Service

Case 1:
- given NFS service is `Stopped` and `disabled` (auto-start)
- create NFS share
- ensure the `Start SMB Service` dialog **do appear**

Case 2:
- given NFS service is `Running` and `disabled` (auto-start)
- create NFS share
- ensure the `Start SMB Service` dialog **do not appear**

Case 3:
- given NFS service is `Running` and `enabled` (auto-start)
- create NFS share
- ensure the `Start SMB Service` dialog **do not appear**

### iSCSI Service

Case 1:
- given iSCSI service is `Stopped` and `disabled` (auto-start)
- create iSCSI share
- ensure the `Start iSCSI Service` dialog **do appear**

Case 2:
- given iSCSI service is `Running` and `disabled` (auto-start)
- create iSCSI share
- ensure the `Start iSCSI Service` dialog **do not appear**

Case 3:
- given iSCSI service is `Running` and `enabled` (auto-start)
- create iSCSI share
- ensure the `Start iSCSI Service` dialog **do not appear**
- ensure the `Warning about active sessions` dialog **do appear**

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
For SMB Service, when I click "Start" nothing happens and then suddenly the dialog closes. Either the loading state is missing or it doesn't work as intended.
The first test scenario doesn't work properly. 
If I chose to enable the service with the toggle button on the dialog, the service is not enabled to automatically start on the services page. Also, if I do the same test twice, with the smb service disabled both times, the dialog doesn't appear the second time around.

**Comment by denysbutenko** [comment]
Testing scenarios are updated.

> For SMB Service, when I click "Start" nothing happens and then suddenly the dialog closes. Either the loading state is missing or it doesn't work as intended. The first test scenario doesn't work properly.

Notification toast should appears. Added loading state for requests to be more intuitive. @RehanY147, please provide details on how to reproduce the issue when it does not work as intended for you.

> If I chose to enable the service with the toggle button on the dialog, the service is not enabled to automatically start on the services page. 

I can't repeat this. Needs steps on how to reproduce it.

> Also, if I do the same test twice, with the smb service disabled both times, the dialog doesn't appear the second time around.

I agree there is a space for improvements and this is by design to be less annoying with dialogs at this point. It checks if service id matches previous id then do not show `Start/Enable` dialog twice. The dialog will appear if you try to create another service share.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Steps to reproduce
1. SMB service is disabled and stopped
2. Create an NON ACL smb share
3. Dialog to start and enable SMB service shows up
4. Go to the services page and stop and disable smb service again
5. Go back to shares dashboard and repeat the process

Expected result: The dialog to start service shows up
Actual Result: Nothing happens and the share is created

**Comment by denysbutenko** [comment]
> Steps to reproduce
> 
> 1. SMB service is disabled and stopped
> 2. Create an NON ACL smb share
> 3. Dialog to start and enable SMB service shows up
> 4. Go to the services page and stop and disable smb service again
> 5. Go back to shares dashboard and repeat the process
> 
> Expected result: The dialog to start service shows up Actual Result: Nothing happens and the share is created

I appreciate your detailed feedback. I've addressed the issue, and it's fixed now.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Case 2 is failing. The enable smb service dialog shows up after the restart dialog
Also, why do we have an enable button and a toggle button on the Enable dialog? Are there two operations being performed here? I thought enabling the SMB service meant enabling it to start automatically.
image

**Review by RehanY147 — CHANGES_REQUESTED** [review]
For SMB case 5, I get the "Enable Dialog" both times and don't get the start smb service dialog as mentioned.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
NFS Service case 2 fails after trying case 1 and case 3

**Review by RehanY147 — CHANGES_REQUESTED** [review]
ISCSI case 2 fails. UI gets stuck at the loading indicator

**Review by RehanY147 — CHANGES_REQUESTED** [review]
ISCSI case 3 fails the same way as case 2

**Comment by denysbutenko** [comment]
> Case 2 is failing. The enable smb service dialog shows up after the restart dialog
 Also, why do we have an enable button and a toggle button on the Enable dialog? Are there two operations being performed here? I thought enabling the SMB service meant enabling it to start automatically. image

**Comment by denysbutenko** [comment]
@RehanY147 

> Case 2 is failing. The enable smb service dialog shows up after the restart dialog 

That's not good tbh. Mixing start and enable dialogs is confusing. I'll take a look.

> Also, why do we have an enable button and a toggle button on the Enable dialog? 

I assumed it was a good idea to show that dialog just to enable the service to start automatically when it was running. Actually, it's not.

> Are there two operations being performed here? 

Yes, the first operation starts the service, and the second is to enable it to start automatically.

> I thought enabling the SMB service meant enabling it to start automatically. 

That's correct.

**Comment by denysbutenko** [comment]
> For SMB case 5, I get the "Enable Dialog" both times and don't get the start smb service dialog as mentioned.
> NFS Service case 2 fails after trying case 1 and case 3
> ISCSI case 2 fails. UI gets stuck at the loading indicator
> ISCSI case 3 fails the same way as case 2

@RehanY147, those issues have been addressed, and testing scenarios are updated.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Case 1 fails. I'm getting the Configure ACL dialog every time

**Comment by denysbutenko** [comment]
> Case 1 fails. I'm getting the Configure ACL dialog every time

Is it with a non-ACL path? the Configure ACL dialog appears before the Start Service dialog. I'll double-check it.

**Comment by RehanY147** [comment]
@denysbutenko Yes. I created a new pool. And tried to add a share on the pool and it was successful. But then I created a simple dataset under the pool and tried creating a share on the new dataset and that failed.

**Comment by denysbutenko** [comment]
> @denysbutenko Yes. I created a new pool. And tried to add a share on the pool and it was successful. But then I created a simple dataset under the pool and tried creating a share on the new dataset and that failed the case 1

@RehanY147 OK, I see that behavior. A quick overview shows that the ACL is true in the default share preset. It activates the ACL checkbox in the form. The ACL checkbox is disabled, and the payload ignores this value. After share is created, the `filesystem.stat` checks the share path and compares ACL value from response with ACL value in the form. If they don't match, the Configure ACL dialog appears. This also can be reproduced in master branch. So it looks like unrelated to this PR. Would you mind creating a new ticket for the discovered bug?

**Comment by denysbutenko** [comment]
> Case 1 fails. I'm getting the Configure ACL dialog every time

@RehanY147 Taking into account the discovered bug/changes. It is going through Case 4.

**Comment by RehanY147** [comment]
@denysbutenko I have 3 pools
1. pool > ds (no acl)
2. posix > ds (posix acl)
3. nfs > ds (nfs acl)

When I go to test case 1 on pool > ds it shows me the dialog to configure ACL. That's why I say that case 1 fails.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
^

**Comment by RehanY147** [comment]
Case 2 and 3 are failing similarly

**Comment by RehanY147** [comment]
@denysbutenko 
SMB Service
- Case 1 ❌ 
- Case 2 ❌ 
- Case 3 ❌ 
- Case 4 ✅ 
- Case 5 ✅ 
- Case 6 ✅ 
NFS Service
- Case 1 ✅ 
- Case 2 ✅ 
- Case 3 ✅ 
iSCSI Service
- Case 1 ✅ 
- Case 2 ✅ 
- Case 3 ✅

**Review by RehanY147 — APPROVED** [review]

**Comment by denysbutenko** [comment]
@RehanY147 just a reminder to create a ticket for the discovered bug.

**Comment by denysbutenko** [comment]
linked ticket: https://ixsystems.atlassian.net/browse/NAS-125283

**Pull request merged**
