### PR TITLE
NAS-127441 / 24.10 / Refactor SnapshotList to use ix-table2

### PR DESCRIPTION
**Pull request by denysbutenko**
Check `/datasets/snapshots` for regressions.

### CODE REVIEW

**Comment by AlexKarpov98** [comment]
@denysbutenko - single selection is not working as expected.
https://github.com/truenas/webui/assets/22980553/4a927a37-bf39-4bcc-a6f6-2665c180cdde

**Comment by AlexKarpov98** [comment]
@denysbutenko 

Hold checkbox is not changing to correct state on error.
And maybe we can add some loader to see when it's updating, but main idea is that it should always show correct state.

https://github.com/truenas/webui/assets/22980553/eb25525b-d49a-4c3f-91fe-696447556c24

**Review by AlexKarpov98 — CHANGES_REQUESTED** [review]
Looks good overall. Please check my attached videos.

**Comment by AlexKarpov98** [comment]
Screenshot 2024-03-07 at 10 07 33
@denysbutenko - as well please check tests

**Comment by denysbutenko** [comment]
@AlexKarpov98 thanks, fixed

**Review by AlexKarpov98 — APPROVED** [review]
Works beautifully, good job 👍 

1 issue noticed tho:
When I BATCH select ALL items, they are all selected, not only the ones which are currently on the page

see images:
Screenshot 2024-03-07 at 14 44 12
Screenshot 2024-03-07 at 14 44 30

**Comment by denysbutenko** [comment]
> Works beautifully, good job 👍
> 
> 1 issue noticed tho: When I BATCH select ALL items, they are all selected, not only the ones which are currently on the page
> 
> see images: Screenshot 2024-03-07 at 14 44 12 Screenshot 2024-03-07 at 14 44 30

Huh, I'm curious if that works. I'll keep it as is since the "select all" implementation was adapted from another page. I created a [ticket](https://ixsystems.atlassian.net/browse/NAS-127632) for checkbox column improvements and added TODO to improve it when the ticket is done.

**Pull request merged**
