### PR TITLE
NAS-122208 / 23.10 / Submitting in pool creation

### PR DESCRIPTION
**Pull request by undsoft**
Testing: submit in new pool creation wizard.

Some steps will be implemented in other PRs.

### CODE REVIEW

**Comment by undsoft** [comment]
Note. With latest master changes it may be impossible to press Save button on Data step for some reason.
You can workaround it by clicking on Review step header.

**Comment by AlexKarpov98** [comment]
@undsoft - Enclosure options are missing
I think this is the problem

image

**Comment by undsoft** [comment]
Will check in future PRs.

**Comment by AlexKarpov98** [comment]
@undsoft - I've fixed it in new PR:
https://github.com/truenas/webui/pull/8285

**Pull request merged**
