### PR TITLE
NAS-125092 / 24.04 / Add support for webui logs in feedback form

### PR DESCRIPTION
**Pull request by bvasilenko**
**Testing**

For testing steps, please see ticket

Use mocks for `"debug_extra": {"ui/info.txt": "Test info"}` payload property of the **support.new_ticket** API endpoint

### CODE REVIEW

**Comment by bvasilenko** [comment]
blocked by https://github.com/truenas/ixdiagnose/pull/129

**Comment by RehanY147** [comment]
Waiting for attached ticket to unblock

**Review by RehanY147 — COMMENTED** [review]
Please re-request the review when the attached PR is merged.

**Comment by undsoft** [comment]
Middleware decided against adding support for uploading logs in debug api for security reason. Unfortunately this would have to be solved in a different way.

**Pull request closed without merging**
