### PR TITLE
NAS-120289 / 22.12.2 / Adding min_memory field to VMs

### PR DESCRIPTION
**Pull request by undsoft**
Testing: observe new Minimum Memory field when creating or editing a VM.

### CODE REVIEW

**Comment by m9x3mos** [comment]
Thanks for the quick updates on this. 
I commented on the Jira ticket as well

Is there anyway this can be done via CLI until the release in March is out?

**Review by AlexKarpov98 — APPROVED** [review]
backport 👍

**Comment by undsoft** [comment]
@AlexKarpov98 Not really a backport :)

**Review by AlexKarpov98 — APPROVED** [review]
Got confused, sorry 😃 
Looks good to me!

**Pull request merged**
