### PR TITLE
NAS-123460 / 24.04 / Show App Version and Chart Version on two lines

### PR DESCRIPTION
**Pull request by denysbutenko**
image

### CODE REVIEW

**Review by AlexKarpov98 — COMMENTED** [review]
Looks fine.

**Comment by denysbutenko** [comment]
@AlexKarpov98 this PR still needs your approval

**Review by AlexKarpov98 — APPROVED** [review]
👍

**Comment by denysbutenko** [comment]
backport

**Comment by denysbutenko** [comment]
backport

**Pull request merged**
