### PR TITLE
NAS-113836 / 22.02 / Padding issue on Certificates page on SCALE

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Comment by RehanY147** [comment]
Need help reproducing the original bug. I don't see the padding issue on master.

**Review by RehanY147 — COMMENTED** [review]
Need help reproducing the original bug. I don't see the padding issue on master.

**Comment by AlexKarpov98** [comment]
> Need help reproducing the original bug. I don't see the padding issue on master.

reproduce

**Comment by AlexKarpov98** [comment]
Before:
image

After:
image

**Review by RehanY147 — APPROVED** [review]
Looks good

**Pull request merged**
