### PR TITLE
NAS-114911 / 22.12 / Add a new option in network bridge sidebar

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing:

Network -> Interfaces ->  Add Bridge Interface

Added STP option as checkbox.

image

### CODE REVIEW

**Review by bvasilenko — COMMENTED** [review]
I noticed that validation message is not clear enough. Can we override the text to make it more clear to the user?

image

**Comment by bvasilenko** [comment]
I've also noticed that it's impossible to save changes while the STP checkbox unchecked.

**Comment by bvasilenko** [comment]
And last thing I discovered, is that the parameters  of `interface.create` query is being sent without `stp` field being populated at all (no `true` nor `false` )

**Comment by AlexKarpov98** [comment]
> I noticed that validation message is not clear enough. Can we override the text to make it more clear to the user?
> 
> image

Please confirm testing is on the version 22.12 with update https://jira.ixsystems.com/browse/NAS-113826 (added a new option STP). - there isn't validation message such.

**Comment by AlexKarpov98** [comment]
> And last thing I discovered, is that the parameters of `interface.create` query is being sent without `stp` field being populated at all (no `true` nor `false` ) . Not sure if that's by design or not.

`stp: false` would be added to payload in the only case Interface type is Bridge and unchecked STP.
Screenshot_27

**Comment by AlexKarpov98** [comment]
> I've also noticed that it's impossible to save changes while the STP checkbox unchecked. Not sure if that's by design or not.

Waiting for reply from backend developer
image

**Comment by undsoft** [comment]
Let's try to do something with this PR. If backend issue still persists, please create a backend ticket and link to our ticket.

**Comment by AlexKarpov98** [comment]
Tested with the latest vm (TrueNAS-SCALE-22.12-MASTER-20220330-015452.iso)
It works to update `stp` option.

**Review by bvasilenko — APPROVED** [review]
Looks good and works for me.
Tested that UI sends proper value of `stp` to the back-end.

**Pull request merged**
