### PR TITLE
NAS-121730 / 22.12.3 / Replication tasks cannot be changed after creation, persists in 22.12.2

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Review by dszidi — COMMENTED** [review]
This does resolve the reported issue. I can edit the replication task and changes are stored without tracebacks. However, there now seems to be a regression where I'm unable to save a new replication task if I have the schedule set to "run once"

EDIT: Disregard the regression comment. The issue seems to also exist on stable/bluefin branch

**Review by dszidi — APPROVED** [review]
LGTM

**Comment by undsoft** [comment]
Blocked - waiting to see if we get additional information from users.

**Comment by undsoft** [comment]
Deeming to be a cache (or some other) issue.

**Pull request closed without merging**
