### PR TITLE
NAS-112158 / 21.10 / NAS-112158: Fetched latest values from FormControl instead of config

### PR DESCRIPTION
**Pull request by RehanY147**
NAS-112158
Test "Apply Permissions Recursively" and "Apply permissions to child datasets" fields in ACL Editor by setting them to different pairs of values.

### CODE REVIEW

**Comment by AlexKarpov98** [comment]
@RehanY147 
ACL permission seems not saved properly. Also removing it is not working.

**Review by AlexKarpov98 — COMMENTED** [review]
@RehanY147 
ACL permission seems not saved properly under recursive applying. Also removing it is not working.

https://user-images.githubusercontent.com/22980553/133369265-e030c452-1383-4f42-b54f-d3d44a167a28.mp4

**Comment by RehanY147** [comment]
At first glance, looks like UI is sending the correct payload. This issue seems to be on the middleware side. I'll consult with someone from middleware.

**Comment by RehanY147** [comment]
@AlexKarpov98 This turned out to be a middleware issue. Please test again with the latest Scale nightly.

**Comment by AlexKarpov98** [comment]
LGTM

**Review by AlexKarpov98 — APPROVED** [review]

**Pull request merged**
