### PR TITLE
NAS-111537 / 21.10 / Allow job dialog to collapsed

### PR DESCRIPTION
**Pull request by denysbutenko**

### CODE REVIEW

**Review by undsoft — COMMENTED** [review]
I like how how it shows where it collapses and that I can bring the window back.
I would prefer a different collapse button, maybe something similar to minimize button in Windows?
Also, note that "Close" button in dialog does similar thing, I think we can basically replace "Close" with this everywhere.

**Comment by denysbutenko** [comment]
I tried to use the `minimize` icon, but it's tricky to align this icon:
image
image

We can keep it or find an alternative option

**Comment by denysbutenko** [comment]
`indeterminate_check_box`:
image

**Comment by undsoft** [comment]
Can we push it to top right and make custom styles to make it basically appears as Windows minimize icon?

**Review by undsoft — APPROVED** [review]
Very nice 👍

**Pull request merged**
