### PR TITLE
NAS-110764 / 21.08 / NAS-110764 - Trivial permissions form facelift

### PR DESCRIPTION
**Pull request by undsoft**
Improves styling and type safety of trivial (aka unix) permissions form:
https://xd.adobe.com/view/285bc415-335a-4aff-b632-3e9c6ab7e179-7d08/screen/06250a7b-765e-4bed-bc28-57ab965094df/
Also reorganizes scss files – see after all the translations.

To test open editor for basic permission and test for regressions.

### CODE REVIEW

**Comment by RehanY147** [comment]
Getting this error when clicking on `View Permissions` option for a dataset
image

**Review by RehanY147 — CHANGES_REQUESTED** [review]
The aforementioned bug

**Comment by undsoft** [comment]
It was likely a middleware issue / outdated middleware. I've updated it and the error is gone.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
If I'm on a really long Storage page and I've scrolled down to a lower pool and I click on view permissions on one of the datasets, all I see is that the pools table has shrunk but I don't see the permissions card at the top. Maybe the page should either scroll up or the card should open right next to the relevant pool.

image
image

**Comment by undsoft** [comment]
Good find, but you are testing the wrong thing. This PR is specifically about the trivial permissions.
I'll add a ticket for the issue you mentioned.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Two issues
- I can't seem to edit permissions properly. I unchecked the `Execute` permission for `other` and saved. The next time I open the edit form for the same dataset, the `Read` permission was unchecked instead of `Execute`. At other times, the permission saving doesn't even work at all.

- The `ComboBox's` don't seem to work anymore. The dropdown's work but when entering something in the input field, the search based dropdown doesn't show up anymore

**Comment by RehanY147** [comment]
trivial_permissions1

**Comment by RehanY147** [comment]
trivial_permissions2

**Comment by undsoft** [comment]
@RehanY147 Nice testing. Fixed the issues.

**Review by RehanY147 — APPROVED** [review]
Issues resolved. Works OK now.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Still getting error when trying to change the user. Is that intended behavior?

**Comment by RehanY147** [comment]
trivial_permissions3

**Comment by undsoft** [comment]
@RehanY147 Yes, you have to press "Apply User / Apply Group" to confirm changes.

**Review by RehanY147 — APPROVED** [review]
Looks good

**Pull request merged**
