### PR TITLE
Update new content in SChinese

### PR DESCRIPTION
**Pull request by AltracasysHC**
- Update new content in SChinese

And here are some question I wanna ask:
- Why some entries are not translated in the newer file, but appear and translated in the earlier version? 
  (Example:  "Enter a threshold temperature in Celsius. S.M.A.R.T. will message with a log level of LOG_CRIT and send an email if the temperature is higher than the threshold.": "输入摄氏度阈值。如果温度高于阈值，S.M.A.R.T 将以日志级别 LOG_CRIT 发出消息并发送电子邮件。", )
- I found that my recently revision was rolled back to the previous version (not including known issus). I would like to know if this is due to a mistake in the submission method or some other reason? Cause this frustrates me a bit.
- Will the translation of the project move to a platform like crowdin in the future?

Thanks.
 😍 TrueNAS

### CODE REVIEW

**Comment by denysbutenko** [comment]
Hi @AltracasysHC, I will try to answer your questions.

> * Why some entries are not translated in the newer file, but appear and translated in the earlier version?
>   (Example:  "Enter a threshold temperature in Celsius. S.M.A.R.T. will message with a log level of LOG_CRIT and send an email if the temperature is higher than the threshold.": "输入摄氏度阈值。如果温度高于阈值，S.M.A.R.T 将以日志级别 LOG_CRIT 发出消息并发送电子邮件。", )
> * I found that my recently revision was rolled back to the previous version (not including known issus). I would like to know if this is due to a mistake in the submission method or some other reason? Cause this frustrates me a bit.

It happened due to a mistake during a merge conflict, which was entirely our mistake. The translation files are the number one reason for merge conflicts. There is recovered [zh-hasn.json](https://github.com/truenas/webui/blob/d7bae786b2860f987e095aff9fe7c5be29cfa15f/src/assets/i18n/zh-hans.json) from 29th Jan. Sorry for that incident.

> * Will the translation of the project move to a platform like crowdin in the future?

I want to think so. Added [a ticket](https://github.com/truenas/webui/pull/7653/files#diff-2f0d49ff5053763a3b36cec5c48c2174a14d0c36c4683b97c7a3b58a26ae291eL1357) to backlog.

**Review by denysbutenko — CHANGES_REQUESTED** [review]
Please resolve a merge conflict before proceeding

**Comment by AltracasysHC** [comment]
Thanks for your answer @denysbutenko, now I know what is going on.

And I was manually merged some conflicts/improves contents between Jan.28 and Feb.1.
If there is still have a conflict, I will continue to modify the relevant content.

**Review by denysbutenko — APPROVED** [review]
Looks good. Thanks for the contribution.

**Pull request merged**
