### PR TITLE
NAS-124969 / 24.04 / Add Smb Status page

### PR DESCRIPTION
**Pull request by denysbutenko**
Add Smb status overview page that includes tabs to navigate between different types of SmbStatus information. Other tables will be implemented separately.

### CODE REVIEW

**Review by RehanY147 — COMMENTED** [review]
Need instructions to test this. I can't get a record to show up on that page.

**Comment by denysbutenko** [comment]
> Need instructions to test this. I can't get a record to show up on that page.

The table was implemented before and already tested.
For testing, ensure that
- SMB Status page has Sessions tab
- SMB Session table is rendered on SMB Status page
- URL is match `/sharing/smb/status/sessions`
- if go to `/sharing/smb/status` check redirect to `/sharing/smb/status/sessions`

**Review by RehanY147 — CHANGES_REQUESTED** [review]
The page looks good, however, I only see one tab on the page. Are there supposed to be more tabs there? Also, there should be a way to redirect to the new sessions page on the Shares list page that comes up when you click the Table header on the shares dashboard.

**Comment by denysbutenko** [comment]
> The page looks good, however, I only see one tab on the page. Are there supposed to be more tabs there? 

Yes, it is. There are a couple of tickets for each new view.

> Also, there should be a way to redirect to the new sessions page on the Shares list page that comes up when you click the Table header on the shares dashboard.

Make sense. Unfortunately, the full-page table uses a legacy entity table component that makes extending the page header a bit tricky. Let's add it when the table is being refactored to the ix-table2 component.

**Review by RehanY147 — APPROVED** [review]
Let's add a ticket for the refactor. Lest this detail is missed when someone else creates it./

**Pull request merged**
