### PR TITLE
NAS-115099 / 13.0 / SSH Keypairs: Creating a Private Key for a System fails

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing:
SSH Connection -> Add -> Generate SSH Key Pair

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Still getting that error
image
image

**Comment by AlexKarpov98** [comment]
Tested on latest vm. It works well.

**Review by RehanY147 — COMMENTED** [review]
@AlexKarpov98 What build did you use to test this?

**Comment by AlexKarpov98** [comment]
> @AlexKarpov98 What build did you use to test this?

Tested on TrueNAS-13.0-MASTER-202203120601-239d935.iso

**Review by RehanY147 — APPROVED** [review]
Looks good to me

**Pull request merged**
