### PR TITLE
NAS-126919 / 24.10 / On Dragonfish BETA.1  the licence agreement appears multiple times.

### PR DESCRIPTION
**Pull request by AlexKarpov98**
See ticket.

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
Only hides the problem, let's go for solutions that fix the underlying issue.

**Comment by AlexKarpov98** [comment]
> Only hides the problem, let's go for solutions that fix the underlying issue.

Problem is that filterAsync may emit multiple times, not sure if we need that behaviour, or just get first() value from the successful observable.

By adding the first() operator, asyncPredicate$ will only be considered once per each item from the source observable.

**Review by undsoft — CHANGES_REQUESTED** [review]
`filterAsync` does not emit multiple times. `hasRole` does. I would suggest checking usages for it and seeing if we can/should add `take(1)` there. 
If it's possible let's add it there and test.
If not possible, we can add `take(1)` in this effect in `hasRole` pipe.

Also note about `first`: https://stackoverflow.com/questions/42345969/take1-vs-first

**Comment by AlexKarpov98** [comment]
@undsoft - yeah, it's possible to add take(1) in the `hasRole`. Now It only emits once.

**Review by undsoft — APPROVED** [review]
Alright, that's fine too.

**Pull request merged**
