### PR TITLE
NAS-114614 / 13.0 / 2FA field doesn't show after failover until screen is refreshed

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing:

System -> 2FA -> Enable Two Factor Authentication
Re-checked Two Factor Status after failing to login in to the sync login page.

### CODE REVIEW

**Comment by AlexKarpov98** [comment]
> Tested this on same machine from the screenshots in the ticket. Once system reboots, 2fa field is still missing.

Sorry, I could not reproduce it. Could you attach the screenshot or something?
Please check again 2FA field would show up after clicking login button.
Thanks

**Comment by dszidi** [comment]
The steps I have taken based on the ticket description:

1. Go to System/Failover and press  the "Sync to Peer" button. Complete the dialog
2. Go to Dashboard and wait for sync to complete. (Dashboard's standby controller card will show "HA Disabled")
3. Once the Dashboard standby controller card shows the "Initiate Failover" button again, start the failover process

This is the form I am greeted with once the system comes back online

image

**Comment by dszidi** [comment]
Also by comparison, this is what is presented if I just refresh the page...

image

**Review by dszidi — APPROVED** [review]
Looks good!

image

**Pull request merged**
