### PR TITLE
NAS-119698 / 23.10 / Unsupported type = cron and uri when trying to Launch a docker image

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing steps:
1. Make sure you are connected to `m40g3-137.dc1.ixsystems.net`
2. Go to APPS -> Available Applications -> Search Jacket (test_list_default)
3. Click Install 
Screenshot 2023-01-18 at 15 48 24
4. At the top part of the form search for `CRON TEST` and `URI TEST`

What you will see is:
Screenshot 2023-01-19 at 10 59 26

Schema example:
```
        {
            "variable": "uri_test",
            "label": "URI TEST",
            "group": "General Settings",
            "schema": {
                "type": "uri"
            }
        },
        {
            "variable": "cron_test",
            "label": "CRON TEST",
            "group": "General Settings",
            "schema": {
                "type": "cron",
                "default": {
                    "hour": "*",
                    "minute": "*",
                    "month": "*",
                    "dom": "*",
                    "dow": "*"
                }
            }
        },
```

### CODE REVIEW

**Review by undsoft — COMMENTED** [review]
Do you know of any app that has `uri` control type so that I can test it?
BTW I don't see any `uri` related changes in the code.

**Comment by AlexKarpov98** [comment]
> Do you know of any app that has `uri` control type so that I can test it? BTW I don't see any `uri` related changes in the code.
Screenshot 2023-01-16 at 13 41 27

I think it was not there before, that's why no changes for `uri` 
gonna review once again.

**Comment by undsoft** [comment]
Can you provide instructions on how to actually test this? I see that there is a `cron` field in Launch Docker schema, but I don't know how to get to it through UI.

**Comment by AlexKarpov98** [comment]
> Can you provide instructions on how to actually test this? I see that there is a `cron` field in Launch Docker schema, but I don't know how to get to it through UI.

currently it's hidden, as I've seen in schema.

**Comment by undsoft** [comment]
Then how can I make sure it's working?

**Comment by AlexKarpov98** [comment]
@undsoft we need to tweak schema or update UI to allow showing hidden fields.

**Review by undsoft — CHANGES_REQUESTED** [review]
The point is that I cannot confirm that this PR is working unless you provide instructions on how to do this.
I can change mock in code to make field visible, but you have to tell me what to change.

**Comment by AlexKarpov98** [comment]
@undsoft  - steps attached. 
Once we merge this one, I will start working on `schedule` implementation instead of plain string.

**Comment by AlexKarpov98** [comment]
Waqar Ahmed:
Also middleware has not added any changes wrt schema changes etc

**Comment by undsoft** [comment]
So far don't see the app. I suppose showing [object Object] is better than the whole form crashing, but it's only marginally better :)

**Comment by AlexKarpov98** [comment]
@undsoft once it is merged, I'll work on improvements. :)

**Review by undsoft — APPROVED** [review]
NIce work!

Снимок экрана 2023-01-19 в 10 44 38

**Pull request merged**
