### PR TITLE
NAS-126957 / 24.10 / SMB Status Screen Improvements

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: see ticket

### CODE REVIEW

**Review by RehanY147 — COMMENTED** [review]
Change tilte from `Smb` to `SMB`

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Also, breadcrumb for `NFS Sessions` should be `Sharing -> NFS`

**Comment by AlexKarpov98** [comment]
@RehanY147 - okay, but please go ahead with the ticket borders, if we need to fix another things - it's always better to create a separate ticket!

**Comment by AlexKarpov98** [comment]
@RehanY147 - check it out now.

**Review by RehanY147 — APPROVED** [review]

**Pull request merged**
