### PR TITLE
NAS-114032 / 22.02 / NAS-114032: Center and add margins to entity-empty on entity-tables.

### PR DESCRIPTION
**Pull request by dszidi**
To test: 
- Go to a page that uses entity-table and doesn't have content.
- Make sure entity-empty is centered

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
Снимок экрана 2021-12-29 в 12 05 33
Directory Services page is still misaligned.
Do we know what caused the regression?

**Comment by dszidi** [comment]
I'm not sure where or when the directory services page layout regression happened. I noticed the entity-table issue yesterday after updating my VM from 22.02-MASTER-20211214-012925 to latest nightlies.  I'm also just now noticing the entity-table loader/spinner is left-aligned when it should be centered. I'll see if I can find the culprit.

**Review by undsoft — APPROVED** [review]
Looks good.

**Comment by dszidi** [comment]
@undsoft Should I backport?

**Comment by undsoft** [comment]
You can backport to bluefin.

**Pull request merged**
