### PR TITLE
NAS-109642 / 21.04 / Fix dialog overflow css

### PR DESCRIPTION
**Pull request by dszidi**

### CODE REVIEW

**Review by AlexKarpov98 — APPROVED** [review]
Perfect, thanks for quick fix!

**Review by ryousaf — APPROVED** [review]
LGTM

**Review by ryousaf — CHANGES_REQUESTED** [review]
Content goes out of bounds vertically when adding multiple fields

**Comment by dszidi** [comment]
> Content goes out of bounds vertically when adding multiple fields

I believe this was only on dialogForm. Fix applied, please check again.

**Review by AlexKarpov98 — APPROVED** [review]

**Review by ryousaf — APPROVED** [review]
LGTM

**Pull request merged**
