### PR TITLE
NAS-123885 / 24.04 / Remove DisplayVmDialogComponent

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: Go to Virtual Machines -> Click on Display button on one of the VM.
You should be redirected in other browser tab.

Screenshot 2023-09-06 at 16 05 34

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
The new tab just opens the same UI page again. And not anything related to the vm. Although the URL has the query params. What nightly build version is required for this to work?

**Comment by AlexKarpov98** [comment]
@RehanY147 - Middleware sends this:

```
{
    "error": null,
    "uri": "http://localhost:4200/vm/display/14/spice_auto.html?path=vm%2Fdisplay%2F14%2F&autoconnect=1"
}
```

**Comment by undsoft** [comment]
The localhost url is okay and happens on local webui instances. It'll be okay once deployed.

**Comment by AlexKarpov98** [comment]
> The localhost url is okay and happens on local webui instances. It'll be okay once deployed.

@RehanY147 - then we can approve and merge.

**Review by RehanY147 — APPROVED** [review]

**Pull request merged**
