### PR TITLE
NAS-125808 / 24.04 / Disable restricted controls for Credentials pages

### PR DESCRIPTION
**Pull request by undsoft**
Testing: test credential pages as Readonly and Sharing Manager user.

### CODE REVIEW

**Review by AlexKarpov98 — COMMENTED** [review]
Generally it works as expected, buttons are disabled, like:
Screenshot 2023-12-22 at 10 54 28

But one problem I noticed is that form can still be submitted via ENTER, for example, and then I see error modal:
Screenshot 2023-12-22 at 10 55 21

For readonly user - we still see ADD button, and for some cases I immediately see error modal (for example on Certificates page after I click ADD):

Screenshot 2023-12-22 at 11 05 43

**Comment by AlexKarpov98** [comment]
@undsoft - is that OK case?
https://github.com/truenas/webui/assets/22980553/559cbeef-0f4b-4f89-897e-4fffd955abd6

**Comment by undsoft** [comment]
@AlexKarpov98 The sidebar should not be closing – fixed. As for some endpoints being unavailable, this is expected. There is a middleware ticket about it.

**Review by AlexKarpov98 — APPROVED** [review]
Looks good 👍

**Pull request merged**
