### PR TITLE
NAS-122716 / 23.10 / User is able to see view the non-existing app page details

### PR DESCRIPTION
**Pull request by AlexKarpov98**
For testing try to reproduce this issue:

Screenshot 2023-06-29 at 23 59 31

You should end up on the installed apps instead of what is on the description screenshot since you try to view not available app.

As well I fixed this overlay issue on the login page:
Overlay issue visually: (fixed now)

https://github.com/truenas/webui/assets/22980553/0eef562a-62a5-42db-84c8-15d4b6e1bf7a

### CODE REVIEW

**Review by denysbutenko — APPROVED** [review]
There are routing guards designed for this purpose. Please consider if this fits scope of the ticket or create a new ticket for adjustments.

I was redirected to installed apps when putting in the wrong app name in the address bar. It works great.

**Comment by AlexKarpov98** [comment]
@denysbutenko - sure, we can rework the logic if we need it, for now I'll push this change in order for it to work.

**Comment by AlexKarpov98** [comment]
@denysbutenko - ticket created:
https://ixsystems.atlassian.net/browse/NAS-122720

**Comment by denysbutenko** [comment]
> @denysbutenko - ticket created: https://ixsystems.atlassian.net/browse/NAS-122720

thanks a lot

**Pull request merged**
