### PR TITLE
NAS-109659 / 21.04 / Change wording to "Unselect All" when all apps are selected / Nas 109659

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Review by sonicaj — COMMENTED** [review]
I have following concerns:
1) We should allow selecting all apps in bulk - right now no such option can be seen. It is only seen once i select one application.
Screenshot 2021-03-04 at 6 23 30 PM

**Comment by AlexKarpov98** [comment]
Updated

**Review by sonicaj — COMMENTED** [review]
Can we please reword the text here to "Requested action performed for selected Applications" ?

Screenshot 2021-03-04 at 9 04 48 PM

**Comment by AlexKarpov98** [comment]
Updated

**Comment by AlexKarpov98** [comment]
> Can we please reword the text here to "Requested action performed for selected Applications" ?
> 
> Screenshot 2021-03-04 at 9 04 48 PM

Updated

**Review by sonicaj — APPROVED** [review]

**Review by denysbutenko — APPROVED** [review]
Looks good

**Pull request merged**
