### PR TITLE
NAS-112435 / 21.10 / NAS-112435: Avoid button overlap

### PR DESCRIPTION
**Pull request by dszidi**
To test:

- Create some replication task (ticket says cloud sync but can be any kind really)
- Misconfigure it so it fails
- Click on the "FAILED" in the state table cell
- In the error dialog click on "More info" button to show the error message.
- Make sure the white text-area does not extend so far that the action buttons cover it.

### CODE REVIEW

**Comment by dszidi** [comment]
This is what it should look like. In addition to the overlapping issue mentioned in the ticket, I also fixed the "More info" text alignment with the icon. Also made the message area use the theme colors instead of defaulting to white which was really loud on dark themes

image

**Comment by denysbutenko** [comment]
image
`pre` area looking cut off (should take all width) and the buttons get overlap with `textarea`

**Comment by dszidi** [comment]
> `pre` area looking cut off (should take all width) and the buttons get overlap with `textarea`

Yep. I caught that too and am already working on it. Only happens when window height drops below a certain number of pixels.

**Comment by dszidi** [comment]
@denysbutenko Try it now

image

**Review by denysbutenko — APPROVED** [review]
Looks nice! Two small things, cursor on "More info" hover looking weird and textarea resize may unnecessary

**Comment by dszidi** [comment]
Yes I agree on the textarea. I'm not really sure why that element is being used here.

**Pull request merged**
