### PR TITLE
NAS-109316 / None / Misc bugfixes for NAS-109316

### PR DESCRIPTION
**Pull request by Ornias1993**
Made for NAS-109316 by @AlexKarpov98

- Fixes custom trains (not called "charts) not working
- Makes info modal availibility more clear on hover (color change and bigger pointer area)
- Gives a little more spaces for App titles (10-> 15 characters), as the "cutoff-dots" (...) also take up 3 characters
- Fixes Install wizard not taking Catalog and Train into account
- Fixes info modal not taking catalog and train into account

Signed-off-by: Kjeld Schouten-Lebbing <kjeld@schouten-lebbing.nl>

### CODE REVIEW

**Comment by denysbutenko** [comment]
Hi @Ornias1993, there is a typo in the branch name. Could you fix it, please?

**Comment by Ornias1993** [comment]
@denysbutenko SHOOT thanks.
Seems I cant change the branch on this repository. Going to have to resubmit (sadly enough)

**Comment by Ornias1993** [comment]
Now I get what you mean... The PR name, not the branch name.

**Comment by denysbutenko** [comment]
I meant this PR associated with https://jira.ixsystems.com/browse/NAS-109216 because of branch name contains `NAS-109216`

**Comment by Ornias1993** [comment]
@denysbutenko If you know a way of changing branch names, I'm all ears.

**Pull request closed without merging**
