### PR TITLE
NAS-130794 / 25.04 / Fix Cloud Backup Restore Include From Subfolder

### PR DESCRIPTION
**Pull request by denysbutenko**
**Changes:**

Fix Cloud Backup Restore Include From Subfolder

**Testing:**

Try to restore cloud backup with `Include from subfolder` option and use `Included Paths`.

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Works OK. I can see the restored data on the dataset following the instructions provided on the ticket.

Please provide specific instructions on how to confirm if this works correctly.
I created a TrueCloud backup task. Then ran it successfully. Restored using the task snapshot. But I don't see the file that was backed up.

**Comment by denysbutenko** [comment]
> Please provide specific instructions on how to confirm if this works correctly. I created a TrueCloud backup task. Then ran it successfully. Restored using the task snapshot. But I don't see the file that was backed up.

I followed the following steps:

1. Click on the eye icon on the successful TrueCloud backup task
2. Go to snapshot card and click the Restore icon
3. select 'Include from subfolder'
4. Subfolder:  Choose the subfolder from the dropdown that you want to include
5. Include path: select the path (please check the pictures)
5. Choose the target from the dropdown where you want to restore your data
6. save it
A popup text displaying restore is successful.
Go to shell and make sure restore is successful as your configuration.

**Review by undsoft — CHANGES_REQUESTED** [review]
Something doesn't work correctly.
I have backed up some files and folders.

When I select `Include everything`, all files and folders are restored to the root of the new dataset as expected.

When I use `Include from subfolder` and select root path `/mnt` nothing is restored.
When I select `Include from subfolder` and select deeper path (e.g. `subfolder` = `/mnt/dozer` and `Included Paths` = `/mnt/dozer/a/folder`), I get files restores, but they are restored with extra stuff in front of the path. I end up with `/mnt/dozer/b4/dozer/a/folder`, when I would expect it to be `/mnt/dozer/b4/folder`.

**Review by RehanY147 — APPROVED** [review]
Everything seems to work OK for me
image

**Comment by denysbutenko** [comment]
@undsoft

> Something doesn't work correctly. I have backed up some files and folders.
> 
> When I select `Include everything`, all files and folders are restored to the root of the new dataset as expected.
> 
> When I use `Include from subfolder` and select root path `/mnt` nothing is restored. When I select `Include from subfolder` and select deeper path (e.g. `subfolder` = `/mnt/dozer` and `Included Paths` = `/mnt/dozer/a/folder`), I get files restores, but they are restored with extra stuff in front of the path. I end up with `/mnt/dozer/b4/dozer/a/folder`, when I would expect it to be `/mnt/dozer/b4/folder`.

Include and Exclude Paths are relative to subfolder value. I think `/mnt/dozer/b4/dozer/a/folder` is expected result when `subfolder` = `/mnt` and `target` = `/mnt/dozer/b4`. 

To reduce the chances of mistakes, we can set the `subfolder` default value to the backup path rather than `/mnt`.

**Review by undsoft — APPROVED** [review]
I think it works well enough, I'm going to merge it.

**Pull request merged**
