### PR TITLE
NAS-126685 / 24.04 / Fixing pipeline

### PR DESCRIPTION
**Pull request by AlexKarpov98**
For testing -- see this PR, which is based on this branch in order to test pipeline:

https://github.com/truenas/webui/pull/9443

You should see that if only translation files were updated - we skip some of the steps and run only `Resort Strings and Commit if only translations were added` Step.

Screenshot 2024-01-11 at 15 52 35

As well you can go ahead and update some other non i18n file, to see that the pipeline will now skip `Resort Strings and Commit if only translations were added` Step and will only run previous steps we had.

Screenshot 2024-01-11 at 15 53 33

### CODE REVIEW

**Comment by bvasilenko** [comment]
@AlexKarpov98 would you pls share some more details. Like demo PR for testing? And summary of what has been changed?

**Comment by AlexKarpov98** [comment]
@bvasilenko - I updated ticket details.
Previous fix got a problem, @undsoft reported:
`something’s wrong with new translation actions` https://github.com/truenas/webui/actions/runs/7527451018

**Review by bvasilenko — CHANGES_REQUESTED** [review]
**1. Translation updates:**  - unfortunately it seems there's no match between actual/expected result

Expected result: only the translation-related action should run
Actual result:
image




**2. Code changes** - Looks Good!

image

**Comment by AlexKarpov98** [comment]
@bvasilenko - please use this latest PR for pipeline testing, it works for me.

https://github.com/truenas/webui/pull/9443, check ticket description.
That's what I see if only translation files were updated. 👇 
Screenshot 2024-01-16 at 23 35 26

**Comment by undsoft** [comment]
On this PR it says – `Expected — Waiting for status to be reported` on all build items. Shouldn't it be building?

**Comment by AlexKarpov98** [comment]
> On this PR it says – `Expected — Waiting for status to be reported` on all build items. Shouldn't it be building?

it should build, not sure what is that `Expected — Waiting for status to be reported`

**Comment by undsoft** [comment]
`Waiting for status to be reported` is there because it is marked as `Required` in github settings, but the workflow does not build this item.

**Review by bvasilenko — APPROVED** [review]
**1. Translation update**  - Works as expected!

image



**2. Change change**  - Looks Good!

image

**Comment by AlexKarpov98** [comment]
@undsoft - I added new commit and the process started, maybe it was some kind of glitch?

**Pull request merged**
