### PR TITLE
NAS-113675 / 22.02 / NAS-113675: Allow dashboard widgets to be reordered

### PR DESCRIPTION
**Pull request by bvasilenko**
image

**Testing:**
1. Desktop scenarios: 
   - Reorder, add/remove, cancel 
   - Reorder, add/remove, confirm (sequence of steps may vary)
2. Mobile - only regression testing

**Unit tests**

image

### CODE REVIEW

**Review by dszidi — COMMENTED** [review]
Behavior is off. When I drag the System Information card to position 3, it places it in position 2.  It seems to consistently put it 1 position behind where it actually is. Maybe it just needs a temporary card to fill the original position so when the user releases the card it stays where the user intended

image

**Comment by dszidi** [comment]
Let me try to clarify. My screenshot shows the Sysinfo widget hovering over the 3rd position. Ideally that third position should show as empty and the Memory widget should be in position 2. This would indicate to the user that when they release the card it will stay at the position their cursor was at.

**Review by RehanY147 — APPROVED** [review]
Nice work! LGTM.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
The reorder button behaves weirdly if you switch between mobile and desktop screens. E.g., if you're going from mobile -> desktop, the reorder button won't show up until refresh. If you go from desktop -> mobile, the reorder button won't go away always.

**Comment by RehanY147** [comment]
What I was talking about earlier.
reorder button issue

**Comment by bvasilenko** [comment]
Additions: 
+ grid layout for dragging (both vertical and horizontal directions)
+ animations
+ reusable "ix-drop-grid" directive
+ unit tests

**Review by RehanY147 — APPROVED** [review]
Functionally works well. The code looks OK too.

**Pull request merged**
