### PR TITLE
NAS-111493 / 12.0 / user / group quotas not properly displayed

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Comment by RehanY147** [comment]
How should this ticket affect the `Action` dropdown for the `Quota` tables? As it is now, looks like the column's `Toggle` actions just switched which users it should be showing. On the VM, you can see `user A` in the default view and both users in the toggle view. On this branch, `user B` is seen in the default view and both users in the toggle view.

**Comment by AlexKarpov98** [comment]
@RehanY147 I am not sure I am correct, but I think "looks like the column's Toggle actions just switched which users it should be showing" is correct. I asked the reporter(Andrew Walker), but no response so far.

**Comment by RehanY147** [comment]
@AlexKarpov98 Any updates on this? Were you able to confirm this behavior with Andrew?

**Comment by AlexKarpov98** [comment]
@RehanY147 Unfortunately, not yet.

**Review by undsoft — CHANGES_REQUESTED** [review]
Let's change the text in users and groups to:
> Show all available users, including those that do not have quotas set.
> Show only those users who have quotas. This is the default view.

If we have the same toggle in scale, need to port these changes too.

**Review by RehanY147 — APPROVED** [review]
The functionality is fine. Messaging seems better now.

**Pull request merged**
