### PR TITLE
NAS-116397 / 22.12 / NAS-116397: Disks page

### PR DESCRIPTION
**Pull request by undsoft**
Mostly just ports existing disk pages. You can access them via Storage2 -> Manage Disks.

### CODE REVIEW

**Comment by undsoft** [comment]
Couldn't reproduce. I've added something that may fix the issue.
In either case, this code is not new - this issue should exist in old smart test results page.

**Review by dszidi — COMMENTED** [review]
> ... this code is not new - this issue should exist in old smart test results page.

You're right. It is also available in current master branch. I pulled in your latest changes and it seems there is an error with one of the sass files

image

**Comment by undsoft** [comment]
Let's try again.

**Review by dszidi — APPROVED** [review]
LGTM

**Pull request merged**
