### PR TITLE
NAS-117875 / 22.12 / NAS-117875: redirect user to Available Applications if pool is not chosen

### PR DESCRIPTION
**Pull request by bvasilenko**
## Testing

On **Apps** page, for the first time (when pool is not set), 

- Expected Result: user should be sent to the **Available Applications** tab and **Choose a pool for Apps** popup should be displayed

### CODE REVIEW

**Comment by dszidi** [comment]
@undsoft do we want to completely prevent user from going to the "Installed Applications" tab until they set a pool? 
Seems a bit intrusive.

**Comment by undsoft** [comment]
Yeah, maybe, but to be fair if they haven't set up a pool, they wont' have any installed applications.
If we can easily allow them to go to Installed applications after redirect, let's do it, otherwise it's okay to keep how it is now.

**Comment by bvasilenko** [comment]
@dszidi 

Now **Choose a pool** opens only when user visits the **Apps** page, not when user switches to **Installed/available applications**

**Review by dszidi — APPROVED** [review]
Modal behaves as described above.
LGTM

**Pull request merged**
