### PR TITLE
NAS-124430 / 23.10.0 / Duplicate zvols and datasets are displayed upon initial creation and disappear when refresh browser

### PR DESCRIPTION
**Pull request by AlexKarpov98**
ATM - is not reproducing and reported can't reproduce either.

### CODE REVIEW

**Comment by undsoft** [comment]
So, there is some underlying problem that we need to find. This just puts a bandaid on it.

**Comment by AlexKarpov98** [comment]
> So, there is some underlying problem that we need to find. This just puts a bandaid on it.

yeah, that's why it was a draft PR :) 
I'm waiting for response from @BonnieF

**Comment by undsoft** [comment]
@AlexKarpov98 Ah, my mistake then. I've rescheduled it for 23.10.1.

**Comment by denysbutenko** [comment]
Ping me when it's ready for review.

**Review by denysbutenko — CHANGES_REQUESTED** [review]
Review is paused until further notification.

**Comment by AlexKarpov98** [comment]
moved back to the queue.

**Pull request closed without merging**
