### PR TITLE
NAS-123336 / 24.04 / WebUI tooltips are malfunctioning in chrome

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: 
See ticket description (I tested on Bluefin as well, problem occurs there as well, it's browser update problem)

and 👇

Check help tooltips
Screenshot 2023-08-03 at 16 55 07

(as well added hide on scroll feature, I think it's useful)

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
Now tooltips don't work for me in Chrome. They also flash in form when it is being open.

https://github.com/truenas/webui/assets/1481270/e8cb6159-6e76-452e-ab39-b57442cf1414

**Review by undsoft — CHANGES_REQUESTED** [review]
Tested in 3 browsers, with or without cache.
Same result – I cannot press on the tooltip icon.
In fact, I cannot press the underlying field in some places too. It's like the tooltip is open and blocking the access.

https://github.com/truenas/webui/assets/1481270/b6d1015d-70c4-4ac1-9f32-62a14f061451

**Comment by AlexKarpov98** [comment]
@undsoft 
Check it out now.
It's working fine for me [again].

**Review by denysbutenko — CHANGES_REQUESTED** [review]
https://github.com/truenas/webui/assets/351613/dc268de5-d750-4bc6-bef6-7016987a6feb

Chrome `115.0.5790.114` and `115.0.5790.170` shows the same behavior

**Comment by AlexKarpov98** [comment]
@undsoft @denysbutenko - now it will work! Please give it a try

**Review by denysbutenko — CHANGES_REQUESTED** [review]
https://github.com/truenas/webui/assets/351613/edbdf3db-96b7-4b15-afad-7bd2d77b7bc7

Tooltips are back, and an extra scrollbar has appeared.

**Review by undsoft — APPROVED** [review]
Appears to be working correctly for me.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Tooltips flash for half a second when you open the form

https://github.com/truenas/webui/assets/24204846/5741de41-44af-4738-8d2f-a9ce374a9e00

**Comment by AlexKarpov98** [comment]
@RehanY147 - please try with fresh `yarn install` 
i can't reproduce your defect.

@denysbutenko - please try it now [with Shell popper].

**Review by denysbutenko — APPROVED** [review]
It works great for me.

**Comment by AlexKarpov98** [comment]
@RehanY147 - waiting for you only.

**Review by RehanY147 — APPROVED** [review]

**Pull request merged**
