### PR TITLE
NAS-131316 / 25.04 / Rename SMART Test Results Fields

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: 

See ticket comments.
Screenshot 2024-09-30 at 14 12 40

### CODE REVIEW

**Review by RehanY147 — APPROVED** [review]
Looks good

**Review by RehanY147 — CHANGES_REQUESTED** [review]
These changes seem different than what's recommended. William asked the remaining to be 0% if it's completed. The PR changes it to "Completed". Also, the PR is missing the fix on the Error field mentioned in the ticket description.

**Comment by AlexKarpov98** [comment]
@RehanY147 - I talked to @william-gr 

Screenshot 2024-10-02 at 13 59 48

1. So we should keep current implementation.

2. Regarding error  field - it's updated as well.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
See above comment

**Comment by AlexKarpov98** [comment]
Hey @RehanY147  
I think we should merge this one and do fixes for this ticket https://ixsystems.atlassian.net/browse/NAS-131537 separately

**Review by RehanY147 — APPROVED** [review]

**Pull request merged**
