### PR TITLE
NAS-127245 / 24.10 / Start implementing strictNullChecks

### PR DESCRIPTION
**Pull request by bvasilenko**
**Summary**

Part 1 of `strictNullChecks`. 

Using the method from ticket's link, with adjusted tool.

- Tool: https://github.com/bvasilenko/strict-null-check-migration-tools/tree/NAS-127245

**Testing**

1. There's temporary side-config `tsconfig.strictNullChecks.json` for testing purposes. When running `./node_modules/.bin/tsc` with `tsconfig.strictNullChecks.json`  no errors expected
2. Code review

### CODE REVIEW

**Review by undsoft — COMMENTED** [review]
Maybe worth adding come commands to package.json if they are going to be used in the future.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
The `tsconfig.strictNullChecks.json` config should already be enabled when merging this PR. If not enabled, these changes are prone to be reverted by someone else working on the same files. It is possible to gradually whitelist files, however only files whose dependencies are also without strickNullCheck errors. Please discuss.

**Review by RehanY147 — COMMENTED** [review]
I've requested discussion on the testing methodology. Once clear, will review again.

**Review by RehanY147 — APPROVED** [review]

**Review by RehanY147 — CHANGES_REQUESTED** [review]
I can't see error descriptions.

**Review by RehanY147 — APPROVED** [review]
Looks good now

**Pull request merged**
