### PR TITLE
NAS-127437 / 24.10 / Refactor api-key-list.component List to ix-table2

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Test refactored table :
Screenshot 2024-02-21 at 12 02 20

### CODE REVIEW

**Review by bvasilenko — CHANGES_REQUESTED** [review]
Looks look overall, 

The only thing I've noticed that ability to sort by **Create Date** column is missing

**Comment by AlexKarpov98** [comment]
@bvasilenko, I tried with `sortBy: (row) => row.created_at.$date,` it's sorting it in some way, but not really correctly.
Maybe we need separate ticket for sorting dates?

**Comment by bvasilenko** [comment]
it looks fine now. @AlexKarpov98 would you pls re-request your review?

**Comment by AlexKarpov98** [comment]
@bvasilenko - sure, I already requested it.

**Review by bvasilenko — APPROVED** [review]
Looks good to me!

**Pull request merged**
