### PR TITLE
NAS-121010 / 23.10 / Attempting to enable samba authentication on user blocked on UI

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Comment by RehanY147** [comment]
Need credentials and a vm to test this one @AlexKarpov98. Do you have one or should we talk to middleware?

**Review by RehanY147 — COMMENTED** [review]
Comment

**Comment by AlexKarpov98** [comment]
@RehanY147 use **m40** device.

http://m40g3-137.dc1.ixsystems.net/ui/credentials/users

Try with new user, or use existing one `ggg`

Screenshot 2023-03-15 at 19 36 10

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Save button remains disabled

https://user-images.githubusercontent.com/24204846/225561803-caa0a8f9-c838-441b-a437-f48367027141.mov

**Review by undsoft — APPROVED** [review]
It works, but it just specifically fixes one problem in one place. The main issue is with how we handle errors - I'll create another ticket for it.

**Review by RehanY147 — APPROVED** [review]
It works! Although, the load state on this page isn't working when you click save on the dialog warning. I'll create a new ticket

**Pull request merged**
