### PR TITLE
NAS-116609 / 22.02.2 / add proper strings so enclosure mapping works

### PR DESCRIPTION
**Pull request by yocalebo**
This causes webUI to display the following error on SCALE MINI XL+
image

Since we have rebranded to TrueNAS, most of the systems we ship out the door are flashed with the `TRUENAS-` prefix in SMBIOS. I know basically 0 about typescript but I think this will fix it?

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
This won't work correctly.
`'string1 || 'string2'` in brackets will evaluate to `'string1'`
Has to be:
```
case 'FREENAS-MINI-3.0-E+':
case 'TRUENAS-MINI-3.0-E+':
// etc.
```

**Comment by yocalebo** [comment]
ping @dszidi @undsoft

**Review by undsoft — CHANGES_REQUESTED** [review]
Did you mean to remove `FREENAS-MINI-3.0-E+` and `FREENAS-MINI-3.0-X+`?

Also, you can fall-through:
```
case 'FREENAS-MINI-3.0-E':
case 'FREENAS-MINI-3.0-E+':
case 'TRUENAS-MINI-3.0-E':
case 'TRUENAS-MINI-3.0-E+':
     this.chassis = new MINI();
     break;
```

**Comment by yocalebo** [comment]
> Did you mean to remove `FREENAS-MINI-3.0-E+` and `FREENAS-MINI-3.0-X+`?
> 
> Also, you can fall-through:
> 
> ```
> case 'FREENAS-MINI-3.0-E':
> case 'FREENAS-MINI-3.0-E+':
> case 'TRUENAS-MINI-3.0-E':
> case 'TRUENAS-MINI-3.0-E+':
>      this.chassis = new MINI();
>      break;
> ```

Woops, should be fixed.

**Review by undsoft — APPROVED** [review]
Thanks 👍🏻

**Pull request merged**
