### PR TITLE
NAS-121299 / 23.10 / NAS-121293: Button missing to edit app info on the installed apps page

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Review by RehanY147 — COMMENTED** [review]
The install form doesn't work yet. Need that to be fixed to confirm that the edit button works. I'll add the blocking ticket.

**Comment by undsoft** [comment]
@RehanY147 @AlexKarpov98 Are we still waiting for something here?

**Comment by AlexKarpov98** [comment]
> @RehanY147 @AlexKarpov98 Are we still waiting for something here?

I assume we could merge it.

**Comment by RehanY147** [comment]
Was waiting for the store ticket. We were fetching all apps from one catalog and train with a constant value. That didn't work and we couldn't go from details to install form like that. That's fixed in the store ticket.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
You need to have the catalog and train from the details page to the chart wizard/form to fetch the correct app schema etc.

**Comment by RehanY147** [comment]
You should merge `master` to get the latest code fixes

**Review by RehanY147 — APPROVED** [review]
There should be a test case to test the button click that it loads the right URL with the right params.

**Pull request merged**
