### PR TITLE
NAS-111303 / 21.08 / Render ix-chart dynamically in the UI

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Review by sonicaj — COMMENTED** [review]
I have following concerns:

1) Let's please reword ix-chart to `Launch Docker Image` as user would be unaware what ix-chart is

Screenshot 2021-07-19 at 1 01 23 PM

2) Let's please remove version for launch docker image workload and always use the latest one available from charts train which is supported by the system.

Screenshot 2021-07-19 at 1 02 33 PM

**Comment by denysbutenko** [comment]
Not sure if it's in the scope of the ticket. It would be nice to skip empty list items in summary
image

**Review by denysbutenko — APPROVED** [review]
otherwise looks good 👍🏻

**Review by denysbutenko — APPROVED** [review]
Looks good!

**Review by sonicaj — APPROVED** [review]
Thanks!

**Pull request merged**
