### PR TITLE
NAS-117754 / 22.12 / Font rendering fix

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Review by undsoft — APPROVED** [review]
Nice 👍

**Review by undsoft — CHANGES_REQUESTED** [review]
Actually was to early to approve.
Font looks similar between browsers, but they look differently to what we had before.
Damian wanted to replace header fonts, can you either make fonts looks like they looked before (just so that they look similar in all browsers) or confirm with @dszidi  if change of header font is okay.

**Comment by AlexKarpov98** [comment]
@dszidi please have a look at @undsoft comment. (https://github.com/truenas/webui/pull/7104#pullrequestreview-1114225354)

**Review by dszidi — APPROVED** [review]
LGTM

**Comment by AlexKarpov98** [comment]
@undsoft please have a look now

**Review by undsoft — CHANGES_REQUESTED** [review]
Any chance of making fonts look similar between browsers and similar to what we had before?

**Comment by AlexKarpov98** [comment]
Chrome:
Screen Shot 2022-09-27 at 14 51 58

___

Safari NOW:
Screen Shot 2022-09-27 at 14 50 49

___

Safari without fixes:
Screen Shot 2022-09-27 at 14 51 21

**Comment by AlexKarpov98** [comment]
@undsoft 
@dszidi 
for me it looks OK now, chrome stays the same, safari is nicer and more similar to Chrome.

**Review by dszidi — APPROVED** [review]
@undsoft I'm ok with what's in those screenshots.
We might not want to dwell on this much longer anyways considering we might be changing the title font and doing [work on typography](https://ixsystems.atlassian.net/browse/NAS-118365) in general.

**Comment by AlexKarpov98** [comment]
@undsoft 
@dszidi 
okay, so if we need these changes, please merge them, if not - let's close the PR :)

**Review by undsoft — APPROVED** [review]
Yes, looks good.

**Pull request merged**
