### PR TITLE
NAS-116915 / 22.12 / NAS-116915: Add the pool header row on Datasets IxTreeTable (v2)

### PR DESCRIPTION
**Pull request by bvasilenko**
V2 of #6883 

image

**Update**: the purpose of this PR

> Let's keep current branch and PR open and try a different option with just having some visual separation between pools:
> 
> image (3)

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
Doesn't look right
Снимок экрана 2022-08-05 в 11 45 43

**Review by AlexKarpov98 — CHANGES_REQUESTED** [review]
The pool header row should be added like this.
image

**Comment by bvasilenko** [comment]
@AlexKarpov98 

> The pool header row should be added like this.

The picture you've attached is depicting the previous version (v1), which is reviewed in [another PR](https://github.com/truenas/webui/pull/6883). At this PR we're implementing an alternative version. I've just updated ticket's description above, so it contains this remark.

**Comment by bvasilenko** [comment]
> Doesn't look right Снимок экрана 2022-08-05 в 11 45 43

@undsoft This should be fixed by latest commit

**Pull request closed without merging**
