### PR TITLE
NAS-123820 / 24.04 / Remove `selected` property from ChartRelease interface

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: check that app selection works as before

### CODE REVIEW

**Review by denysbutenko — CHANGES_REQUESTED** [review]
Some regressions are found. `Check/Uncheck All` does not work properly. Checkboxes at rows are still unchecked. Checkboxes randomly being unchecked when checking others. See recording: 

https://github.com/truenas/webui/assets/351613/d215f00a-ae16-4ed5-bc70-9c5a94a42b3a

**Review by denysbutenko — CHANGES_REQUESTED** [review]
Those regressions are still reproducible.
> Checkboxes randomly being unchecked when checking others. The selected count exceeds the installed apps.

https://github.com/truenas/webui/assets/351613/9f41ff43-fb88-4da3-a99f-075ea46c7ad2

**Comment by AlexKarpov98** [comment]
@denysbutenko - now it is fixed, the problem was that I stored objects and the cursor for the object changed after updates came.
As well I fixed sorting issue - since when data got updated - it returned to the default sorting.

**Review by denysbutenko — APPROVED** [review]
Looks good 👍🏻

**Pull request merged**
