### PR TITLE
NAS-116342 / 22.12 / Refactoring Docker Images to ix-table

### PR DESCRIPTION
**Pull request by denysbutenko**
Changes:

- Refactoring Docker Images to ix tables – Add extra columns and bulk actions (update/delete)
- Add component store for docker images
- Refactoring Docker Image Update Dialog to support bulk updating
- Refactoring Docker Image Delete Dialog to support bulk deleting

Testing:

- Test single image pull/delete/update
- Test bulk delete/update

mock query to check update dialog:
```
midclt call test.set_mock container.image.query '{"return_value": [{"id": "sha256:52916ce4626ff88ba06a84a216bc013a63d02df9a3ff040ef0501f8938b6b210", "labels": {"org.opencontainers.image.created": "2022-05-23T16:25:39.041Z", "org.opencontainers.image.description": "Pi-hole in a docker container", "org.opencontainers.image.licenses": "", "org.opencontainers.image.revision": "1570a7682e60b7f3bcbcabad8d3fb8a167f1170e", "org.opencontainers.image.source": "https://github.com/pi-hole/docker-pi-hole", "org.opencontainers.image.title": "docker-pi-hole", "org.opencontainers.image.url": "https://github.com/pi-hole/docker-pi-hole", "org.opencontainers.image.version": "2022.05"}, "repo_tags": ["pihole/pihole:2022.05"], "repo_digests": ["pihole/pihole@sha256:dcd0885a3fe050da005cb544904444cc098017636d6d495ac8770a9aa523a0ef"], "size": 303732678, "created": {"$date": 1653297997000}, "dangling": false, "update_available": false, "system_image": false}, {"id": "sha256:3ce7ff7e2ca3b1558868919fa659e0272c3a97a87c8da3bcd3c9be91f1ae173d", "labels": {}, "repo_tags": ["plexinc/pms-docker:1.26.1.5798-99a4a6ac9"], "repo_digests": ["plexinc/pms-docker@sha256:dee309deea268024b36a9b06067e508084aefe9e5de9dca9b57b15a2ae936c0b"], "size": 632380232, "created": {"$date": 1652155084000}, "dangling": false, "update_available": false, "system_image": false}, {"id": "sha256:9957eafb3901831943ecc11aee10ab980f351ab3829e82a5ff1207f62df4095e", "labels": {}, "repo_tags": ["ghcr.io/opengs/uashield:1.0.5"], "repo_digests": ["ghcr.io/opengs/uashield@sha256:48691d4b37fe2c6c61cdd6f9978b3e11741abd3f5c6a58d9e4fd2e40fce1f30a"], "size": 113889648, "created": {"$date": 1650761485000}, "dangling": false, "update_available": false, "system_image": false}, {"id": "sha256:83fba0db226df27077f7de3480718c8fa1f2a439ec8dc2a285181cfca973c054", "labels": {"org.opencontainers.image.created": "2022-04-20T20:18:01.702Z", "org.opencontainers.image.description": "Pi-hole in a docker container", "org.opencontainers.image.licenses": "", "org.opencontainers.image.revision": "ebbbdae2dfce38bb089f31eeab9b6aff2d80f43d", "org.opencontainers.image.source": "https://github.com/pi-hole/docker-pi-hole", "org.opencontainers.image.title": "docker-pi-hole", "org.opencontainers.image.url": "https://github.com/pi-hole/docker-pi-hole", "org.opencontainers.image.version": "2022.04.3"}, "repo_tags": ["pihole/pihole:2022.04.3"], "repo_digests": ["pihole/pihole@sha256:fa050f8407fc9b63840025f7064763cc20f2b8dd30461852daabb2c33a8231f8"], "size": 303330493, "created": {"$date": 1650460724000}, "dangling": false, "update_available": true, "system_image": false}, {"id": "sha256:becf1f1efe2e255ec188726dca00ded27d7f1eb088c9eb8bc1db0acd32df2ee0", "labels": {}, "repo_tags": ["netdata/netdata:v1.34.1"], "repo_digests": ["netdata/netdata@sha256:04494e001fc6854eb86dd6d53f8194554d3919652ea36d6f75c8f5974de05e1d"], "size": 371949543, "created": {"$date": 1650014400000}, "dangling": false, "update_available": false, "system_image": false}, {"id": "sha256:a61301191305f95bf0044faa5ba72ad2777bb56a6310ea919bc0ceaaa449800b", "labels": {"maintainer": "Bitnami <containers@bitnami.com>", "org.opencontainers.image.source": "https://github.com/truecharts/containers"}, "repo_tags": [], "repo_digests": ["ghcr.io/truecharts/postgresql@sha256:d4e2ab2f3d41e04b2e4d1812058b26b0fbf409b65ce9352d8c714ff33fc66986"], "size": 271998885, "created": {"$date": 1642952716000}, "dangling": false, "update_available": false, "system_image": false}, {"id": "sha256:b2421beea36e51062622b06f2b7683e5b221dc17396f054b20d7983d3840c998", "labels": {"io.hass.arch": "amd64", "io.hass.base.arch": "amd64", "io.hass.base.image": "homeassistant/amd64-base:3.14", "io.hass.base.name": "python", "io.hass.base.version": "2021.09.1", "io.hass.type": "core", "io.hass.version": "2021.12.10", "org.opencontainers.image.authors": "The Home Assistant Authors", "org.opencontainers.image.created": "2022-01-18 00:31:58+00:00", "org.opencontainers.image.description": "Open-source home automation platform running on Python 3", "org.opencontainers.image.documentation": "https://www.home-assistant.io/docs/", "org.opencontainers.image.licenses": "Apache License 2.0", "org.opencontainers.image.source": "https://github.com/truecharts/containers", "org.opencontainers.image.title": "Home Assistant", "org.opencontainers.image.url": "https://www.home-assistant.io/", "org.opencontainers.image.version": "2021.12.10"}, "repo_tags": [], "repo_digests": ["tccr.io/truecharts/home-assistant@sha256:b871fc29dc0a7f2b2e4809ac7afd37ca280483d5706be6167d594ffff6ea3a69"], "size": 1163319065, "created": {"$date": 1642437691000}, "dangling": false, "update_available": false, "system_image": false}, {"id": "sha256:f937e4e4c3438f3b1c5d2f3d342f9d803b29d35518dcac8d703b5463eb72e04b", "labels": {"maintainer": "TrueCharts <info@truecharts.org>", "org.opencontainers.image.source": "https://github.com/truecharts/apps"}, "repo_tags": [], "repo_digests": ["ghcr.io/truecharts/alpine@sha256:4095394abbae907e94b1f2fd2e2de6c4f201a5b9704573243ca8eb16db8cdb7c"], "size": 23067494, "created": {"$date": 1637736303000}, "dangling": false, "update_available": false, "system_image": false}, {"id": "sha256:10dbacde5cc28b2cffd77a3d103a5500610fa8e75638b7fdcf06077c362043c8", "labels": {"org.label-schema.build-date": "2021-09-16T11:53:55UTC", "org.label-schema.description": "OpenEBS ZFS LocalPV Driver", "org.label-schema.name": "zfs-driver", "org.label-schema.schema-version": "1.0", "org.label-schema.url": "https://openebs.io", "org.label-schema.vcs-url": "https://github.com/openebs/zfs-localpv"}, "repo_tags": ["openebs/zfs-driver:1.9.3"], "repo_digests": ["openebs/zfs-driver@sha256:1f6f18059a646ca1ce8fc8f5a305b0f902a13723b8e162206ce23f8359bd1d0b"], "size": 174657370, "created": {"$date": 1631768093000}, "dangling": false, "update_available": true, "system_image": false}, {"id": "sha256:61345d6582f93f4cdad8a836fff6f9ec5a21346b7bd889da371af41e92bde85d", "labels": {}, "repo_tags": ["nextcloud:21.0.0"], "repo_digests": ["nextcloud@sha256:7e0ea42ce29b28c97d4417dfb1873e2f91d674b9646f0f444d8cc71378d52664"], "size": 834761133, "created": {"$date": 1617237490000}, "dangling": false, "update_available": true, "system_image": false}, {"id": "sha256:3885a5b7f138c3e8779a18f672fd55c3c7cf0166b67cf5143ab0cd137eb38418", "labels": {}, "repo_tags": ["rancher/coredns-coredns:1.8.3"], "repo_digests": ["rancher/coredns-coredns@sha256:9d4f5d7968c432fbd4123f397a2d6ab666fd63d13d510d9728d717c3e002dc72"], "size": 43486589, "created": {"$date": 1614146360000}, "dangling": false, "update_available": true, "system_image": true}, {"id": "sha256:407cece1abfffb1e84b5feb8a763f3773c905c409e52c0ee5f57f33acf0c10c6", "labels": {}, "repo_tags": ["postgres:13.1"], "repo_digests": ["postgres@sha256:26180996f7d804993f9c90398615d1269709a799b5eb79109292843a1c7cd851"], "size": 314189269, "created": {"$date": 1612866649000}, "dangling": false, "update_available": false, "system_image": false}, {"id": "sha256:da32a49a903a6da38480f7485ea5927eaeec1e0c9bc79e5b7952bb1709670d1c", "labels": {"description": "CSI External Snapshotter Sidecar", "maintainers": "Kubernetes Authors", "revision": "v4.0.0"}, "repo_tags": ["k8s.gcr.io/sig-storage/csi-snapshotter:v4.0.0"], "repo_digests": ["k8s.gcr.io/sig-storage/csi-snapshotter@sha256:51f2dfde5bccac7854b3704689506aeecfb793328427b91115ba253a93e60782"], "size": 49543356, "created": {"$date": 1608293077000}, "dangling": false, "update_available": false, "system_image": true}, {"id": "sha256:f1d8a00ae690f549c0e4c4a152ae914ba349b21bab63cc32c3f571cb46ce5780", "labels": {"description": "Snapshot Controller", "maintainers": "Kubernetes Authors", "revision": "v4.0.0"}, "repo_tags": ["k8s.gcr.io/sig-storage/snapshot-controller:v4.0.0"], "repo_digests": ["k8s.gcr.io/sig-storage/snapshot-controller@sha256:00fcc441ea9f72899c25eed61d602272a2a58c5f0014332bdcb5ac24acef08e4"], "size": 46567186, "created": {"$date": 1608292446000}, "dangling": false, "update_available": false, "system_image": true}, {"id": "sha256:a8fe79377034e98d6c1161f0dc289d82db3d6fa61896e0e60985e1eb9426c710", "labels": {"description": "CSI External Resizer", "maintainers": "Kubernetes Authors", "revision": "v1.1.0"}, "repo_tags": ["k8s.gcr.io/sig-storage/csi-resizer:v1.1.0"], "repo_digests": ["k8s.gcr.io/sig-storage/csi-resizer@sha256:7a5ba58a44e0d749e0767e4e37315bcf6a61f33ce3185c1991848af4db0fb70a"], "size": 49160266, "created": {"$date": 1608284676000}, "dangling": false, "update_available": false, "system_image": true}, {"id": "sha256:e0d187f105d601e694032928f48b0535482cd8df52645bc52510639fec08aec0", "labels": {"description": "CSI External Provisioner", "maintainers": "Kubernetes Authors", "revision": "v2.1.0"}, "repo_tags": ["k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0"], "repo_digests": ["k8s.gcr.io/sig-storage/csi-provisioner@sha256:20c828075d1e36f679d6a91e905b0927141eef5e15be0c9a1ca4a6a0ed9313d2"], "size": 51629546, "created": {"$date": 1608234538000}, "dangling": false, "update_available": false, "system_image": true}, {"id": "sha256:ef2b13b2a0667ddc97e10bd089672a9db65a7718073467d532e98c21290dd0b2", "labels": {"description": "CSI Node driver registrar", "maintainers": "Kubernetes Authors", "revision": "v2.1.0"}, "repo_tags": ["k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0"], "repo_digests": ["k8s.gcr.io/sig-storage/csi-node-driver-registrar@sha256:a61d309da54641db41fb8f35718f744e9f730d4d0384f8c4b186ddc9f06cbd5f"], "size": 19646681, "created": {"$date": 1608224246000}, "dangling": false, "update_available": false, "system_image": true}, {"id": "sha256:897ce3c5fc8ff8b1ad4fe1e74f725a0942e8e1dad0ee09096cfa7320da889a53", "labels": {"org.label-schema.build-date": "2019-05-22T23:40:26Z", "org.label-schema.schema-version": "1.0", "org.label-schema.vcs-ref": "824f44ae4ba761ec2a5fe5602b3dfcb7982f32f2", "org.label-schema.vcs-url": "https://github.com/rancher/klipper-lb.git"}, "repo_tags": ["rancher/klipper-lb:v0.1.2"], "repo_digests": ["rancher/klipper-lb@sha256:2fb97818f5d64096d635bc72501a6cb2c8b88d5d16bc031cf71b5b6460925e4a"], "size": 6099268, "created": {"$date": 1558543231000}, "dangling": false, "update_available": false, "system_image": true}, {"id": "sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e", "labels": {}, "repo_tags": ["rancher/pause:3.1"], "repo_digests": ["rancher/pause@sha256:d22591b61e9c2b52aecbf07106d5db313c4f178e404d660b32517b18fcbf0144"], "size": 742472, "created": {"$date": 1513776649000}, "dangling": false, "update_available": false, "system_image": true}]}'
```

### CODE REVIEW

**Comment by AlexKarpov98** [comment]
- No error/UI for the updating of the image that repo-tags is empty
Screenshot_94
Screenshot_95

**Comment by denysbutenko** [comment]
> Nice Bulk Action!
> 
> Screenshot_88
> 
> 
> 
> - Unset Pool is missing and Clicking does not work in Settings actions, and Launch Image is disabled.
> 
> 
> 
> Before:
> 
> Screenshot_96
> 
> After:
> 
> Screenshot_90
> 
> 
> 
> 

Good catch. Some regression with entity toolbar after moving images to own module. Thanks will take a look.

**Comment by denysbutenko** [comment]
> - No error/UI for the updating of the image that repo-tags is empty
> 
> Screenshot_94
> 
> Screenshot_95
> 
> 
> 
> 

That's a good point. Perhaps images without repo_tags can not be updated. Mistake in mock query when I set update_available to the image without repo_tags. I'll double check that case.

**Comment by denysbutenko** [comment]
A combination of mat-tabs and lazy-loading tab content with the global entity toolbar does not work. Reverted back to approach when 4 tabs need to be loaded before content appears.

**Review by AlexKarpov98 — APPROVED** [review]
LGTM! 👍

**Pull request merged**
