### PR TITLE
NAS-115669 / 13.0 / After upgrade the Standby controller card didn't update until Screen refresh/relog in

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
Retested failover on 12 -> 13 update. Version didn't update correctly. Will provide more info later.

**Comment by AlexKarpov98** [comment]
> Retested failover on 12 -> 13 update. Version didn't update correctly. Will provide more info later.

@undsoft - page reload  when logged out didn't help?

**Review by undsoft — CHANGES_REQUESTED** [review]
Issues are not fixed.
1. When second controller is being rebooted, dashboard card incorrectly reports that failover is active.
2. When second controller has finished rebooting, dashboard card still says U8.1.

**Review by undsoft — APPROVED** [review]
Mission accomplished 🥳

**Comment by AlexKarpov98** [comment]
> Mission accomplished 🥳

roger that!

**Pull request merged**
