### PR TITLE
NAS-118817 / 22.12 / Refactor Zvol form

### PR DESCRIPTION
**Pull request by bvasilenko**

### CODE REVIEW

**Review by dszidi — COMMENTED** [review]
Testing this on our M40 and it seems the form submits fine but the zvol doesn't show up on the datasets page after submission>

image

image

**Review by dszidi — COMMENTED** [review]
The ticket specifies that the "Advanced Options" button should not be present.

image

**Comment by bvasilenko** [comment]
> The ticket specifies that the "Advanced Options" button should not be present.
> 
> image

@dszidi this is now fixed

**Review by dszidi — APPROVED** [review]
LGTM

**Pull request merged**
