### PR TITLE
NAS-132785 / 25.10 / Use cdkDragList for dashboard widgets

### PR DESCRIPTION
**Pull request by denysbutenko**
**Changes:**

- Fixes dashboard drag and drop. Requires Angular 19.
- Use `cdkDragList` and `cdkDropListOrientation="mixed"`
- Remove `ixDragList` module

**Testing:**

- Try to drag and drop widgets on main dashboard.

### CODE REVIEW

**Comment by denysbutenko** [comment]
time 04:00

**Comment by bvasilenko** [comment]
https://github.com/truenas/webui/pull/11103 has been merged now.
@denysbutenko could you please rebase on the latest master?

**Review by bvasilenko — CHANGES_REQUESTED** [review]
needs rebasing

**Comment by denysbutenko** [comment]
@bvasilenko good catch. fixed now

**Review by bvasilenko — APPROVED** [review]
Works perfect!

**Pull request merged**
