### PR TITLE
NAS-130470 / 24.10 / Adds back container functionality

### PR DESCRIPTION
**Pull request by RehanY147**
**Changes:**

Adds back docker container functionality

**Testing:**

Test docker container list page. Test bulk delete function. Also test that data is displayed correctly on the page. Also test that `dockerhub_rate_limit` is handled correctly.

### CODE REVIEW

**Review by denysbutenko — CHANGES_REQUESTED** [review]
image

Menu item is missing.
Routing is not connected.
How to test the changes?

**Review by denysbutenko — CHANGES_REQUESTED** [review]
image

Checkbox column is missing to test bulk items delete.

**Review by undsoft — APPROVED** [review]
I can live without a checkbox column for now if it's too hard to add. In this case create a ticket to improve this later.

I did however try to pull `nginx` image and receive an error:
```
[EFAULT] Failed to pull 'nginx:vlatest' image: 404 Client Error for http+docker://localhost/v1.46/images/create?tag=vlatest&fromImage=nginx: Not Found ("manifest for nginx:vlatest not found: manifest unknown: manifest unknown")
```

**Comment by RehanY147** [comment]
I've created a new ticket to add bulk checkbox for deletion

**Comment by RehanY147** [comment]
https://ixsystems.atlassian.net/browse/NAS-130533

**Review by undsoft — APPROVED** [review]
Our code looks okay, but I'd like to know why I wasn't able to install `nginx`.

**Comment by RehanY147** [comment]
@undsoft I talked to middleware about tag and there was a misunderstanding on what tag is. I wrongly assumed that whatever the tag string would be, I would have to prefix it with a `'v'` character so the image name and tag name would be joined like so. `'[IMAGE_NAME]:v[TAG_NAME]'`. However, I didn't need to add any prefixes. Tag need to be joined as is to the image name like so. `'[IMAGE_NAME]:[TAG_NAME]'`. The updated code reflects this change.

**Pull request merged**
