### PR TITLE
NAS-127039 / 24.10 / Feedback form - Rate page error handling is missing, i.e I try to upload 10mb image

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing:
See ticket & try to upload large image for the feedback form.

### CODE REVIEW

**Comment by AlexKarpov98** [comment]
@denysbutenko - what do you think about it?
I don't really like the idea of just silently ignoring image uploading.
If that fine, we can close the PR and ticket.

**Comment by denysbutenko** [comment]
> @denysbutenko - what do you think about it? I don't really like the idea of just silently ignoring image uploading. If that fine, we can close the PR and ticket.

I think it would be better to prevent adding files if the size is exceeded - raise validation error. Some time ago, I assumed that JIRA and feedback service have equal limits, which was wrong - it needs to differentiate or create a ticket to sync limits. Regarding the current behavior of silently ignoring errors - I think that's okay, but it would be better to ask @undsoft

**Comment by AlexKarpov98** [comment]
I like the idea of limit sync and raising error if file is too big - before upload.
@undsoft

**Comment by undsoft** [comment]
Both behaviours are okay. The reason I disabled error reporting for reviews is because it's not too critical in reviews if image was uploaded, but having an error could work too.
Validation error sounds good.

**Comment by denysbutenko** [comment]
@AlexKarpov98 would you like to merge this PR or plan to change something?

**Comment by AlexKarpov98** [comment]
> @AlexKarpov98 would you like to merge this PR or plan to change something?

@denysbutenko - I think we can close this one and create new ticket. --> `Feedback form: File Size Limit sync & raise error if file is too big - before upload.`

**Pull request closed without merging**
