### PR TITLE
NAS-127589 / 24.10 / Use new download VM logs endpoint in WebUI

### PR DESCRIPTION
**Pull request by denysbutenko**
M40 is ready for testing this PR. Try to download logs on the VM page.

### CODE REVIEW

**Comment by AlexKarpov98** [comment]
@denysbutenko 
Screenshot 2024-03-07 at 10 28 26
on m40 I get this error

**Review by AlexKarpov98 — COMMENTED** [review]
Method is called correctly, but I was not able to achieve successful response.
@denysbutenko - please let me know how to correctly test it? 😺

**Comment by denysbutenko** [comment]
@AlexKarpov98 ready for testing now

**Comment by AlexKarpov98** [comment]
@denysbutenko I see this using m40.
Screenshot 2024-03-13 at 13 59 31

**Review by AlexKarpov98 — COMMENTED** [review]
I still was not able to download logs successfully.
and as well would be good to have some waiting feedback for the user.
Currently I clicked the button and not sure what's happening.

https://github.com/truenas/webui/assets/22980553/596d5861-4da1-4b71-9140-2ef063932dc8

**Review by AlexKarpov98 — APPROVED** [review]
Loader works good. 
I still get 500 error.
Maybe it will work on nightly machine?
Screenshot 2024-03-14 at 11 29 18

**Comment by AlexKarpov98** [comment]
@denysbutenko - that's what I see.

https://github.com/truenas/webui/assets/22980553/97e720dc-9082-40ff-9f8e-9d9e21eb1100

**Comment by denysbutenko** [comment]
> Loader works good. I still get 500 error. Maybe it will work on nightly machine? Screenshot 2024-03-14 at 11 29 18

Nightly instances do not support virtualization. I tried to test from the branch and using a docker image in both cases worked for me. It looks like a proxy issue that is not related to changes.

**Pull request merged**
