### PR TITLE
NAS-130629 / 25.04 / Add "Reset" to configure dashboard

### PR DESCRIPTION
**Pull request by denysbutenko**

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
I think there should be an extra step before saving the "Reset" dashboard. The reset should only apply locally. The user should still be able to cancel the reset function and undo their reset.

**Comment by RehanY147** [comment]
Once the "Reset" button is clicked, the default dashboard config should be applied and shown the user but not saved. The user should be able to click cancel button and not save those changes.

**Comment by denysbutenko** [comment]
> I think there should be an extra step before saving the "Reset" dashboard. The reset should only apply locally. The user should still be able to cancel the reset function and undo their reset.
> Once the "Reset" button is clicked, the default dashboard config should be applied and shown the user but not saved. The user should be able to click cancel button and not save those changes.

This sounds reasonable. PR is updated.

**Review by undsoft — APPROVED** [review]
Looks good 👍🏼

**Pull request merged**
