### PR TITLE
NAS-111468 / 21.08 / NAS-111468 - POSIX ACL Editor

### PR DESCRIPTION
**Pull request by undsoft**
Design: https://xd.adobe.com/view/285bc415-335a-4aff-b632-3e9c6ab7e179-7d08/screen/d629a09e-fe21-4ed6-9def-906e885858d8

**Testing**
Only test datasets with acltype = POSIX.
Create a POSIX dataset -> View permissions -> Edit -> Set ACL.

The following scenarios need testing:
Adding acl item, editing, removing, saving.
Stripping ACL.

**Known issues**
Will be addressed in future PRs:
Radio button alignment does not match design
Dropdowns are used instead checkbox groups.

### CODE REVIEW

**Comment by AlexKarpov98** [comment]
@undsoft [Strip ACL] Error:  `filesystem_acl.acltype: ACL type mismatch. On-disk format is [POSIX1E], but received [NFS4].`
image

**Comment by AlexKarpov98** [comment]
@undsoft [Add Item] Failed:  `filesystem_acl.dacl: Named (user or group) POSIX ACL entries require a mask entry to be present in the ACL.`
acl_add_item_failed

**Comment by AlexKarpov98** [comment]
@undsoft [Delete Item] Failed: `filesystem_acl.dacl: Presence of [OTHER] entry is required.`
acl_delete_item_failed

**Comment by undsoft** [comment]
The first one appears to be a middleware issue, good catch.
Two last items are expected – they are validation errors. I guess we can try improving UI to validate things on our end first. Will create a ticket for this.
Will let you know when stripping acl issue is resolved.

**Comment by undsoft** [comment]
The strip acl issue got fixed on latest middleware. I've updated our cloud vm.

**Review by AlexKarpov98 — APPROVED** [review]
@undsoft Confirmed.

**Pull request merged**
