### PR TITLE
NAS-130379 / 24.10 / Workloads card

### PR DESCRIPTION
**Pull request by undsoft**
**Testing:**

Test workloads card.

### Downstream

|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   | Behaviour of workloads card changed.

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
image
This dialog doesn't seem consistent with the other dialogs we show. I think it should have action buttons even if just to click "Ok".

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Also, since the max width for dialogs was removed, I think that made some dialogs look weird. Like the dialog that warns about installing apps is too wide and doesn't look nice.

**Comment by undsoft** [comment]
Okay, added OK button and reverted dialog width change.

**Review by RehanY147 — APPROVED** [review]
Looks good. The "Ok" button has weird margins but otherwise it's OK.
image

**Review by RehanY147 — COMMENTED** [review]
In the dialog, maybe the source column can be truncated. Show full value on hover. Give other columns more width to show their values in one row.

**Comment by undsoft** [comment]
I'll keep as is for now, later we need to figure out the issue that prevents dialog from having width overrides.

**Pull request merged**
