### PR TITLE
NAS-127082 / 24.10 / Added `ix-code-editor` and support for `text` dynamic form item type

### PR DESCRIPTION
**Pull request by RehanY147**
Testing instructions are in the ticket.

### CODE REVIEW

**Review by denysbutenko — COMMENTED** [review]
Waiting to be unblocked

**Comment by RehanY147** [comment]
@denysbutenko Ready for review.

**Comment by denysbutenko** [comment]
@RehanY147 docker build check has a failure

**Review by denysbutenko — CHANGES_REQUESTED** [review]
image

Test Text Field is not rendered

Errors in the console:
```
TypeError: B8[this.language] is not a function
    at Md.initEditor (ix-code-editor.component.ts:102:43)
    at Md.ngAfterViewInit (ix-code-editor.component.ts:84:10)
```

**Comment by RehanY147** [comment]
@denysbutenko Please use a recent build. The changes required are missing if you see that error.

**Review by denysbutenko — CHANGES_REQUESTED** [review]
> @denysbutenko Please use a recent build. The changes required are missing if you see that error.

Retested using the recent build  `sha256:f0063f05236ff86517c23a941bed1d0eaf2d0ebbc57057edf3bfe6cc21b280c1`, getting the same error on a fresh nightly instance.

**Comment by RehanY147** [comment]
This is an issue with the test app. It's missing the language attribute. Waiting for a new schema to test with.

**Comment by RehanY147** [comment]
@denysbutenko Use the following command to add a new catalog to your system. Then uncomment line 159 in chart-wizard.component.ts file.
```midclt call -job catalog.create '{"label": "testlang", "repository": "https://github.com/truenas/charts", "branch": "ix-test-language-field", "force": true}'```

**Review by denysbutenko — APPROVED** [review]
image

It works well

**Pull request merged**
