### PR TITLE
NAS-111625 / 21.10 / Add ensure_display_device field in the UI for vms

### PR DESCRIPTION
**Pull request by denysbutenko**

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
The checkbox is there, but once I've added a first VM search field and Add button disappeared.

**Review by undsoft — CHANGES_REQUESTED** [review]
Doesn't look like the fix fixed it. The search/Add button are still not there.

**Review by undsoft — APPROVED** [review]
It looks good now.

**Comment by denysbutenko** [comment]
Unfortunately, it shows the global actions toolbar when a system does not support virtualization. WIP

**Comment by denysbutenko** [comment]
`disableActionsConfig` must be `true` by default to prevent toolbar initialization. Once the toolbar gets initialized, we can't hide it.
There are two cases when `disableActionsConfig` should be `false`

1. the system has virtualization support
2. the system does not have `vm.virtualization_details` endpoint (old backend + new UI)

**Pull request merged**
