### PR TITLE
NAS-128840 / 24.10 / Replace `disk.query` with `webui.enclosure.dashboard` in listenForTemperatureUpdates

### PR DESCRIPTION
**Pull request by bvasilenko**
**Testing**
Verify enclosure UI for regressions

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
I should have been more broad in ticket description.
It may not be just `disk.query` that needs to be updated. 
Essentially we need to make old enclosure work with `webui.enclosure.dashboard` as much as possible. Right now it doesn't seem to be the case – no pools or disk statuses are shown in the enclosure for some reason.

**Review by RehanY147 — APPROVED** [review]

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Misclick. Tests are failing

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Still problems with Github actions. Problem with build

**Review by undsoft — APPROVED** [review]
Looks good overall. Don't worry about adding coverage to old code, just message me when you are ready to merge.

**Comment by bvasilenko** [comment]
@RehanY147 all build issues are resolved, so now it's ready for review

**Review by RehanY147 — APPROVED** [review]

**Pull request merged**
