### PR TITLE
NAS-110581 / 21.06 /List attribute does not render inside a dictionary in applications UI properly

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Comment by undsoft** [comment]
The interface looks okay, but when I try to submit, I got:
> Error: [EINVAL] attributes.externalInterfaces: Item#0 is not valid per list types: [EINVAL] interfaceConfiguration.type: Field was not expected [EINVAL] interfaceConfiguration.staticIPConfigurations: Field was not expected [EINVAL] interfaceConfiguration.staticRoutes: Field was not expected [EINVAL] ipam.type: attribute required

**Comment by Ornias1993** [comment]
@undsoft I think this might be related to another general UI issue I discovered:
When there is a dict, inside a dict, inside a list, the second dict gets ignored. 

Example code:
```
  - variable: hostPathMounts
    label: "Custom app storage"
    group: "Storage"
    schema:
      type: list
      default: []
      items:
        - variable: volumeMount
          label: "Custom Storage"
          schema:
            type: dict
            attrs:
              - variable: enabled
                label: "Enabled"
                schema:
                  type: boolean
                  default: true
                  hidden: true
                  editable: false
              - variable: setPermissions
                label: "Automatic Permissions"
                description: "Automatically set permissions on install"
                schema:
                  type: boolean
                  default: true
                  hidden: false
              - variable: readOnly
                label: "Mount as ReadOnly"
                description: "prevent any write from being done to the mounted volume"
                schema:
                  type: boolean
                  default: false
                  hidden: false
              - variable: emptyDir
                label: "EmptyDir Volume"
                schema:
                  type: dict
                  attrs:
                    - variable: enabled
                      label: "Use emptyDir volume"
                      schema:
                        type: boolean
                        default: false
                    - variable: medium
                      label: "EmptyDir Medium"
                      schema:
                        type: string
                        default: ""
                        enum:
                          - value: ""
                            description: "Default"
                          - value: "Memory"
                            description: "Memory"
              - variable: mountPath
                label: "Mount Path"
                description: "Path to mount inside the pod"
                schema:
                  type: path
                  required: true
                  default: ""
                  editable: true
              - variable: hostPath
                label: "Host Path"
                description: "Path on the host to mount inside the container, ignored when emptyDir is enabled"
                schema:
                  type: hostpath
                  required: true
```

Leads to:
```
Error: [EINVAL] attributes.hostPathMounts: Item#0 is not valid per list types: [EINVAL] volumeMount.enabled: Field is not editable. [EINVAL] volumeMount.medium: Field was not expected 
```

**Comment by AlexKarpov98** [comment]
> @undsoft I think this might be related to another general UI issue I discovered:
> When there is a dict, inside a dict, inside a list, the second dict gets ignored.
> 
> Example code:
> 
> ```
>   - variable: hostPathMounts
>     label: "Custom app storage"
>     group: "Storage"
>     schema:
>       type: list
>       default: []
>       items:
>         - variable: volumeMount
>           label: "Custom Storage"
>           schema:
>             type: dict
>             attrs:
>               - variable: enabled
>                 label: "Enabled"
>                 schema:
>                   type: boolean
>                   default: true
>                   hidden: true
>                   editable: false
>               - variable: setPermissions
>                 label: "Automatic Permissions"
>                 description: "Automatically set permissions on install"
>                 schema:
>                   type: boolean
>                   default: true
>                   hidden: false
>               - variable: readOnly
>                 label: "Mount as ReadOnly"
>                 description: "prevent any write from being done to the mounted volume"
>                 schema:
>                   type: boolean
>                   default: false
>                   hidden: false
>               - variable: emptyDir
>                 label: "EmptyDir Volume"
>                 schema:
>                   type: dict
>                   attrs:
>                     - variable: enabled
>                       label: "Use emptyDir volume"
>                       schema:
>                         type: boolean
>                         default: false
>                     - variable: medium
>                       label: "EmptyDir Medium"
>                       schema:
>                         type: string
>                         default: ""
>                         enum:
>                           - value: ""
>                             description: "Default"
>                           - value: "Memory"
>                             description: "Memory"
>               - variable: mountPath
>                 label: "Mount Path"
>                 description: "Path to mount inside the pod"
>                 schema:
>                   type: path
>                   required: true
>                   default: ""
>                   editable: true
>               - variable: hostPath
>                 label: "Host Path"
>                 description: "Path on the host to mount inside the container, ignored when emptyDir is enabled"
>                 schema:
>                   type: hostpath
>                   required: true
> ```
> 
> Leads to:
> 
> ```
> Error: [EINVAL] attributes.hostPathMounts: Item#0 is not valid per list types: [EINVAL] volumeMount.enabled: Field is not editable. [EINVAL] volumeMount.medium: Field was not expected 
> ```
> 
> Notice how this should've been parsed as:
> 
> ```
> volumeMount.emptyDir.medium
> ```
> 
> But is parsed as:
> 
> ```
> volumeMount.medium
> ```
> 
> In both cases (this PR and mine) the UI is rendered fine though...
> 
> To be clear:
> It's not related to this PR itself, This PR is solid but hit a seperate bug.
> I've filed a ticket for it though:
> https://jira.ixsystems.com/browse/NAS-110776


@undsoft Your thoughts?

**Comment by undsoft** [comment]
My thoughts is that even if this is a different issue, that different issue is kinda preventing me from testing this PR. So, we'd need to get it fixed one way or another to get this PR merged.

**Comment by AlexKarpov98** [comment]
It should work at least for the case of this ticket. More work is needed for `NAS-110776`, but on different branch.

**Review by undsoft — APPROVED** [review]
Retested - works under scenario described in the ticket.

**Pull request merged**
