### PR TITLE
NAS-110405 / 21.08 / NAS-110405 - Main menu issues on mobile

### PR DESCRIPTION
**Pull request by undsoft**
Fixes: 
- https://jira.ixsystems.com/browse/NAS-110404
- https://jira.ixsystems.com/browse/NAS-110405

Generally, not very satisfied with these 'fixes', but better refactoring is for another time.

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Still getting these weird behaviors with the menu
MENU_ISSUE2

**Comment by RehanY147** [comment]
The weird invisible menu space issue seems to be resolved. But the other issue is still present.

**Comment by undsoft** [comment]
The problem was that I didn't test on tablet resolutions. Resolved, thanks.

**Review by RehanY147 — APPROVED** [review]
Looks good

**Pull request merged**
