### PR TITLE
NAS-115340 / 22.12 / NAS-115340: Refactor OpenVPN client to ix-forms

### PR DESCRIPTION
**Pull request by bvasilenko**
Testing: 
Form is at: Network -> Click at Open VPN Client row.

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]

**Review by RehanY147 — CHANGES_REQUESTED** [review]
We're refactoring the new properties for adding links again. Unfortunately, you're going to have to make some more changes. We want simple `<a>` tags to add links and use css to style them. It's up to you how you decide to do it. But we do want links to the certificates page under all certificates fields.

**Comment by bvasilenko** [comment]
@RehanY147 Any updates on the related discussion?

**Comment by RehanY147** [comment]
@bvasilenko Yes. You can checkout the new certificates links added to certificates select on `master`. A good example is the `UI SSL Certificates` under System -> General -> UI Settings

**Review by RehanY147 — CHANGES_REQUESTED** [review]
> @bvasilenko Yes. You can checkout the new certificates links added to certificates select on master. A good example is the UI SSL Certificates under System -> General -> UI Settings

**Review by RehanY147 — APPROVED** [review]
Looks good to me. Form is submitting and values persist.

**Pull request merged**
