### PR TITLE
NAS-122966 / 23.10 / Downloading key in new pool creation

### PR DESCRIPTION
**Pull request by undsoft**
Testing: see ticket.

### CODE REVIEW

**Review by AlexKarpov98 — CHANGES_REQUESTED** [review]
Not sure why, it's not working for me.
Screenshot 2023-07-13 at 23 53 50

Error occurred while trying to proxy: localhost:4200http://headless.local:6000/_download/4803?auth_token=JXHZr_5mU-vkc9UHjAARB_PbEeChHZSP8ftJBTjY-II9ULpqnwzeSiCD9JOn7f2r

**Comment by undsoft** [comment]
I don't know. Looks like a network error. Please try again.
The only change that I've made is improved error management.

**Comment by AlexKarpov98** [comment]
@undsoft - it's not working for me :(

Screenshot 2023-07-14 at 20 34 39

Please, assign someone else as well for check.

**Review by denysbutenko — APPROVED** [review]
Works well

**Pull request merged**
