### PR TITLE
Missing translate tags

### PR DESCRIPTION
**Pull request by MDVAurelien**
Missing translate tags in syslog-card.component.html

### CODE REVIEW

**Comment by undsoft** [comment]
This is not really necessary. `syslog_server` is just a user-entered string and `syslog_transport` has values like UDP and TCP, which I assume are usually not translated.

**Comment by MDVAurelien** [comment]
it's strange because the related tools tips for these two fields doesn't work.

**Comment by undsoft** [comment]
Right. This needs to be fixed in `syslog-form.component.html` in `[tooltip]="tooltips.syslog_transport"` and others.

**Comment by MDVAurelien** [comment]
OK I'll take a look in these files

**Pull request closed without merging**
