### PR TITLE
NAS-113204 / 22.02-RC.2 / NAS-113204: Refactoring SMART service form to new ix forms

### PR DESCRIPTION
**Pull request by undsoft**

### CODE REVIEW

**Review by dszidi — COMMENTED** [review]
Code looks good to me. The tooltips need a little adjustment.

image

**Comment by undsoft** [comment]
Fixed the tooltip.

**Review by dszidi — COMMENTED** [review]
Layout seems to be borked and no errors in the browser console.

image

**Comment by undsoft** [comment]
Can you try again? I cannot reproduce and I don't know what I could have changed to alter layout this much.

**Review by dszidi — APPROVED** [review]
It was on my end. Reinstalled node modules and cleared cache. All is fine now. LGTM

image

**Pull request merged**
