### PR TITLE
NAS-109267 / 21.02 / After upgrading chart release UI does not show updated version of app / NAS-109267

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Review by sonicaj — COMMENTED** [review]
We should update the information for the whole app tile basically, it's possible it starts consuming different ports or using different images etc.

**Review by sonicaj — COMMENTED** [review]
We should be showing protocol as lowercase, api returns them upper case.

How about we have common logic for rendering the app component and then use that one here and the normal rendering one as well when we show apps ? ( just a recommendation :P )

**Comment by AlexKarpov98** [comment]
We are using filter for lowercase in rendering part so don't have to worry about it.

**Review by sonicaj — APPROVED** [review]

**Review by Ornias1993 — APPROVED** [review]
Looks good, clean code, simple improvement
LGTM

**Review by dszidi — APPROVED** [review]
lgtm

**Pull request merged**
