### PR TITLE
NAS-128844 / 24.10 / Use new icon to represent datasets

### PR DESCRIPTION
**Pull request by denysbutenko**
Visit the Datasets page to see the changes. The original icon was renamed `dataset_root,` and a new dataset icon was added.

Demo:
image

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
1. It's too large. It should be roughly the same size as zvol or dataset_root icon.
2. It should be updated in ix-explorer.

**Review by bvasilenko — APPROVED** [review]
Looks good! 
New icon is displayed where it's expected to display

**Comment by denysbutenko** [comment]
> 1. It's too large. It should be roughly the same size as zvol or dataset_root icon.

Okay done
image


> 2. It should be updated in ix-explorer.

`ix-explorer` uses three folder icons: `folder`, `folder_open`, and `mdi-folder-lock`. I've replaced folder icon for now. 

image

**Comment by denysbutenko** [comment]
Looking into reasons for test failing.

**Review by undsoft — APPROVED** [review]
New icon looks good.

**Pull request merged**
