### PR TITLE
NAS-122353 / 23.10 / Improve loading state for available apps header

### PR DESCRIPTION
**Pull request by denysbutenko**
image

For testing, check available apps header

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
The problem with new solution is that it shows loading animation for numbers every time you change something in filters.

**Comment by denysbutenko** [comment]
> The problem with new solution is that it shows loading animation for numbers every time you change something in filters.

True. With recent changes, there is no needed loader for those numbers - initial values are present from the beginning. I'll code clean up at least.

**Comment by denysbutenko** [comment]
As discussed, I added an internal loader that works the first time only. The loading state is visible when a user is directly loading the available apps page in other cases numbers are ready, and the loading state won't appear.

**Review by undsoft — APPROVED** [review]
Looks good.

**Pull request merged**
