### PR TITLE
Update zh-hans.json

### PR DESCRIPTION
**Pull request by Sagit-chu**
Modify the translation of 'scrub' to make it more intuitive

### CODE REVIEW

**Review by RehanY147 — APPROVED** [review]
Looks good

**Comment by RehanY147** [comment]
@Sagit-chu please resolve the conflicts with master

**Review by undsoft — APPROVED** [review]
Thanks!

**Review by RehanY147 — APPROVED** [review]
Looks good

**Comment by undsoft** [comment]
I had to revert one of the strings, because it was malformed.
```
<strong>后面的{n，复数，一个{快照}或一些{#快照}}将被删除。 您确定要继续吗？</strong>
```
Commas were of a different kind and tokens like `plural`, `one` or `other` do not need to be translated. They are there to allow translators to use language specific rules for pluralization: https://lokalise.com/blog/complete-guide-to-icu-message-format/#Pluralization

Strings can be tested here:
http://format-message.github.io/icu-message-format-for-translators/editor.html

[It sounds like in Chinese](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html), the form of word does not change based on count.
In this case you can do something like:
```
<strong>后面的{n, plural, other{#快照}}将被删除。 您确定要继续吗？</strong>
```

**Comment by Sagit-chu** [comment]
> I had to revert one of the strings, because it was malformed.
> 
> ```
> <strong>后面的{n，复数，一个{快照}或一些{#快照}}将被删除。 您确定要继续吗？</strong>
> ```
> 
> Commas were of a different kind and tokens like `plural`, `one` or `other` do not need to be translated. They are there to allow translators to use language specific rules for pluralization: https://lokalise.com/blog/complete-guide-to-icu-message-format/#Pluralization
> 
> Strings can be tested here:
> http://format-message.github.io/icu-message-format-for-translators/editor.html
> 
> [It sounds like in Chinese](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html), the form of word does not change based on count.
> In this case you can do something like:
> 
> ```
> <strong>后面的{n, plural, other{#快照}}将被删除。 您确定要继续吗？</strong>
> ```

OK

**Pull request merged**
