### PR TITLE
NAS-119180 / 23.10 / Designs for allowing users to manage ACL presets + Improvements

### PR DESCRIPTION
**Pull request by bvasilenko**
**Testing:**

Open ACL editor and test that it works

### CODE REVIEW

**Review by denysbutenko — CHANGES_REQUESTED** [review]
Waiting for a successful build

**Comment by bvasilenko** [comment]
@denysbutenko build is fixed now

**Review by denysbutenko — APPROVED** [review]
Looks good

**Comment by bvasilenko** [comment]
Just pushed an adjustment in a separate PR: https://github.com/truenas/webui/pull/7499

**Pull request merged**
