### PR TITLE
NAS-120268 / 23.10 / Show description for PCI passthrough devices choices

### PR DESCRIPTION
**Pull request by Raz-Dva**
Go to Virtualization -> choose virtual machine -> Devices -> Add -> choose  Type PCI Passthrough Device - >PCI Passthrough Device

image

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
We shouldn't pollute the DropDown options list. Instead, it would be better to show the description in a tooltip. Maybe show an info (i) icon next to the option to indicate that there's more information to be seen about this option.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
The Add device button only shows up on this PR and not on master.

**Review by RehanY147 — COMMENTED** [review]
What's a machine I can test this on?

**Review by RehanY147 — APPROVED** [review]

**Comment by Raz-Dva** [comment]
> What's a machine I can test this on?

You can create a new VM on m40g

**Pull request merged**
