### PR TITLE
NAS-121249 / 22.12.3 / Fix update and removal in stores

### PR DESCRIPTION
**Pull request by bvasilenko**
**Testing**

See original PR: https://github.com/truenas/webui/pull/8016

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
I get
```
instrument.js:109 TypeError: Cannot read properties of undefined (reading 'id')
    at alert.reducer.ts:50:15
```
when I dismiss an alert using one of the Bluefin machine from Jenkins.

**Comment by bvasilenko** [comment]
@undsoft Now the bug should be fixed

**Review by undsoft — CHANGES_REQUESTED** [review]
Deleting a user or a group does not refresh the table.

**Comment by bvasilenko** [comment]
@undsoft Ok, now it should be fixed

**Review by undsoft — CHANGES_REQUESTED** [review]
I get
```
TypeError: Cannot read properties of undefined (reading 'name')
    at snapshot.reducer.ts:35:18
```
when I attempt to delete a snapshot.

**Comment by bvasilenko** [comment]
@undsoft 

I kindly apologize for back and forth.

After thorough testing on bluefin version of the middleware, it turned out that none of the fixes made here are applicable to the bluefin: when deleting, middleware responds with 2 messages - `removed` and `changed` with the `cleared` field (which is obsolete in post-bluefin versions)

So no need to backport these... I'm closing this PR now.

**Pull request closed without merging**
