### PR TITLE
NAS-131073 / 25.04 / Add apps widgets back

### PR DESCRIPTION
**Pull request by denysbutenko**
**Changes:**

Apps widgets were hidden for EE release. This PR brings them back for FG.

**Testing:**

Add app widgets to the main dashboard and test in various scenarios.

### Downstream

|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   | New widgets added

### CODE REVIEW

**Review by AlexKarpov98 — COMMENTED** [review]
I've tested it and found a bug, which is possibly not related to this ticket -- https://ixsystems.atlassian.net/browse/NAS-131219 (new ticket created)

As well I see that statuses are not real time, see:

https://github.com/user-attachments/assets/e760ac4c-769c-4d4c-b620-b0d72e3bda79

**Comment by denysbutenko** [comment]
Known issue is that app shows `Crashed` status for a while - it's coming from middleware.

**Review by AlexKarpov98 — APPROVED** [review]
Now statuses are updating real time.

BTW - is that ok to show `vv0.107.52` ? (double `v`)
Screenshot 2024-09-18 at 20 05 43

**Comment by denysbutenko** [comment]
> Now statuses are updating real time.
> 
> BTW - is that ok to show `vv0.107.52` ? (double `v`) Screenshot 2024-09-18 at 20 05 43

This is the app-related issue since `v` is included in the version. I'll add an extra check for this case.

**Pull request merged**
