### PR TITLE
NAS-125191 / 24.04 / SCALE Certificates UI does not show saved "Renew Certificate Days Before Expiry" values

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: see ticket

### CODE REVIEW

**Review by dszidi — COMMENTED** [review]
Checking against the team's M40, I see no renew field on editing the existing cert.

image


image

**Comment by AlexKarpov98** [comment]
@dszidi it's there, but on save I get an error:
Screenshot 2023-11-21 at 18 11 24

**Review by dszidi — APPROVED** [review]
Ok, after that last pull, the field is now present and validation is working. LGTM

image

**Review by dszidi — COMMENTED** [review]
Wrt the validation error, the field should be hidden on certs that don't support renew time should it not? User probably shouldn't be seeing a validation error here

**Comment by AlexKarpov98** [comment]
@dszidi - I talked to @sonicaj about the ACME cert, the actual value will be:
```
    "renew_days": 10,
    "revoked_date": null,
    "signedby": null,
    "acme": {
      "id": 2,
      "uri": "https://acme-v02.api.letsencrypt.org/acme/acct/101330433",
      "directory": "https://acme-v02.api.letsencrypt.org/directory/",
      "tos": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
      "new_account_uri": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
      "new_nonce_uri": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
      "new_order_uri": "https://acme-v02.api.letsencrypt.org/acme/new-order",
      "revoke_cert_uri": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
    },
```

So, our code will work and only show `RENEW_DAYS` only for ACME certificate and prefill it with data if available.

**Review by dszidi — APPROVED** [review]
LGTM

**Pull request merged**
