### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by renediepenbroek**
Checked my updated NL-translation with TrueNAS-Scale-22.12.0 as far as I could...

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
Eh, `truenas scale bluefin - versie 7` needs to be deleted from `i18n`. Not sure how it got there.
As for translation file, it should go be called `nl.json` and should be located within `i18n` directory.

**Comment by undsoft** [comment]
@renediepenbroek I've merged the translations. Due to conflicts I had to merge some strings manually, hopefully I picked the correct version.

**Comment by renediepenbroek** [comment]
Hello Evgeny,

On March 14, you sent me an email regarding my Dutch translation for 
TrueNAS. Thanks for this!

However, I have the following question for you because translating into 
Dutch as it should be done now is a frustrating thing in my opinion. If 
I have made an adjustment because I see a typing error, for example, 
then I do not have to check it further in principle, but if I have to 
make a contextual adjustment (for example: 'copy' in English has 2 
'solutions' in Dutch: it can either be a verb (kopiëren) or a noun 
(kopie)) and then it gets tricky because I can't (quickly) check the 
effect/context of my translation.

I therefore have the following request for you:
• Where can I put my translated NL file (in json-notation or another 
format?) in the TrueNAS file/folder system so I am able to quickly check 
my corrections myself?
• Do specific file(s) need to be modified for this? I'm thinking of 
certain *.ini files?

If I can work in this way, a solid piece of translation work will be 
ready for TrueNAS in a very short period of time, which, I hope, will 
then be used by a large number of Dutch-speaking users of TrueNAS  (in 
the Netherlands and Belgium). After checking the correct context, I will 
prepare the NL.json-file for you in Github.
I await your response with interest and thank you in advance!

Sincerely,

René Diepenbroek


------ Oorspronkelijke bericht ------
Van "Evgeny Stepanovych" ***@***.***>
Aan "truenas/webui" ***@***.***>
CC "René" ***@***.***>; "Mention" 
***@***.***>
Datum 14-2-2023 15:20:32
Onderwerp Re: [truenas/webui] Add files via upload (PR #7595)

**Comment by undsoft** [comment]
@renediepenbroek 
Yes, you can go to /usr/share/truenas/webui/assets/i18n on your truenas instance and edit corresponding file.
You will need to refresh page to see changes. It may be a good idea to open inspector in Chrome to disable cache.

As to the fact that the same string can be translated in two different ways, unfortunately that is a problem with our translation system right now. It is entirely possible that the same English is used in two different places with different meaning.

**Pull request merged**
