### PR TITLE
NAS-123838 / 24.10 / F100.png image backported to Electric Eel

### PR DESCRIPTION
**Pull request by bvasilenko**
**Summary**

This is backported image for ES24N to match existing logic of building image URLs at `ProductImageService`, as was requested here: https://github.com/truenas/webui/pull/9783#pullrequestreview-1927504996

**Testing**

1. Connect to the machine mentioned in the NAS-123838 ticket
2.  Examine the **System Information** widget at **Dashboard**  page
  - **Expected result:** image from this PR is shown in this widget

### CODE REVIEW

**Review by AlexKarpov98 — COMMENTED** [review]
@bvasilenko - machine from the ticket is not working for me `f60-141`

**Comment by AlexKarpov98** [comment]
I don't see this change backported as well:

Screenshot 2024-03-13 at 14 18 01

**Comment by bvasilenko** [comment]
Changes on the screenshot is not needed. But on the Enclosure page, without them, a message appears saying that the device is not supported. 

Originally, there was a request from @undsoft to only port the image for the dashboard. 

@undsoft  Is it really necessary to port changes to the Electric Eel that affect the Dashboard but do not affect the Enclosure?

**Review by undsoft — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
