### PR TITLE
NAS-115951 / 22.12 / Nas 115951 Add linter for component selectors

### PR DESCRIPTION
**Pull request by Raz-Dva**
Check functionality after changing selectors

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
There are still selectors that don't follow this rule

**Comment by RehanY147** [comment]
I see that other PRs handle some of the selector renaming as well. Gonna review it again.

**Review by RehanY147 — APPROVED** [review]
The UI seems to be working OK. No compilation errors.

**Comment by Raz-Dva** [comment]
> 
I plan to complete this task in a few PR

**Pull request merged**
