### PR TITLE
NAS-125605 / 24.10 / Do not reload system.info every 30 seconds

### PR DESCRIPTION
**Pull request by denysbutenko**
For testing, ensure uptime values are still updating on the system information widgets.

### CODE REVIEW

**Review by AlexKarpov98 — COMMENTED** [review]
@undsoft named ticket: `Do not reload system.info every 30 seconds`
@denysbutenko - you did that it now updates every 5 seconds 😄 

So what's the correct behaviour? Shall we remove at all that interval?

**Comment by undsoft** [comment]
Auto-ddos. We shouldn't send recurring requests to middleware.

**Comment by denysbutenko** [comment]
> @undsoft named ticket: `Do not reload system.info every 30 seconds` @denysbutenko - you did that it now updates every 5 seconds 😄
> 
> So what's the correct behaviour? Shall we remove at all that interval?

I'll try to explain the difference. The problem is when we call `system.info` in the global scope of the app store, it causes an issue described in https://ixsystems.atlassian.net/browse/NAS-125603. Now, it is moved to widget scope and works similarly to a network widget where data is updated with a short delay.

**Comment by denysbutenko** [comment]
> Auto-ddos. We shouldn't send recurring requests to middleware.

Okay, we can switch back to the internal counter implementation again because necessary information is available in a single query.

**Review by AlexKarpov98 — CHANGES_REQUESTED** [review]
Interval is not stopped when component is destroyed.
see:

https://github.com/truenas/webui/assets/22980553/32382cc5-3366-49d9-b78e-ac4d900666a8

**Review by AlexKarpov98 — APPROVED** [review]
Works fine and interval is cleared once component is destroyed.

**Pull request merged**
