### PR TITLE
NAS-110583 / 21.08 / Render ix-chart dynamically in the UI

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Comment by denysbutenko** [comment]
How to test this change?

**Comment by AlexKarpov98** [comment]
You can add a new catalog to test this - URI to use will be "https://github.com/truenas/charts" and branch would be "test-ix-chart" and the application name would be "test-ix-chart" as well.

**Comment by AlexKarpov98** [comment]
> You can add a new catalog to test this - URI to use will be "https://github.com/truenas/charts" and branch would be "test-ix-chart" and the application name would be "test-ix-chart" as well.

So once you followed this steps, you should see `ix-chart` application like below.
Then you can test if you can successfully install it.
image

**Review by RehanY147 — APPROVED** [review]
LGTM. Chart is loading.

**Comment by sonicaj** [comment]
@AlexKarpov98 we are not rendering the wizard being shown by "Launch Docker Image" dynamically - it is still static. I am not sure i follow the change ?

**Pull request merged**
