### PR TITLE
NAS-127514 / 24.10 / Improve codebase for dashboard widgets

### PR DESCRIPTION
**Pull request by denysbutenko**
Changes:

- Fixed Storage widget on mobile
- Some optimizations
- Code cleanup
- Add basic unit tests

For testing, look for regressions.

### CODE REVIEW

**Comment by AlexKarpov98** [comment]
@denysbutenko - please fix conflicts first, to release statuses checks.
A lot of changes, huh 😄

**Comment by AlexKarpov98** [comment]
@denysbutenko 
some weird `TRUE` on the Configure Form.
Screenshot 2024-03-20 at 12 27 28

**Comment by AlexKarpov98** [comment]
@denysbutenko 
When I click UPDATES AVAILABLE -> nothing happens. (m40)
https://github.com/truenas/webui/assets/22980553/9ab21082-e0ca-4ab1-83a9-8a9e92a83c5e

**Comment by AlexKarpov98** [comment]
@denysbutenko 
Screenshot 2024-03-20 at 12 32 16

**Comment by denysbutenko** [comment]
> @denysbutenko (m40) hmm, I configured to Hide and Show `System Information` Now the issue seems to gone... weird Screenshot 2024-03-20 at 12 32 16

@AlexKarpov98 The `true` toggle and this are related issues—it was already fixed in https://github.com/truenas/webui/pull/9733. Perhaps there are some leftovers in user dashState.

**Review by AlexKarpov98 — APPROVED** [review]
A lot of changes.
I was not able to find any regressions.
It works well for me - good job.

**Pull request merged**
