### PR TITLE
NAS-118007 / 22.12 / NAS-118007: Removing BaseService

### PR DESCRIPTION
**Pull request by undsoft**
1. Removes resilvering indication on top bar.
2. Fixes temperatures in enclosure management on Minis.

### CODE REVIEW

**Review by dszidi — CHANGES_REQUESTED** [review]
Confirmed with support, we really should keep the resilver prominent despite the fact that the task manager might also show resilver progress.

**Comment by undsoft** [comment]
Brought resilvering indication back.

**Review by dszidi — CHANGES_REQUESTED** [review]
Looks good. It does take a few seconds to get initial temperature readings. It would be good if that spinner stuck around until the temperatures are shown to the user. Then if there is a problem, put an error message in the empty space.

**Comment by undsoft** [comment]
Changed the code a little bit to make first query immediately.

**Review by dszidi — APPROVED** [review]
LGTM

**Pull request merged**
