### PR TITLE
NAS-116263 / 22.12 / NAS-116263: Refactoring idmap form

### PR DESCRIPTION
**Pull request by undsoft**
1. Go to Credentials -> Directory Services and enable Active Directory. Use instructions [here](https://confluence.ixsystems.com/display/QE/Directory+Servers+and+other+resources+for+testing).
2. Add and edit idmap.

Known changes:
- Order of fields in the form.
- When creating an idmap, there are now fewer options for name field.
- When editing an idmap, name can no longer be edited.

### CODE REVIEW

**Comment by AlexKarpov98** [comment]
Shows blank slide dialog if click `Add` button in Idmap list
image

Screenshot_35

**Comment by AlexKarpov98** [comment]
When click the 'Manage Certificates' link in the idmap edit it redirects to the certificates page but gives an endless load dialog.

image
image

**Comment by AlexKarpov98** [comment]
'Clearing Cache...' dialog remains after the cache is cleared.

Screenshot_52
Screenshot_50
Screenshot_51

**Comment by AlexKarpov98** [comment]
I think it would be better to create a new 'idmap-form' folder and put it.
image

**Review by AlexKarpov98 — CHANGES_REQUESTED** [review]

**Comment by undsoft** [comment]
Good comments. Fixed.

**Review by AlexKarpov98 — APPROVED** [review]
LGTM! 👍

**Pull request merged**
