### PR TITLE
NAS-110863 / 21.08 / Adjusted height

### PR DESCRIPTION
**Pull request by RehanY147**
NAS-110863

### CODE REVIEW

**Comment by denysbutenko** [comment]
Looks like a magic number. Can we try to find better approach to solve this? For example something like "$header-height: n; height: calc(100% - $header-height)"?

**Comment by denysbutenko** [comment]
image
In this case, it would be:
```
$page-title-height: 97px;
height: calc(100% - $page-title-height);
```

**Review by denysbutenko — APPROVED** [review]

**Comment by RehanY147** [comment]
@denysbutenko Made the suggested changes. Thanks! Please review again

**Review by denysbutenko — APPROVED** [review]
image
Looks good 👍🏻

**Pull request merged**
