### PR TITLE
NAS-122674 / 23.10 / Do not put tooltip icons in select options

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Ticket description:
Screenshot 2023-06-28 at 13 55 29

Result:
Screenshot 2023-06-28 at 13 56 00

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
1. I don't think it's a good idea to remove this functionality completely. Tooltips in selects are still used in certificate forms. 
Снимок экрана 2023-06-28 в 15 30 55
Instead it's worth checking why removing `tooltip` field from the interface didn't produce compilation errors.

2. Until we have a better way of working with help, we should show layout descriptions in tooltip next to Layout select.

**Comment by undsoft** [comment]
I don't know if @dszidi would approve of this approach. If we decide to keep tootips, they need to appear on the left or right not below as to not interfere with user selecting items.
Снимок экрана 2023-06-30 в 11 37 01

**Comment by AlexKarpov98** [comment]
@undsoft - make sense --> updated.
Screenshot 2023-06-30 at 13 17 52

**Review by dszidi — APPROVED** [review]
Tooltips on the right work well.

image

**Comment by AlexKarpov98** [comment]
@undsoft - waiting for your approve.

**Review by undsoft — APPROVED** [review]
Yup, looks good.

**Pull request merged**
