### PR TITLE
NAS-129885 / 24.10 / Add customer designed login banner 

### PR DESCRIPTION
**Pull request by denysbutenko**
Ready for testing. Unit tests in progress.

Note: Ensure you have the latest middleware

Demo:
image

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
I am using the latest build. If I am not already logged in, the sign in page never shows up.

**Comment by denysbutenko** [comment]
> I am using the latest build. If I am not already logged in, the sign in page never shows up.

@RehanY147 have you seen any errors in console?

**Review by RehanY147 — CHANGES_REQUESTED** [review]
When the dialog shows up with the login banner, you can't click the "Continue" button if you click on the text part of it. You can click it on the empty part of the button only which is weird since the text is in the center and that's where the user is likely to click.

Also, I only see the login banner when I log out. When I first come to the UI with a page refresh, I don't see the login banner. See the video. 

https://github.com/user-attachments/assets/90f73d6a-37d6-426e-b657-6f28d42037f7

**Comment by denysbutenko** [comment]
> When the dialog shows up with the login banner, you can't click the "Continue" button if you click on the text part of it. You can click it on the empty part of the button only which is weird since the text is in the center and that's where the user is likely to click.

I tested it on Firefox 128, Chrome 126, and Safari, but I can't reproduce the problem on my end. Did you experience the same problem with other buttons?

> Also, I only see the login banner when I log out. When I first come to the UI with a page refresh, I don't see the login banner. See the video.
> 
>  Screen.Recording.2024-07-17.at.4.45.33.AM.mov

Okay fixed this case

**Review by RehanY147 — COMMENTED** [review]
I can consistently reproduce the button bug. It doesn't happen for me on other buttons. Only this one. @undsoft Can you review if you can get this error as well?

**Review by RehanY147 — CHANGES_REQUESTED** [review]
I can still reproduce the page refresh bug with the latest changes pulled in and on firfox up to date.

https://github.com/user-attachments/assets/1030b1cd-1e30-4e2c-ba4f-c17491bd752e

**Comment by denysbutenko** [comment]
> I can still reproduce the page refresh bug with the latest changes pulled in and on firfox up to date.
> 
>  Screen.Recording.2024-07-18.at.4.30.12.AM.mov

Ah, I see now. It is another case. Made changes for it.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
The missing banner on refresh after logout bug has been resolved. I still see the unclickable text on the continue button issue. If you want, you can create a new ticket for this and link it here. I will approve this PR.

**Comment by denysbutenko** [comment]
> The missing banner on refresh after logout bug has been resolved. I still see the unclickable text on the continue button issue. If you want, you can create a new ticket for this and link it here. I will approve this PR.

Let's try to resolve it here. I assume it may be a z-index issue. In the past, we had a problem with password input overlapped popups. Can you check the selected element under the text button with `Inspect Element`? It may help to understand the root cause.


https://github.com/user-attachments/assets/a6fe1528-7e14-47da-addc-d3377a97df99

**Review by RehanY147 — CHANGES_REQUESTED** [review]
There is a some sort of cdk layout on top of the button. That's stopping it from being clickable. I've also tested this in incognito to confirm that no extension or plugins are messing with the UI and I could reproduce it.

**Comment by RehanY147** [comment]
https://github.com/user-attachments/assets/1d57d1cd-9deb-4a8f-8312-a8d963a6ee0f

**Comment by denysbutenko** [comment]
> There is a some sort of cdk layout on top of the button. That's stopping it from being clickable. I've also tested this in incognito to confirm that no extension or plugins are messing with the UI and I could reproduce it.

Autofocus directive intercepts active element to input that enables autocomplete. I added two possible fixes:

1. Increased z-index for full-screen dialog than input's autocomplete.
2. Skip autofocus when full-screen dialog appears and restore on username input when dialog is closed.

**Review by RehanY147 — APPROVED** [review]
Seems to be working OK now. No longer see the issues. Great work!

**Pull request merged**
