### PR TITLE
NAS-111919 / 21.10 / NAS-111919: Use primary color for checkboxes 

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Comment by denysbutenko** [comment]
background is not applied here:
image
also, some checkboxes have a mixed appearance
image

**Comment by denysbutenko** [comment]
Can we use `cursor: not-allowed` on disabled checkboxes?

**Comment by denysbutenko** [comment]
On light themes: 
The checkbox looks unchecked but there invisible mark
image

**Comment by AlexKarpov98** [comment]
@denysbutenko fixed.

**Review by denysbutenko — APPROVED** [review]
image
image

Looks good to me 👍🏻

**Pull request merged**
