### PR TITLE
NAS-119552 / 23.10 / Migrate mat-dialog to MDC

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
The following dialogs do not look good:
1.  Top bar -> Truecommand
2. Top bar -> Truecommand -> connect
3. Storage -> Unassigned disks -> Add to Pool.

There may be others, those are the ones I've tested.

**Comment by AlexKarpov98** [comment]
@undsoft - Fixed these issues and checked other modals (rechecked)

**Review by undsoft — CHANGES_REQUESTED** [review]
At least following dialogs look broken:
* User menu -> About.
* System Settings -> Cron Job -> Add -> Schedule -> Custom.
* Trucommand -> Connect (there is now a scrollbar on macos when mouse is connected).

**Review by undsoft — CHANGES_REQUESTED** [review]
When job is running, minimize icon needs to be on top.
Снимок экрана 2022-12-28 в 10 29 24

When creating an encrypted pool, buttons are weird (rounded corners on one and no background on another).
Снимок экрана 2022-12-28 в 10 30 05

**Review by undsoft — APPROVED** [review]
Looks good.

**Pull request merged**
