### PR TITLE
NAS-113671 / 22.02 / Remove support for showing console on loading indicator

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Review by dszidi — COMMENTED** [review]
Apologies but I'm not quite sure how to test this. Could you provide testing instructions please.

**Comment by AlexKarpov98** [comment]
> Apologies but I'm not quite sure how to test this. Could you provide testing instructions please.

I am sorry.
To test:
Need to try changing the code to see `AppLoader` that would disappeared quickly

Line 50 in src\app\pages\services\components\service-rsync\rsync-configure\rsync-configure.component.ts
```
  ngOnInit(): void {
    this.loader.open();

    this.ws.call('rsyncd.config').pipe(untilDestroyed(this)).subscribe(
      (config: RsyncConfigUpdate) => {
        this.form.patchValue(config);
        // this.loader.close();
        this.cdr.markForCheck();
      },
      (error) => {
        // this.loader.close();
        new EntityUtils().handleWsError(null, error, this.dialogService);
      },
    );
  }
```
Please prevent to close the loader like line 56, 60,
then could see the app loader permanently in the page System Setting -> Services -> Rsync

**Comment by AlexKarpov98** [comment]
Before:
image

After:
image

**Review by dszidi — APPROVED** [review]
LGTM

image

**Pull request merged**
