### PR TITLE
NAS-123588 / 24.04 / Resending the request with additional attribute on error

### PR DESCRIPTION
**Pull request by RehanY147**

### CODE REVIEW

**Review by denysbutenko — CHANGES_REQUESTED** [review]
Need instructions on how to test this.

**Comment by RehanY147** [comment]
@denysbutenko Try setting up a connection with https://localhost/

**Review by denysbutenko — CHANGES_REQUESTED** [review]
The SSH connection can't be created when it raises an SSL error. Tested with `TrueNAS-SCALE-24.04-MASTER-20230827-024250`.

https://github.com/truenas/webui/assets/351613/5333278c-b996-40e3-9bb5-b53513ddf7d1

**Review by denysbutenko — APPROVED** [review]
image

Works well.

**Pull request merged**
