### PR TITLE
NAS-111136 / 21.08 / Finnish notation

### PR DESCRIPTION
**Pull request by undsoft**
Don't know how to test this, besides doing general regression testing in random places.

### CODE REVIEW

**Review by RehanY147 — COMMENTED** [review]
The `Apps` page seems to have the following issues
- The `Installed Apps` tab stays in the loading state. The loader/spinner never goes away
- When installing an app, the form submission returns an error similar to `Expected an object or string` or something like that

Haven't found any other issues

**Comment by undsoft** [comment]
@RehanY147 Please take a look again. I couldn't reproduce. Either the issue got resolved when I merged master, or maybe it was something else.

**Comment by undsoft** [comment]
@RehanY147 🙏

**Review by RehanY147 — APPROVED** [review]
LGTM

**Pull request merged**
