### PR TITLE
NAS-124231 / 24.04 / Add `Create New` option for Cloud Credentials

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: see ticket

Result:

https://github.com/truenas/webui/assets/22980553/f7d009dd-1845-48ac-be23-5ca2739e5685

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
This PR seems to be in conflict with https://github.com/truenas/webui/pull/9094. The other PR is replacing the form with a wizard and adding ways to add new providers. Discuss with @denysbutenko please.

**Comment by AlexKarpov98** [comment]
@RehanY147 - @denysbutenko told me:
`
Cloud Credentials form is still in use despite adding Cloudsync Wizard. Wizard also have Create New option to add new credential although it renders the cloud credentials form below the credentials select. I am not sure if this way suitable for the form. so I think there is no conflict between PRs.
`

**Review by RehanY147 — CHANGES_REQUESTED** [review]
This is too impactful of a change to accommodate one small form. I think we should just open another slide in form instead of changing the ix-modal-header, meant for ix-slide-ins, to handle dialogs. Plus, as a team preference, we don't want to show forms in dialogs.

**Comment by AlexKarpov98** [comment]
> This is too impactful of a change to accommodate one small form. I think we should just open another slide in form instead of changing the ix-modal-header, meant for ix-slide-ins, to handle dialogs. Plus, as a team preference, we don't want to show forms in dialogs.

@RehanY147 - then I can close this PR?

**Comment by RehanY147** [comment]
@AlexKarpov98 I think so. Instead of opening the form in a dialog, let's use a slide-in to open this form. Or use the new `IxChainedSlideInService`

**Review by RehanY147 — COMMENTED** [review]
^

**Comment by AlexKarpov98** [comment]
Instead of opening the form in a dialog, let's use a slide-in to open this form. Or use the new IxChainedSlideInService

**Pull request closed without merging**
