### PR TITLE
NAS-125093 / 24.04 / Similar tickets in Feedback dialog

### PR DESCRIPTION
**Pull request by denysbutenko**
Based on https://github.com/truenas/webui/pull/9324 ~and blocked by https://github.com/truenas/middleware/pull/12699~

For testing, use the latest nightly build.

Alternatively, you can use mock for `support.similar_issues` endpoint.

```
midclt call test.set_mock support.similar_issues '[]' '{"return_value":[{"url":"https://ixsystems.atlassian.net/browse/NAS-125093","id":87844,"key":"NAS-125093","keyHtml":"NAS-125093","img":"/rest/api/2/universal_avatar/view/type/issuetype/avatar/10311?size=medium","summary":"<b>Similar</b> tickets screen","summaryText":"Similar tickets screen"},{"url":"https://ixsystems.atlassian.net/browse/NAS-122608","id":79257,"key":"NAS-122608","keyHtml":"NAS-122608","img":"/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium","summary":"Figure out a max limit for <b>similar</b> apps on the UI","summaryText":"Figure out a max limit for similar apps on the UI"},{"url":"https://ixsystems.atlassian.net/browse/NAS-121981","id":77378,"key":"NAS-121981","keyHtml":"NAS-121981","img":"/rest/api/2/universal_avatar/view/type/issuetype/avatar/10308?size=medium","summary":"Add <b>similar</b>ity score for retrieving <b>similar</b> apps","summaryText":"Add similarity score for retrieving similar apps"},{"url":"https://ixsystems.atlassian.net/browse/NAS-121950","id":77215,"key":"NAS-121950","keyHtml":"NAS-121950","img":"/rest/api/2/universal_avatar/view/type/issuetype/avatar/10311?size=medium","summary":"Improvements to <b>similar</b> apps","summaryText":"Improvements to similar apps"},{"url":"https://ixsystems.atlassian.net/browse/NAS-121562","id":75489,"key":"NAS-121562","keyHtml":"NAS-121562","img":"/rest/api/2/universal_avatar/view/type/issuetype/avatar/10311?size=medium","summary":"Add endpoint to retrieve <b>similar</b> apps","summaryText":"Add endpoint to retrieve similar apps"},{"url":"https://ixsystems.atlassian.net/browse/NAS-121484","id":75191,"key":"NAS-121484","keyHtml":"NAS-121484","img":"/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium","summary":"<b>Similar</b> Apps Navigation is not working","summaryText":"Similar Apps Navigation is not working"},{"url":"https://ixsystems.atlassian.net/browse/NAS-120377","id":71041,"key":"NAS-120377","keyHtml":"NAS-120377","img":"/rest/api/2/universal_avatar/view/type/issuetype/avatar/10310?size=medium","summary":"Extract <b>similar</b> Manage Certificates code","summaryText":"Extract similar Manage Certificates code"},{"url":"https://ixsystems.atlassian.net/browse/NAS-120285","id":70573,"key":"NAS-120285","keyHtml":"NAS-120285","img":"/rest/api/2/universal_avatar/view/type/issuetype/avatar/10311?size=medium","summary":"Implement API endpoint for <b>similar</b> apps","summaryText":"Implement API endpoint for similar apps"},{"url":"https://ixsystems.atlassian.net/browse/NAS-120107","id":69799,"key":"NAS-120107","keyHtml":"NAS-120107","img":"/rest/api/2/universal_avatar/view/type/issuetype/avatar/10311?size=medium","summary":"Implement <b>Similar</b> Apps for the App Detail View","summaryText":"Implement Similar Apps for the App Detail View"}]}'```

### CODE REVIEW

**Review by AlexKarpov98 — CHANGES_REQUESTED** [review]
@denysbutenko - please remove draft status and request review once it is ready.

**Review by AlexKarpov98 — COMMENTED** [review]
I like how it works so far, good job 🔋 

Some improvements I'd like to see listed below 👇 

On Designs, list looks good, has spacing.
Screenshot 2024-01-05 at 13 14 49

We have a little of spacing:
Screenshot 2024-01-05 at 13 14 53

Once I clear input or press `X` - similar issues are still shown, maybe we can hide them if user clears an input?
Screenshot 2024-01-05 at 13 17 28

**Comment by AlexKarpov98** [comment]
@denysbutenko - as well, please fix tests.
Screenshot 2024-01-05 at 13 20 59

**Comment by denysbutenko** [comment]
Thanks for the feedback, @AlexKarpov98

Here is demo of updated version:

https://github.com/truenas/webui/assets/351613/a0449680-52b0-42df-b913-58b4ebee304b

**Review by AlexKarpov98 — APPROVED** [review]
Looks and works nicely 👍 
A little improvement may be - add loading indicator?

**Pull request merged**
