### PR TITLE
NAS-115973 / 22.12 / Terminal UI improvements

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing:
System Settings -> Shell

### CODE REVIEW

**Review by RehanY147 — APPROVED** [review]
@AlexKarpov98 Can you specify what to test for on the UI?

**Review by RehanY147 — CHANGES_REQUESTED** [review]
@AlexKarpov98 What I said above. Approved by mistake.

**Review by undsoft — APPROVED** [review]
Nice work.

Снимок экрана 2022-05-02 в 20 50 23

**Comment by AlexKarpov98** [comment]
> @AlexKarpov98 Can you specify what to test for on the UI?
shell
Please check selectable and editable.

**Pull request merged**
