### PR TITLE
NAS-115420 / 22.02.1 / NAS-115420: Added protections

### PR DESCRIPTION
**Pull request by RehanY147**
Added some lacking `else` conditions that might have caused this

### CODE REVIEW

**Review by denysbutenko — APPROVED** [review]
Looks good

**Comment by undsoft** [comment]
backport

**Comment by themylogin** [comment]
backport

**Comment by RehanY147** [comment]
@undsoft @themylogin What is the backport status on this PR? Did we backport it? Or is it not needed?

**Comment by undsoft** [comment]
I've already ported it manually.

**Pull request merged**
