### PR TITLE
Patch 11

### PR DESCRIPTION
**Pull request by fgmGitHub**

### CODE REVIEW

**Review by denysbutenko — APPROVED** [review]
Looks good

**Comment by denysbutenko** [comment]
@undsoft merge it please

**Comment by undsoft** [comment]
@fgmGitHub Please resolve conflicts with master branch.

**Comment by undsoft** [comment]
Somehow the conflicts are still there. :)
What are you doing to resolve them? You should be pulling master branch from origin in your branch.

**Comment by undsoft** [comment]
I think something didn't go right, because now the PR contains no changes (see Files tab).

**Comment by undsoft** [comment]
Sorry, I would have to close this PR. There hasn't been any movement on it for a while and it's still in an invalid state.
We will welcome another PR should you choose to make one.

**Pull request closed without merging**
