### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by MDVAurelien**
Add some French translations

### CODE REVIEW

**Review by undsoft — APPROVED** [review]
Thanks. You can create larger PRs if you want. :)

**Comment by MDVAurelien** [comment]
Thks, OK I thought I understood that small PRs were better for you.

**Comment by undsoft** [comment]
Yeah, but they don't have to be that small. We've had issues with other contributors attempting to translate the whole json file in one go.

**Comment by MDVAurelien** [comment]
Ok that works, anyway I don't have much left to translate. Afterwards it will be corrections only.

**Pull request merged**
