### PR TITLE
NAS-123563 / 24.04 / duplicate "ZFS ARC Result" graphs in reporting section of webUI

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: see ticket

### CODE REVIEW

**Comment by undsoft** [comment]
@AlexKarpov98 Do we understand why the original issue was happening? It appears that those two charts were showing different things.

**Comment by AlexKarpov98** [comment]
@undsoft - seems like data is different, it's the object:

Screenshot 2023-08-29 at 17 32 11

**Comment by AlexKarpov98** [comment]
Screenshot 2023-08-29 at 17 34 57
@undsoft  - we can render it like that, what do you think?

**Review by RehanY147 — CHANGES_REQUESTED** [review]
I agree with what Evgeny said. I'm not sure what to look out for when testing.

**Review by undsoft — CHANGES_REQUESTED** [review]
This approach is correct, thought I think it would be better to have an exception to correct `demand_data` to `Demand Data`.
But titles for some other charts don't look good now, e.g. `Disk I/O sdm - sdm` and `Interface Traffic eno1 - eno1`.

**Comment by AlexKarpov98** [comment]
> This approach is correct, thought I think it would be better to have an exception to correct `demand_data` to `Demand Data`. But titles for some other charts don't look good now, e.g. `Disk I/O sdm - sdm` and `Interface Traffic eno1 - eno1`.

ok, in this case I need to check if there are more than one item with same name - then I'll add an extra title.

**Comment by AlexKarpov98** [comment]
@undsoft @RehanY147
 
Screenshot 2023-09-01 at 15 43 35

Final result

**Review by undsoft — APPROVED** [review]
This works, thanks.

**Comment by AlexKarpov98** [comment]
@RehanY147 - I need your approve for merge :)

**Review by RehanY147 — APPROVED** [review]

**Pull request merged**
