### PR TITLE
NAS-131461 / 25.04 / Listen for apps stats only when have installed apps

### PR DESCRIPTION
**Pull request by denysbutenko**
**Changes:**

Listen for apps stats only when have installed apps

**Testing:**

Check websocket messages

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
`this.installedApps$` will emit every time there is a change to installed apps, leading to more and more subscriptions.

**Comment by denysbutenko** [comment]
> `this.installedApps$` will emit every time there is a change to installed apps, leading to more and more subscriptions.

No extra subscriptions are seen in websocket. Changed operator to `tapOnce` anyway.
image

**Review by undsoft — APPROVED** [review]
It's fine, but probably can be optimized further. For example, we won't unsubscribe here when last app is removed, but that's not a big deal.

**Comment by denysbutenko** [comment]
backport

**Comment by denysbutenko** [comment]
backport

**Pull request merged**
