### PR TITLE
NAS-129988 / 24.10 / Highlight search results with an arrow

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: see ticket.

Result:

https://github.com/user-attachments/assets/f2ce7a01-1bff-4b6c-a6e1-32dd2355b44d

### CODE REVIEW

**Review by denysbutenko — COMMENTED** [review]
https://github.com/user-attachments/assets/6fdcd0de-ecf6-4547-a202-f102ac43e19e

The arrow icon looks disproportionate to me. Maybe look at material icons

**Comment by AlexKarpov98** [comment]
@denysbutenko @undsoft 

https://github.com/user-attachments/assets/44e41bc5-baec-4484-91e5-3d36ee596ccb

what do you think about it now?

**Review by denysbutenko — APPROVED** [review]
Looks good to me

**Review by undsoft — APPROVED** [review]
Yeah, it looks good overall.
I agree that we could make arrow a little bit bigger, for example by stretching it horizontally more.

Also arrow needs to use css variables for primary color and border, because primary color is theme dependent.

**Comment by AlexKarpov98** [comment]
@undsoft - updated.

https://github.com/user-attachments/assets/83909c2c-dc89-4d28-bca8-34796d6f3abe

**Pull request merged**
