### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by MDVAurelien**
Add some French translations

### CODE REVIEW

**Review by undsoft — APPROVED** [review]

**Comment by undsoft** [comment]
@MDVAurelien Please resolve conflicts.

**Review by MDVAurelien — COMMENTED** [review]
Fix

**Comment by undsoft** [comment]
Didn't do it.

**Comment by MDVAurelien** [comment]
> Didn't do it.

sorry no it's me who did it, there was only one line to add I think?

**Comment by undsoft** [comment]
I meant that the conflict is still not resolved. You need to pull master into your branch to resolve the conflict.

**Comment by MDVAurelien** [comment]
I'm going to make a PR because I have other problems with this file. I'm closing this one

**Pull request closed without merging**
