### PR TITLE
NAS-131403 / 25.04 / Use `app.redeploy` endpoint for restart apps

### PR DESCRIPTION
**Pull request by denysbutenko**
**Changes:**

Replace custom implementation.

**Testing:**

You can test it on the app widget on main dashboard

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Let's add this operation to the apps dashboard installed apps table. It's missing from there.

**Comment by denysbutenko** [comment]
> Let's add this operation to the apps dashboard installed apps table. It's missing from there.

Good idea, added

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Table styles got messed up

https://github.com/user-attachments/assets/da62d682-059f-483b-b4ad-89c1f4b64037

**Review by RehanY147 — APPROVED** [review]
Looks good

**Pull request merged**
