### PR TITLE
NAS-129826 / 24.10 / Update enclosure when disks have been updated

### PR DESCRIPTION
**Pull request by bvasilenko**
**Testing**

Use mocks to simulate insertion of a new disk. Same for deletion of existing disk.

When disk has been removed or inserted,

**Expected result:** this disk is being removed from / added to UI

### CODE REVIEW

**Review by RehanY147 — COMMENTED** [review]
@bvasilenko How do I test this? What do you mean by "mocks"?

**Comment by bvasilenko** [comment]
@RehanY147 I meant mock or stub event, which will simulate an insertion of a new disk, and removal of an existing disk

**Review by RehanY147 — COMMENTED** [review]
Evgeny told me to wait for updates.

**Comment by bvasilenko** [comment]
@RehanY147 To test, open two tabs as shown in the screen recording. Add a new pool (or disks to an existing pool). They should appear in the second tab (without refreshing):


https://github.com/user-attachments/assets/7c8f2ae1-57a5-4a5f-9a57-f92294198e6d

**Note**: when deleting a pool or disk, the backend does not send a message in the subscription (`disk.query`), so you will have to refresh the page.

**Review by RehanY147 — APPROVED** [review]
Looks good. Thanks.

**Review by AlexKarpov98 — APPROVED** [review]
Nice 👍

**Pull request merged**
