### PR TITLE
NAS-112012 / 21.10 / Don't show [Manual Test] button as well when disk does not support S.M.A.R.T. test

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Review by RehanY147 — APPROVED** [review]
Looks good

**Review by undsoft — CHANGES_REQUESTED** [review]
Not sure if this PR breaks it, but I get an error every time I try to open the row.
Снимок экрана 2021-09-15 в 12 23 02

**Comment by AlexKarpov98** [comment]
> Not sure if this PR breaks it, but I get an error every time I try to open the row.
> Снимок экрана 2021-09-15 в 12 23 02

I could see also this bug and is not from my commit.

**Review by undsoft — APPROVED** [review]
Looks like a regression that I've introduced. Fixed.

**Pull request merged**
