### PR TITLE
NAS-116088 / 22.12 / NAS-116088: Refactoring quota forms

### PR DESCRIPTION
**Pull request by undsoft**
Testing: 
Two forms.
Dataset context menu -> User Quotas and Group Quotas -> Add.

We used to have to fields to specify users/groups, they were deliberately merged into one.
IxChips gained support for autocomplete.

### CODE REVIEW

**Review by denysbutenko — COMMENTED** [review]
Getting some errors when submitting user form
- when selected `root` user – `[EINVAL] quotas.2.id: user: Setting u quota on s [0] is not permitted.`
- when selecting the same user twice in the chips component - `'NoneType' object has no attribute 'decode'`

**Comment by denysbutenko** [comment]
The action says `Add` but the form allows updating existing user quotas. Not sure it's worth to notify somehow

**Review by denysbutenko — APPROVED** [review]
Otherwise looks good 👍🏻

**Review by denysbutenko — COMMENTED** [review]
image
image
Breadcrumbs does not work

**Comment by undsoft** [comment]
I'll create additional tickets for some of the issues found: one is middleware and one happens on other pages too.

**Pull request merged**
