### PR TITLE
NAS-116009 / 22.12 / Refactoring Dashboard

### PR DESCRIPTION
**Pull request by denysbutenko**
Changes:

- Sync styles for widget header and remove `&nbsp;`. 
- Sync widget gaps
- On the `System Information` widget fill more space on the `Version` row
- Better error handling
- More progressive loading but still have space for improvements
- Fixed a couple of bugs on mobile widgets
- PR includes a fix from #6680 
- add throttle for network updates
- use a new approach for page-header

For testing enable available widgets and check if everything looks good. Try it with a slow connection to feel a full experience. Any comments are appreciated.

### CODE REVIEW

**Comment by denysbutenko** [comment]
I going to do some more changes, marked as a draft

**Review by dszidi — COMMENTED** [review]
In your layout there is more space in between cards. This has the effect that cards grid does not line up with the edge of title bar. Also puts it uncomfortably close to the edge of the screen.

Before:

image




After:

image

**Review by dszidi — COMMENTED** [review]
Network Interface Widgets no longer show realtime stats.

Before:

image



After:

image

**Comment by denysbutenko** [comment]
Changes preview:
https://user-images.githubusercontent.com/351613/168082991-f0b01cf7-e74f-4723-a8a8-866e3342c565.mp4

**Comment by denysbutenko** [comment]
Example of usage throttle to reduce amount of re-rendering:

https://user-images.githubusercontent.com/351613/168084655-e9a8ff72-8e00-44f2-9254-1dc3196f15b3.mp4

https://user-images.githubusercontent.com/351613/168084669-c7ded50f-0efe-4fe1-9292-092321beb5a5.mp4

The same applied to other widgets as well.

**Comment by denysbutenko** [comment]
The first preview uses a local dev server against a cloud VM on a mobile connection.

This one uses a local dev server against a local VM, making another view of how it looks.

https://user-images.githubusercontent.com/351613/168093323-689aab93-210f-461f-9059-17726eb9fa3c.mp4

**Comment by denysbutenko** [comment]
The latest one includes fixes for Network and NIC widgets.
https://user-images.githubusercontent.com/351613/168096620-a70ebb92-0e1f-48f7-9e0b-6e44ef3bb742.mp4

**Review by AlexKarpov98 — APPROVED** [review]
LGTM! 👍

**Pull request merged**
