### PR TITLE
NAS-123469 / 24.04 / Refactor CronCardComponent to ix-table2

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: 
test updated CronCardComponent

### CODE REVIEW

**Review by dszidi — CHANGES_REQUESTED** [review]
The row width shouldn't shrink when details are expanded

image

**Comment by AlexKarpov98** [comment]
> The row width shouldn't shrink when details are expanded
> 
> 
> 
> image
> 
> 

That's the other bug I opened.
Btw - you tested wrong place, you need to test Card, not List page.

**Comment by dszidi** [comment]
> ... That's the other bug I opened. Btw - you tested wrong place, you need to test Card, not List page.
 
 Apologies. I misread one of the file paths from the diff so I also checked the cron page.

**Review by dszidi — APPROVED** [review]
The card in System Advanced works as expected.
 LGTM
 
image

**Pull request merged**
