### PR TITLE
NAS-130698 / 25.04 / Replace `EntityJobComponent` with `jobDialog` method in `ix-cell-state-button`

### PR DESCRIPTION
**Pull request by RehanY147**
**Changes:**

Replaces `EntityJobComponent` with `jobDialog` method in `ix-cell-state-button`

**Testing:**

See if there are any regressions when `ix-cell-state-button` is used

### CODE REVIEW

**Review by bvasilenko — CHANGES_REQUESTED** [review]
Noticed a regression:

1. Go to **Storage > Manage disks**
2. Expand **MIRROR** -> **Choose a disk**, click **Replace** action, and choose a disk, which is not empty (belongs to another exported pool) to _trigger an error_
3. While replacement is in progress, switch to **Jobs** page, and click the state pill

- **Actual result:** no error details are displayed, see video

   

https://github.com/user-attachments/assets/9424ccc3-48b9-43fb-981d-2104389ba3f8


- **Expected result:** error details are displayed

   previously it was displayed like that:

   
   image

**Comment by RehanY147** [comment]
A different ticket will address the issue regarding the missing `takeUntil` ignore statement

**Review by undsoft — APPROVED** [review]
The error is reported now.

**Review by bvasilenko — APPROVED** [review]
Works as expected!

**Pull request merged**
