### PR TITLE
NAS-112710 / 22.02-RC.2 / NAS-112710: Added options to the CA dropdown

### PR DESCRIPTION
**Pull request by RehanY147**
Edit SysLog configuration and change `Syslog Transport` to `TLS`. The `Syslog TLS Certificate` drop down should show up and it should be filled by some selectable options (at least one). Also test form submission.
NAS-112710

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
Waqar update ticket description with additional requirements.

**Review by undsoft — CHANGES_REQUESTED** [review]
1. Since `Certificate` is optional, there should be an option to not select any in dropdown.
2. Values do not appear to be saved.

https://user-images.githubusercontent.com/1481270/139891313-54434282-6c99-4397-af36-931c5cb84a1f.mov

**Comment by undsoft** [comment]
I am mostly done with refactoring Syslog form to new ix forms. You can close this PR and I will address remaining issues in my PR.

**Comment by RehanY147** [comment]
Closing as instructed

**Pull request closed without merging**
