### PR TITLE
NAS-123437 / 24.04 / Disable delete button when snapshot has dependent clones

### PR DESCRIPTION
**Pull request by bvasilenko**
**Summary**
When setting the `recursive` parameter to `true`, the deletion also failed. Therefore, the button was disabled and a tooltip was added.

**Testing**

On Datasets page, after choosing a dataset (for example ix-applications) , and following Manage snapshots hyperlink

Then see ticket please

### CODE REVIEW

**Review by denysbutenko — CHANGES_REQUESTED** [review]
image

There is an issue with UI

**Comment by bvasilenko** [comment]
@denysbutenko the requested changes should be addressed now

**Review by denysbutenko — CHANGES_REQUESTED** [review]
A new docker image is not available. It's needed to validate the fix.

**Review by denysbutenko — CHANGES_REQUESTED** [review]
There is another error appears in the console.

https://github.com/truenas/webui/assets/351613/2063f5d6-5e9c-4468-b45c-22ff3c9ea2e3

**Comment by bvasilenko** [comment]
@denysbutenko requested changes should be addressed now

**Review by denysbutenko — APPROVED** [review]
No errors were observed. Looks good.

**Pull request merged**
