### PR TITLE
NAS-111446 / 21.08 / Layout improvements for Storage widget

### PR DESCRIPTION
**Pull request by denysbutenko**
Testing:
- Take a look at the Storage widget in different states (2, 4, 6 pools) and see if there is something that looks awkward

### CODE REVIEW

**Comment by denysbutenko** [comment]
Before | After
------------ | -------------
x2_before | x2_after

**Comment by denysbutenko** [comment]
Before | After
------------ | -------------
x4_before | x4_after

**Comment by denysbutenko** [comment]
Before | After
------------ | -------------
x5_before | x5_after

**Review by undsoft — APPROVED** [review]
Looking good 👍🏻

**Pull request merged**
