### PR TITLE
NAS-112767 / 22.02 / NAS-112767: Functional approach to IxCombobox

### PR DESCRIPTION
**Pull request by RehanY147**

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
The approach looks good, but I'd to see a loading indicator when user starts typing in user combobox. Right now you have to know that network request is being sent and wait for results.

**Review by undsoft — APPROVED** [review]
Looks good to me. Spinner can be optimized further:
- not to show it before user touches control (i.e. on initial page load).
- not to show it when user selects an option from the list?

@dszidi 
You okay with this indication?

https://user-images.githubusercontent.com/1481270/151559123-6b31ae46-a875-45c7-b9e2-18ca3194f76a.mov

**Review by AlexKarpov98 — APPROVED** [review]
LGTM

**Comment by RehanY147** [comment]
Have to change loader placement because it will be hidden in this case
image

**Comment by RehanY147** [comment]
New loader placement
new loader

**Review by undsoft — APPROVED** [review]
Yes, looks better.

**Pull request merged**
