### PR TITLE
NAS-111315 / 21.08 / Renaming files to match naming convention

### PR DESCRIPTION
**Pull request by undsoft**
All this does is add a linter rule to enforce kebab-style filenames and renames a bunch of files to match the style.
Some imports got auto converted to absolute paths by IDE, enforcing common style of imports is outside of scope for this PR.

No testing is necessary.

### CODE REVIEW

**Comment by AlexKarpov98** [comment]
@undsoft I found some file/folder names as follows. I think these should be changed too.
1. consolepanel
2. pagetitle
3. viewcontrol.ts
4. viewcontroller.ts
5. widgetchart
6. widgetcontroller
7. widgetcpu
8. widgetmemory
9. widgetnic
10. widgetpool
11. widgetsysinfo
12. bootenv.ts
13. cloudcredentials.ts
14. cloudsync
15. kerberossettings.component.ts
16. rsyncconfiguration
17. volumeaddkey
18. volumechangekey
19. alertservice
20. ntpserver
21. manualupdate
22. viewenclosure
23. lockscreen

**Comment by undsoft** [comment]
@AlexKarpov98 Updated.

**Comment by AlexKarpov98** [comment]
@undsoft LGTM.
But one thing I want to mention is that there are different names for `cloud sync`. one is `cloud-sync-task.interface.ts`, the others are `cloudsync-...`.

**Comment by undsoft** [comment]
True, I left them as is, because components are also named inconsistenly, i.e. Cloudsync.

**Review by AlexKarpov98 — APPROVED** [review]

**Pull request merged**
