### PR TITLE
NAS-121123 / 23.10 / Reordered dashboard reversts to initial order

### PR DESCRIPTION
**Pull request by AlexKarpov98**
For testing please follow the ticket details.

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
Pressing Reorder - Cancel is not working now.

**Review by undsoft — CHANGES_REQUESTED** [review]
Order is not saved after Save button is pressed. Reloading will show old order.
https://github.com/truenas/webui/assets/1481270/55b863d2-23c8-4f64-b45f-a562c74e5ba4

**Review by undsoft — CHANGES_REQUESTED** [review]
Reorder widgets, Save, wait without reloading => order reverts back.

**Comment by AlexKarpov98** [comment]
@undsoft - I finally fixed it! please check it.

**Review by undsoft — APPROVED** [review]
It works now, action needs to be adjusted.

**Pull request merged**
