### PR TITLE
NAS-124942 / 24.04 / NFS sessions page

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: see ticket

_I used latest nightly_

Go to http://localhost:4200/sharing/nfs/sessions and see:
Screenshot 2023-11-16 at 14 09 20
Screenshot 2023-11-16 at 14 14 14

You may need to mock data to see results:

Use this mock for NFS 4:
```
[
  {
    "id": "4",
    "info": {
      "clientid": 6273260596088110000,
      "address": "192.168.40.247:790",
      "status": "confirmed",
      "seconds from last renew": 45,
      "name": "Linux NFSv4.2 debian12-hv",
      "minor version": 2,
      "Implementation domain": "kernel.org",
      "Implementation name": "Linux 6.1.0-12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64",
      "Implementation time": [
        0,
        0
      ],
      "callback state": "UP",
      "callback address": "192.168.40.247:0"
    },
    "states": []
  },
  {
    "id": "2",
    "info": {
      "clientid": 6273260587498175000,
      "address": "192.168.50.65:886",
      "status": "confirmed",
      "seconds from last renew": 9,
      "name": "}uIe\u0000\u0000\u0000\u0000426f864f-7197-4864-ae2d-e2fb6b7c58cd",
      "minor version": 2,
      "Implementation domain": "freebsd.org",
      "Implementation name": "FreeBSD 13.2-RELEASE-p4 #3 nfs_stablerestart_handling-n254682-a7af088f940-dirty: Tue Oct 31 10:32:17 PDT 2023\n    root@freebsd13-c:/usr/obj/usr/src/amd64.amd64/sys/MCGKERNEL\n",
      "Implementation time": [
        1293840000,
        0
      ],
      "callback state": "DOWN",
      "callback address": "192.168.50.65:0"
    },
    "states": []
  }
]
```

FOR NFS 3:
```
[{ ip: '10.238.238.162', export: '10.238.238.162:/mnt/tank/nfs' }]
```

As well you can grab that mock data from tests.

___

On sharings dashboard --> NFS card - you should see new option **NFS Sessions**
Screenshot 2023-11-16 at 15 05 53

___

On the Services page you should be able to navigate to NFS sessions as well:

Screenshot 2023-11-16 at 15 06 41

### CODE REVIEW

**Review by RehanY147 — CHANGES_REQUESTED** [review]
The tab header placement is unusual. Doesn't seem consistent with the rest of the UI. Should be discussed or let me know if it's already been discussed.

**Comment by AlexKarpov98** [comment]
@undsoft  @dszidi  - what do you think about it? (check @RehanY147  comment)

**Comment by denysbutenko** [comment]
Just FYI. This approach is being used on the Jobs List (History) page. There is another approach with tabs showing page hierarchy on iSCSI page.

**Comment by dszidi** [comment]
> Just FYI. This approach is being used on the Jobs List (History) page. There is another approach with tabs showing page hierarchy on iSCSI page.

This may be true but there is another competing approach already on this page with the columns selection. Perhaps it would be best to stick with that? 

FWIW I really like the look and feel of the tab style UI element in the screenshots here, however that is probably best left for another discussion about consistently implementing it throughout the entire UI. 

For this specific task, my vote is for keeping it consistent with what's already on the page. Use the same sort of UI element as the columns menu button. Perhaps also make it multi-selectable so if the user wants to, they can see all sessions across either or both protocol versions. 

Advantages:
- consistent
- space efficient

@undsoft what do you think?

**Comment by undsoft** [comment]
I'm okay with the way it looks now tbh. I think about it more like a toggle and not a tab group.

**Comment by AlexKarpov98** [comment]
@undsoft  @dszidi - then let's review/merge it if it's what we need.

**Review by undsoft — APPROVED** [review]
Sessions table works correctly (tested on nfs 3).

**Comment by AlexKarpov98** [comment]
@RehanY147 please review it again so I cam merge.

**Review by RehanY147 — APPROVED** [review]

**Pull request merged**
