### PR TITLE
NAS-128302 / 25.04 / Fix filtering in `excludeManualSelectionDisks`

### PR DESCRIPTION
**Pull request by bvasilenko**
**Testing:**

Please see replication steps in the ticket

### CODE REVIEW

**Review by AlexKarpov98 — COMMENTED** [review]
@bvasilenko - I am not sure how to correctly test this.
Could you provide me with more data please? (you can record a video as well)

**Comment by bvasilenko** [comment]
@AlexKarpov98 

1. Go to **Storage \> Pool Creation Wizard**.
2. At the `Data` step, make automatic disk selection. Click `Manual Disk Selection` and see which disk was selected (`sdb` in this example).
3. Click `Reset Step`.
4. Click `Manual Disk Selection` and add this disk (`sdb`) manually.
5. Go to the `Log` step and configure `Automated Disk Selection`.
6. In the `Data` and `Log` steps, click `Manual Disk Selection`. Selected disks must not be duplicates.

**Note**: before the fix, the `sdb` disk was in both configurations

Expected behavior:

https://github.com/user-attachments/assets/3df7b365-c433-4a91-b1af-02fa6804105f


Behavior before fix:


https://github.com/user-attachments/assets/c5fe0a45-529e-4222-bcce-077603a23ca3

**Review by AlexKarpov98 — APPROVED** [review]
Works as described 👍

**Comment by bvasilenko** [comment]
backport

**Pull request merged**
