### PR TITLE
NAS-110764 / 21.08 / NAS-110764 - New NFS ACL Editor

### PR DESCRIPTION
**Pull request by undsoft**
Congratulations %username%, you have won the lottery to review this PR.

Design: https://xd.adobe.com/view/285bc415-335a-4aff-b632-3e9c6ab7e179-7d08/screen/d629a09e-fe21-4ed6-9def-906e885858d8

**Testing**
Only datasets with acltype = NFS are supported. Posix datasets will keep using old editor.
Create an NFS dataset -> View permissions -> Edit -> Set ACL.

The following scenarios need testing:
- Getting preset prompt after going from Unix Permissions editor.
- Adding acl item, editing, removing, saving.
- Stripping ACL.
- Using preset manually by pressing Use ACL Preset.

**Known issues**
Will be addressed in future PRs:
- No POSIX support
- Radio button alignment does not match design
- Dropdowns are used instead checkbox groups.

### CODE REVIEW

**Comment by denysbutenko** [comment]
Getting error while editing ACL item it says "Ace has errors" and it's not clear what is the error and how to fix it
image

**Comment by denysbutenko** [comment]
Can't view/edit permissions after stripping acl items
image

**Review by denysbutenko — APPROVED** [review]
image
Looking nice 👍🏻

**Comment by undsoft** [comment]
Resolved the issue about selecting root user. (Root user has uid of 0, "if" failed :))
Could not reproduce second issue, confirmed with Denys. Will continue to observe if issue happens again.

**Pull request merged**
