### PR TITLE
NAS-129146 / 25.04 / Slow scroll behaviour on Apps screen

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: see ticket. 
This is an alternative fix for https://github.com/truenas/webui/pull/10477.
Read comments there.

### CODE REVIEW

**Review by bvasilenko — CHANGES_REQUESTED** [review]
I could replicate same issue, as in https://github.com/truenas/webui/pull/10477
Using chrome, with scale 90%

**Comment by AlexKarpov98** [comment]
> I could replicate same issue, as in https://github.com/truenas/webui/pull/10477
> 
> Using chrome, with scale 90%

Ah okay, gonna check it out 👌🏼

**Comment by AlexKarpov98** [comment]
@bvasilenko - right now it works correctly for me. Try it out now.

**Review by RehanY147 — APPROVED** [review]
I can see the issue fixed on both Firefox and Chrome. Thanks. I can close my PR.

**Comment by bvasilenko** [comment]
@AlexKarpov98 Perfect! The issue is fixed now!

**Review by bvasilenko — APPROVED** [review]

**Pull request merged**
