### PR TITLE
NAS-130365 / 25.04 / Improve Add Alert Service > Level Tooltip 

### PR DESCRIPTION
**Pull request by AlexKarpov98**
**Changes:**

Tooltip text change.

**Testing:**
Code review is enough.

|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   | Tooltip text change.

### CODE REVIEW

**Review by undsoft — APPROVED** [review]
Looks good, thanks.

**Comment by AlexKarpov98** [comment]
backport

**Comment by AlexKarpov98** [comment]
backport

**Comment by AlexKarpov98** [comment]
backport

**Pull request merged**
