### PR TITLE
NAS-133051 / 25.04 / Reorganize iSCSI wizard + NAS-133051 new form controls to handle fibre ports

### PR DESCRIPTION
**Pull request by bvasilenko**
**Changes:**

1. Built controls specific to Fibre ports  ( [NAS-133051](https://ixsystems.atlassian.net/browse/NAS-133051) Build form controls to handle fibre ports )
2. Used these controls in iSCSI wizard  ( [NAS-132835](https://ixsystems.atlassian.net/browse/NAS-132835) Reorganize iSCSI wizard )

**Testing:**

Log into http://m50-143.dc1.ixsystems.net/

Go to  **iSCSI Wizard** 

Walk through 2 scenarios:
1. Choose option **iSCSI** and complete the wizard
2. Choose option **Fibre Channel** and complete the wizard

### Downstream

|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   | Newly added  **iSCSI** / **Fibre Channel** radio button group in the wizard
|Documentation   | Newly added blocks **Protocol options** for iSCSI, and **Protocol options** for Fibre Channel

### CODE REVIEW

**Review by AlexKarpov98 — APPROVED** [review]
Wizard works in some cases, but I noticed some issues.

1. `Create New`  should be first option, currently it's last option. Same for other inputs where we can Create New.

https://github.com/user-attachments/assets/54fb3981-7e5f-4ab4-a18c-a0e377d1784a

2. When fibre channel is submitted with error, Target is created anyways and then when I want to make an update to the form and submit it -- i get an error that target has already been created.

https://github.com/user-attachments/assets/ffba4e86-b230-40d7-af9d-d45b8292e4f9

3. I was not able to submit successfully with any of the provided `Ports` options.

https://github.com/user-attachments/assets/ea80c16a-fd61-4ee4-8f0c-4bbf9347bf5d

4. Loading indicator does not stop immediately after receiving an error, but after some delay.

https://github.com/user-attachments/assets/ddaa6f21-c860-43b9-a856-de3e3d0c6827

**Review by AlexKarpov98 — CHANGES_REQUESTED** [review]
Approved by mistake. Sorry

**Comment by bvasilenko** [comment]
@AlexKarpov98 point "3" is blocked by middleware, the rest is ready for review

**Comment by AlexKarpov98** [comment]
> @AlexKarpov98 point "3" is blocked by middleware, the rest is ready for review

@bvasilenko - is there any related middleware ticket? Can you link it to the current ticket?

**Comment by bvasilenko** [comment]
@AlexKarpov98 sure there was one, now it's linked to the current ticket

**Review by AlexKarpov98 — APPROVED** [review]
Issues resolved 👌 
Middleware Issues with ports are known.

I've noticed that there's such error as well: (if creation was not successful, on the second submit)
Screenshot 2024-12-25 at 12 19 37

**Pull request merged**
