### PR TITLE
NAS-120260 / 22.12.2 / Removed mixed disks warning

### PR DESCRIPTION
**Pull request by RehanY147**
Removed the mixed disks warning as the logic was wrong according to middleware

### CODE REVIEW

**Comment by undsoft** [comment]
Eh, it was my understanding that the warning in this specific case was wrong (and needs to be fixed), not that it shouldn't be there at all.

**Review by undsoft — CHANGES_REQUESTED** [review]
See comment.

**Comment by RehanY147** [comment]
@undsoft I talked to Caleb and he said it's best to remove this warning as the logic is all wrong and UI shouldn't decide if mixed disks capacity exists.

**Comment by RehanY147** [comment]
@undsoft I also explained the logic UI had for showing this warning and he still wanted it removed.

**Review by undsoft — CHANGES_REQUESTED** [review]
See ticket comment.

**Comment by RehanY147** [comment]
new PR https://github.com/truenas/webui/pull/7804

**Pull request closed without merging**
