### PR TITLE
NAS-114383 / 13.0 / NAS-114383: Fixing logic of joining disks and enclosures

### PR DESCRIPTION
**Pull request by bvasilenko**
Summary:
- adapted the UI code to a new response of `enclosure.query` (use new parameters `{ extra: { pools: true } }`)
- changed order so that controller module are always displayed at the top 

Testing:
1. connect your setup to testing machine `m60-100.dc1.ixsystems.net` 
2. System -> View Enclosure

https://user-images.githubusercontent.com/20611516/156405176-31fad5e9-987e-4df6-891e-77b3a18c1344.mp4
- "m60" module should be on the top
- check that disks are displayed at proper slots in each enclosure (
   - first ~24 front
   - others ~100 disks each
- check that table rows contain proper sensor data on each tab for each enclosure

https://user-images.githubusercontent.com/20611516/156405198-115d0653-34fa-4239-be93-1c72306ca405.mp4
- check Front - should contain ~23 disks
- check Rear - should contain 4 disks

### CODE REVIEW

**Review by dszidi — COMMENTED** [review]
So far have tested against the machine mentioned in the description. Controller is on top and disks are in the correct order. I have noticed some odd behavior though. If I navigate to another browser tab, all the enclosure selector images are gone.

image

**Comment by dszidi** [comment]
Agreed. At minimum we should test M-Series, Mini and non M-Series Rackmount

**Review by dszidi — COMMENTED** [review]
Testing on an R20, and when selecting "Rear", the elements to the left and right of the server visualization no longer update.

image

**Review by dszidi — COMMENTED** [review]
Also there should be other elements showing up in the enclosure navigation other than just disks view. Seems there is a backend issue related to that and a ticket exists

https://jira.ixsystems.com/browse/NAS-115427

**Comment by dszidi** [comment]
The R20 test system has been hot patched and the navigation issue is resolved.
The other issue with the elements to the left and right of the visualization still remain

**Comment by dszidi** [comment]
Enclosure.query returns temperature sensors but they don't show up as a tab. Also the 

image

**Comment by dszidi** [comment]
Also the enclosure label is missing

image

**Review by dszidi — COMMENTED** [review]
Please see above comments

**Comment by bvasilenko** [comment]
@dszidi  Thanks for providing descriptions and screenshots. I've fixed the issues you've found so far.

**Review by dszidi — COMMENTED** [review]
I tested it again and editing the label seems to have no effect even if I navigate away and come back. It seems the call is being successfully sent. This might be a backend issue. I'm waiting for a response from somebody on middleware team.

image

**Comment by bvasilenko** [comment]
@dszidi 

> I tested it again and editing the label seems to have no effect even if I navigate away and come back. It seems the call is being successfully sent. This might be a backend issue. I'm waiting for a response from somebody on middleware team.
> 
> image

I have pushed a fix for this issue. Now it works fine with m60 test machine.

**Comment by bvasilenko** [comment]
> I checked the backend and it seems enclosure.query is saying da406 is in the controller but disk.query, which also gives enclosure and slot info, is saying that da406 is in enclosure number 6. This mismatch is likely the cause of the problem.

I got clarification from the back-end team. There doesn't seem to be a problem. The controller head-unit is actually enclosure number 6.

**Review by dszidi — APPROVED** [review]
After finally getting a suitable test machine, PR behaves as expected. All VDEVS are properly represented and label editing functionality is working.

LGTM

**Pull request merged**
