### PR TITLE
NAS-127041 / 24.10 / Removed `filesize` and `ngx-filesize` libraries in favor of custom methods

### PR DESCRIPTION
**Pull request by RehanY147**
Test for regressions

### CODE REVIEW

**Review by bvasilenko — CHANGES_REQUESTED** [review]
I've noticed a bit/byte convertion error at the Dashboard, Network widget, interface bandwidth

image

**Comment by RehanY147** [comment]
@bvasilenko The data on that page comes in bytes from middleware. We want to show all bandwidth data in bits so it is converted. You're supposed to implement the conversion. So, if middleware said sent 28360 bytes, that should translate to 226 kb/s roughly.

**Comment by bvasilenko** [comment]
@RehanY147 Ok, then it looks good! Please re-request review, so I could approve

**Comment by RehanY147** [comment]
@bvasilenko I've asked for your review

**Review by bvasilenko — APPROVED** [review]
Works good!

**Comment by RehanY147** [comment]
backport

**Comment by RehanY147** [comment]
backport

**Pull request merged**
