### PR TITLE
NAS-126801 / 24.10 / Accessing the email set up a second time requires a screen refresh when accessed and also the UI reverts to the General page

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Testing: see ticket and result: 👇 

https://github.com/truenas/webui/assets/22980553/9bfe6363-425a-4bde-93b8-6d97d0ec2cfd

### CODE REVIEW

**Review by denysbutenko — APPROVED** [review]
Looks good

**Comment by AlexKarpov98** [comment]
backport @bugclerk

**Comment by AlexKarpov98** [comment]
backport

**Comment by AlexKarpov98** [comment]
backport now

**Comment by AlexKarpov98** [comment]
backport

**Pull request merged**
