### PR TITLE
NAS-122065 / 23.10 / Replace the IxSlideInService with a new IxSlideInService

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Comment by AlexKarpov98** [comment]
> https://github.com/truenas/webui/pull/8197/files

is it the same PR as this one?

**Comment by undsoft** [comment]
Okay that PR got merged, probably easier to start a new one if there are any old usages that remain. When refactoring avoid using `slideInService.closeLast()`, the idea is that you'll have `slideInRef` like `matDialogRef` that you can use to close component.

Also instead of using methods from a component like this `componentInstance.setupForm()`, we should now pass arguments via `data` and they'll be available via `SLIDE_IN_DATA` token inside.

**Comment by bvasilenko** [comment]
@AlexKarpov98 once PR is ready for review, please remove "WIP" from the description

**Review by undsoft — APPROVED** [review]
Looks good.

**Pull request merged**
