### PR TITLE
NAS-130056 / 24.10 / Missing widgets in the widget-group form options

### PR DESCRIPTION
**Pull request by denysbutenko**
**Changes:**

Refresh supported widgets on layout changes. 

**Testing:**

Check demo in ticket

### CODE REVIEW

**Review by AlexKarpov98 — COMMENTED** [review]
@denysbutenko - I was not able to find `CpuUsageGauge, CpuUsageRecentWidget, CpuTemperatureBar` widgets.
Screenshot 2024-07-20 at 09 30 01

**Comment by denysbutenko** [comment]
> @denysbutenko - I was not able to find `CpuUsageGauge, CpuUsageRecentWidget, CpuTemperatureBar` widgets.
> 
> Screenshot 2024-07-20 at 09 30 01
> 
> 

It depends on selected slot size. Did you mean expected to see all CPU widgets regardless slot size?

**Review by AlexKarpov98 — COMMENTED** [review]
Once I start with Full Size layout - I only see 1 option value in CPU Widget Type.
Even when I change layout - I don't see expected widgets. 
They only show up if I change `widget category` and then reselect `CPU` widget category -- see it on the video below 👇 

https://github.com/user-attachments/assets/dec76093-b07d-4dcc-af6a-f9f5e1f2360d

**Comment by denysbutenko** [comment]
A new solution would show all available widgets and disable unsupported widget options depending on the selected slot size.

**Comment by undsoft** [comment]
I've discussed how to best show widget options with Damian.
Let's show all widgets in the category, even if they don't support current size, but have them be at the end of the list disabled.

**Review by AlexKarpov98 — COMMENTED** [review]
Adding comment to receive an update that it's ready for review.
Denys -```Hey - just need to sort options, I will do update soon`

**Review by AlexKarpov98 — APPROVED** [review]
Nice, it works now 👍

**Pull request merged**
