### PR TITLE
NAS-130213 / 24.10 / Add smaller apps widgets

### PR DESCRIPTION
**Pull request by denysbutenko**
**Changes:**

1. Widget App Component was sliced into multiple small components
2. Added widget-app-cpu (Quarter size)
3. Added widget-app-memory (Quarter size)
4. Added widget-app-info (Half size)
5. Added widget-app-network (Half size)

image

**Testing:**

Check details in ticket

### CODE REVIEW

**Comment by denysbutenko** [comment]
One thing is missing. I'll notify when it is ready for review.

**Review by AlexKarpov98 — COMMENTED** [review]
@denysbutenko - please re-request review once it's ready 😃

**Comment by denysbutenko** [comment]
@AlexKarpov98, it's ready for review but blocked for testing. The recent changes in master branch break compatibility with the DF API. Waiting for adding support to make basic app CRUD actions.

**Comment by denysbutenko** [comment]
Tracking #10394 to be merged

**Review by undsoft — COMMENTED** [review]
This PR for apps changes has been merged. This PR is now unblocked https://github.com/truenas/webui/pull/10394

**Comment by denysbutenko** [comment]
Since stats are unavailable, new widgets do not work.
Half of `widget-app` can be tested only (app image, app version, app status)

**Review by undsoft — APPROVED** [review]
As discussed on Slack, we've decided to hide apps widgets for Electric Eel. 
This PR can be merged in, but we need to hide widgets from the widget registry.

**Pull request merged**
