### PR TITLE
NAS-114143 / 22.12 / Nas 114143 Deleted the translation for the keys of object

### PR DESCRIPTION
**Pull request by Raz-Dva**
Check the NIC interface widgets.
Check out other similar widgets.
Widgets should be displayed in the same way in different languages.
An enum was created to replace strings.

### CODE REVIEW

**Review by denysbutenko — APPROVED** [review]
Looks good

**Comment by Raz-Dva** [comment]
backport

**Comment by Raz-Dva** [comment]
backport

**Comment by Raz-Dva** [comment]
backport

**Pull request merged**
