### PR TITLE
NAS-119103 / 22.12 / Highlight degraded vdevs and other minor fixes

### PR DESCRIPTION
**Pull request by undsoft**
Changes:
* Degraded pools are now shown in orange.
* Hit area on back button in mobile details increased.
* In some places WidgetUtils replaced with filesize.

### CODE REVIEW

**Comment by undsoft** [comment]
@dszidi Can't say that orange looks particularly great, but so far nothing looks too good.

**Review by dszidi — COMMENTED** [review]
@undsoft ^^

**Comment by undsoft** [comment]
Ok, fn-theme-orange still has white text, but fn-theme-yellow looks okaish.

**Review by dszidi — COMMENTED** [review]
We should stick with orange IMO because that is the status color we're using in other places in the UI. (Storage Dashboard, data protection task status etc)

We should be able to change the text color in `.fn-theme-orange` by modifying the `orange-txt` css var in `src/assets/styles/scss-imports/cssvars.scss`

**Review by AlexKarpov98 — COMMENTED** [review]
Code looks good to me (UI not checked yet)

**Review by denysbutenko — APPROVED** [review]
image

Looks good to me

**Comment by undsoft** [comment]
@dszidi I think I'm going to keep it yellow for now. Other changes seem to be more intrusive and we can tweak it later as needed.

**Pull request merged**
