### PR TITLE
NAS-116333 / 22.12 / Add ix-tree

### PR DESCRIPTION
**Pull request by denysbutenko**
Work in Progress. Appreciate your feedback.

ToDo:

- Add harnesses
- Improve reusability/clean up code

Preview

https://user-images.githubusercontent.com/351613/172841005-ab320fc4-c04e-45bf-8d95-0339263eee19.mp4

### CODE REVIEW

**Comment by RehanY147** [comment]
I know this is WIP right now. Just mentioning this.
I don't see indentation for nested nodes. Everything exists on the same indentation
image

**Comment by RehanY147** [comment]
Also, on a smaller laptop screen, the details view goes completely out of view towards the right and no scroll available. So we should add a scroll at least when things go out of bounds. @undsoft thoughts on how to handle smaller screens?

**Comment by denysbutenko** [comment]
image

Fixed indentation for nested nodes. I'm digging into grid layouts to get pretty columns back

**Comment by denysbutenko** [comment]
Preview latest changes

https://user-images.githubusercontent.com/351613/173323775-2daa0062-049f-411e-844a-5be9cb684f80.mp4

**Comment by denysbutenko** [comment]
> Also, on a smaller laptop screen, the details view goes completely out of view towards the right and no scroll available. So we should add a scroll at least when things go out of bounds. @undsoft thoughts on how to handle smaller screens?

As a thought to make a tree component resizable by the x-axis. So, a user can drag the card on the edge and resize it horizontally. For example, the tree column takes 30% width and can be extended up to 50% or something.

**Comment by denysbutenko** [comment]
> Preview latest changes
> 
>  Kapture.2022-06-13.at.14.57.37.mp4

sticky node labels

https://user-images.githubusercontent.com/351613/173327406-d3633dbc-2af8-4202-9b27-063f11329826.mp4

**Review by undsoft — APPROVED** [review]
Looks good, nice work.
Let's either add tests or remove test stubs before merging.
Dataset row can be extracted in a separate component either now or in the future.

**Pull request merged**
