### PR TITLE
NAS-108328 / 12.0 / Nas 108328 - Show all types of memory data on dashboard

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Remove inactive from Services on dashboard memory card

### CODE REVIEW

**Review by erinix — APPROVED** [review]
lgtm

**Review by william-gr — CHANGES_REQUESTED** [review]
There was some misunderstanding.

We still need to show all the other values. What I asked is if there was some way to group some values in the graph itself

Like Free and Inactive be inside Available
And ZFS Arc inside Wired.

**Comment by dszidi** [comment]
According to the ticket, this now requires new middleware before progress can be made.

**Comment by undsoft** [comment]
How about closing this PR and adding a comment to ticket that there is some code ready in branch?

**Comment by undsoft** [comment]
Closing for inactivity.

**Pull request closed without merging**
