### PR TITLE
NAS-110927 / 12.0 / No UI option to change the readonly state of a ZVOL.

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
When comparing to datasets, datasets also support "inherit" option for read only field.
Looks like readonly on zvols can also be set to inherit, so we need to support this value.
Example from table:
Снимок экрана 2021-06-14 в 16 26 11

**Comment by AlexKarpov98** [comment]
> When comparing to datasets, datasets also support "inherit" option for read only field.
> Looks like readonly on zvols can also be set to inherit, so we need to support this value.
> Example from table:
> Снимок экрана 2021-06-14 в 16 26 11

Fixed

**Review by undsoft — APPROVED** [review]
Looks good, thank you. 
Снимок экрана 2021-06-16 в 12 22 54

**Comment by undsoft** [comment]
@AlexKarpov98 
Can you check if need to do the same for Scale?

**Comment by AlexKarpov98** [comment]
@undsoft Yeah, we need to add it on Scale as well.

**Comment by undsoft** [comment]
Don't know if this can be backported, but if it can, you can add 'backport-21.08' label and add 'backport' comment.

**Comment by AlexKarpov98** [comment]
I don't think it can't be backported, it needs to be updated manually.

**Pull request merged**
