### PR TITLE
NAS-116570 / 22.12 / NAS-116570: Refactoring cloudcredentials form

### PR DESCRIPTION
**Pull request by undsoft**
Testing:
Credentials -> Backup credentials -> Add / Edit Credential.

Known issues:
- When form has validation errors, they may be shown in the dialog instead of the form.
- In Cloudsync Task form instead of Add new option in Credentials select there is now a link to go to Backup Credentials.

### CODE REVIEW

**Review by AlexKarpov98 — CHANGES_REQUESTED** [review]
The code change is great.
A link to go to Backup Credentials does work correctly.
Screenshot_34

**One issue:**
When editing a cloud credential with a `Google Cloud Storage,` the action buttons on the bottom inside the form are only enabled in case an authentication file is changed. i.e, they are still disabled even when a name is changed.
Screenshot_35

**Comment by undsoft** [comment]
Thanks. Kinda fixed.

**Comment by AlexKarpov98** [comment]
There are some conflicts.

**Review by AlexKarpov98 — APPROVED** [review]
Code change looks good.

**Pull request merged**
