### PR TITLE
NAS-122087 / 23.10 / Add Category View

### PR DESCRIPTION
**Pull request by denysbutenko**
For testing, check the `View All <category-name>` buttons on the Discover Apps (Available). Make sure navigation forth-and-back works well.

Worth mentioning: The pageTitle component has a `loading` param to show the `ix-fake-progress-bar` passing just a boolean.

### CODE REVIEW

**Comment by bvasilenko** [comment]
@denysbutenko When I checkout the branch, then click `View All <category-name>`, CPU usage jumps to 100% and the browser tag hangs. Maybe there's an endless cycle?

**Review by bvasilenko — CHANGES_REQUESTED** [review]
Hit a bug, please see my commentary

**Comment by denysbutenko** [comment]
@bvasilenko ping

**Review by bvasilenko — APPROVED** [review]
Works good!

**Pull request merged**
