### PR TITLE
NAS-120371 / 23.10 / Replace mat-icon with ix-icon

### PR DESCRIPTION
**Pull request by denysbutenko**
The `mat-icon` component was replaced with the `ix-icon` component, and logos now have the prefix `logo_` for example, `truenas_scale_logo_full` becomes `logo_truenas_scale_full`. This change was made to allow CSS selectors to unset the width and height of logos. As a result, the `mat-icon` selector in BDD tests has been updated to reflect the new component. Please look at the affected parts for any regressions to ensure there are no adverse effects from this change.

### CODE REVIEW

**Comment by AlexKarpov98** [comment]
Search icon is missalligned: 

Screenshot 2023-02-24 at 10 59 09

**Comment by AlexKarpov98** [comment]
Icons in buttons misaligned: 

Screenshot 2023-02-24 at 11 00 27

Screenshot 2023-02-24 at 11 00 40

**Comment by AlexKarpov98** [comment]
Screenshot 2023-02-24 at 11 07 14

Enclosure page is broken (not sure if it's related to this PR)

**Comment by AlexKarpov98** [comment]
Password input icon misaligned:

Screenshot 2023-02-24 at 11 08 29
Screenshot 2023-02-24 at 11 09 02

**Review by AlexKarpov98 — CHANGES_REQUESTED** [review]
Overall it looks good, but we need to fix few things I noticed and mentioned in comments.

**Comment by denysbutenko** [comment]
@AlexKarpov98 okay, done with fixes.

**Review by AlexKarpov98 — CHANGES_REQUESTED** [review]
Icons looks good now, but still 1 problem remains.

Password icon is still misaligned
Screenshot 2023-03-01 at 11 44 31
Screenshot 2023-03-01 at 11 45 36

**Comment by denysbutenko** [comment]
@AlexKarpov98 thanks; the icon position has been updated.

**Review by AlexKarpov98 — APPROVED** [review]
Nice job!
👍

**Pull request merged**
