### PR TITLE
NAS-116408 / None / NAS-116408: Permissions editor for new storage section

### PR DESCRIPTION
**Pull request by undsoft**
Mostly copies existing dataset permissions over.
Testing: select a dataset (some rows may not work, because they shouldn't be in the table), test dataset card and edit functionality.
For edit, 3 screens exist: trivial permissions, ACL for datasets with POSIX ACL type and ACL for datasets with NFS ACL type.

Known issues: styles are not finished and some TODO comments are not addressed. Will fix separately.

### CODE REVIEW

**Review by denysbutenko — APPROVED** [review]
Looks good to me

**Review by RehanY147 — APPROVED** [review]
Looks good.

**Comment by RehanY147** [comment]
Although, the font size for these new cards looks too large relatively.

**Comment by undsoft** [comment]
I agree, but it's based on design.

**Pull request merged**
