### PR TITLE
NAS-110434 / 21.06 / Cant Use upercase letters for name of new app

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Comment by undsoft** [comment]
Can we also show an error as user types in the field or even prevent user from typing uppercase characters in the first place?

**Comment by Ornias1993** [comment]
@AlexKarpov98 I hope you're aware that the app name is used in quite a few places in Helmcharts, some of which do NOT allow uppercase?

**Comment by AlexKarpov98** [comment]
> Can we also show an error as user types in the field or even prevent user from typing uppercase characters in the first place?

Exactly that's the normal behavior of validation in UI. But in this case, the app install is based on dynamic schema and the validation is also performed on middleware side. The validation logic might be updated anytime on middleware as well.
So don't think we can add UI validation at this moment.

**Comment by Ornias1993** [comment]
@AlexKarpov98 Ahh shot I was mistaken, this is actually the error for when users try it, not trying to allow users to do this. Sorry.!

**Review by Ornias1993 — APPROVED** [review]

**Comment by undsoft** [comment]
We need to add the same behaviour when user presses blue Launch Docker Image on top.

**Comment by AlexKarpov98** [comment]
> > We need to add the same behaviour when user presses blue Launch Docker Image on top.
> 
> I read that the "Big Blue Button" is also moving to dynamic UI config, shouldn't that already consume this codepath?

Exactly, we are going to move ix-chart to dynamic way. So hopefully this behavior will be applied to ix-chart as well.

**Review by undsoft — APPROVED** [review]
Okay, then it looks good.

**Pull request merged**
