### PR TITLE
NAS-110523 / 13.0 / NAS-110523: Sets checksum to SHA512 by default and adds a warning

### PR DESCRIPTION
**Pull request by undsoft**
Adds a new checksum select in dataset form. Select defaults to Inherit. When deduplication is enabled, we change checksum to SHA512 and warn user about this.

### CODE REVIEW

**Comment by denysbutenko** [comment]
image
The warning dialog appears on explicit change

image
No warning on initial values. Is it expected?

**Comment by denysbutenko** [comment]
image
The warning dialog appears on explicit change

image
No warning on initial values. Is it expected?

**Review by denysbutenko — APPROVED** [review]
Looks good

**Comment by undsoft** [comment]
> No warning on initial values. Is it expected?
I guess so, we don't show warnings about deduplication when Dedup ON is inherited.

**Comment by undsoft** [comment]
backport

**Comment by undsoft** [comment]
backport

**Pull request merged**
