### PR TITLE
NAS-119607 / 23.10 / Storage -> Disks if one disk details toggled, all the disks are toggled as well

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Go to disks and check that once you open details for one disk, it's only opened for one disk.
As well check other expandable table rows, like `S.M.A.R.T. Test Results..`
Screenshot 2022-12-27 at 18 09 19

### CODE REVIEW

**Review by undsoft — CHANGES_REQUESTED** [review]
There is a `getRowIdentifier` that you may be able to use.
I would also like to understand what changed that broke this.

**Review by RehanY147 — CHANGES_REQUESTED** [review]
We can use `UUID.UUID()` instead to get a unique id. `Math.random` isn't always going to be unique by design even if rare

**Comment by AlexKarpov98** [comment]
> There is a `getRowIdentifier` that you may be able to use. I would also like to understand what changed that broke this.

as I see there was simply no `ID` field is some places and in code we have `item.id` checks.

**Review by undsoft — APPROVED** [review]
Alex explained that the issue appeared because of changes here https://github.com/truenas/webui/pull/7451/files

**Review by RehanY147 — APPROVED** [review]

**Pull request merged**
