### PR TITLE
NAS-123115 / 23.10 / Minor fixes for tables

### PR DESCRIPTION
**Pull request by denysbutenko**
Check details in the ticket

### CODE REVIEW

**Comment by renediepenbroek** [comment]
Hello Denys,

Question: how do I get 'push acces' in Github? I want to push my 100% 
translated NL.JSON file but I have no rights to do so (also not in my 
own fork).

Thanks for the information.

Best regards,

René Diepenbroek
The Netherlands



------ Oorspronkelijke bericht ------
Van "codecov[bot]" ***@***.***>
Aan "truenas/webui" ***@***.***>
CC "Subscribed" ***@***.***>
Datum 26-7-2023 15:14:15
Onderwerp Re: [truenas/webui] NAS-123115 / 23.10 / Minor fixes for 
tables (PR #8487)

**Comment by undsoft** [comment]
@renediepenbroek You should fork master, make changes in your fork and then create a PR back like you used to do before.

**Comment by denysbutenko** [comment]
Hi @renediepenbroek, articles on how to do that are available on GitHub docs, e.g.
https://docs.github.com/en/get-started/quickstart/fork-a-repo
https://docs.github.com/en/get-started/quickstart/contributing-to-projects

**Review by undsoft — APPROVED** [review]
The first item `Static routes table overflows on some resolutions.` is not fixed, but I will merge anyway.

**Pull request merged**
