### PR TITLE
NAS-114471 / None / Sync link styles across pages

### PR DESCRIPTION
**Pull request by AlexKarpov98**
Screenshot_5
Screenshot_6

### CODE REVIEW

**Comment by denysbutenko** [comment]
Just a thought: would it be possible to use a CSS selector like `a[href*="//"]` (an example) to determine external links instead of adding an `external-link` class?

**Review by undsoft — CHANGES_REQUESTED** [review]
Would be good preserve some of the existing translations, as in fr.json and maybe others.

**Comment by undsoft** [comment]
> Would be good preserve some of the existing translations, as in fr.json and maybe others.

This point still stands.

**Review by undsoft — CHANGES_REQUESTED** [review]
Need to recover translation files.

**Review by undsoft — APPROVED** [review]
Thanks

**Pull request merged**
