### PR TITLE
NAS-131213 / 25.04 / Refactor out `auth.two_factor_auth`

### PR DESCRIPTION
**Pull request by bvasilenko**
**Changes:**

Refactoring for login page

**Testing:**

Test logging in using both regular credentials and 2FA , and number of calls should be less than it was before.

### CODE REVIEW

**Comment by bvasilenko** [comment]
@RehanY147 it turned out that I need to work more on this one. please reject, so I could request a re-review once I'm done

**Review by RehanY147 — COMMENTED** [review]
Waiting for more changes

**Review by RehanY147 — CHANGES_REQUESTED** [review]
Follow these steps
- Setup 2FA for user
- Go to login page
- Enter username/password and click the login button. The 2FA input will show up
- Click Cancel to go back to the original login page
- Enter username and password again and click 'Login'
You will see the following error shown in the screenshot
Expect:
User can login with new credentials
Actual:
User is shown an error about login in progress? 
image

**Comment by anodos325** [comment]
> Follow these steps
> 
>     * Setup 2FA for user
> 
>     * Go to login page
> 
>     * Enter username/password and click the login button. The 2FA input will show up
> 
>     * Click Cancel to go back to the original login page
> 
>     * Enter username and password again and click 'Login'
>       You will see the following error shown in the screenshot
>       Expect:
>       User can login with new credentials
>       Actual:
>       User is shown an error about login in progress?
> 
> 
> image

**Review by RehanY147 — CHANGES_REQUESTED** [review]
The eslint rule change seems out of the scope of this ticket.

**Review by anodos325 — APPROVED** [review]

**Comment by bvasilenko** [comment]
@RehanY147 it's now should be good to re-review this one

**Review by RehanY147 — APPROVED** [review]

**Pull request merged**
